/**
 * Shared recovery vocabulary for runtime errors, local help, the manual and skills.
 *
 * A fix that names a server writes the placeholder, never an origin: this table
 * is compiled into the installed skill and printed by `afbin help errors`, and
 * both are rendered for the SELECTED server (src/teaching-origin). A
 * self-hoster must not be told to install from someone else's box.
 */
import {TEACHING_BASE} from './teaching-origin';
export const diagnosticCatalog:Record<string,{meaning:string;fix:string}>={
 approval_origin_mismatch:{meaning:'The selected server advertises its browser approval page on a different origin, and has not published that origin as another address of itself, so the pairing cannot be trusted for the selected origin.',fix:'Select the server by its public origin with --server; credentials are never sent to an origin you did not select.'},
 unmanaged_installation:{meaning:'This afbin was not installed as a verified standalone executable.',fix:`Install it with ${TEACHING_BASE}/chat/install.sh, then rerun afbin update.`},
 compatible_release_unavailable:{meaning:'No published release matches the version and protocol the selected server named.',fix:'Retry after a compatible CLI release is published; afbin update --dry-run reports what it resolved.'},
 outside_workspace:{meaning:'The destination is outside the workspace afbin runs in.',fix:'Write inside the workspace, e.g. --output shot.png, and move the file afterwards if it must live elsewhere.'},
 sql_in_argument:{meaning:'A query argument was SQL; arguments name the datasets or documents to query.',fix:'Put the SQL in a file and run afbin query <ref> --input query.sql, or pipe it: afbin query <ref> --input - < query.sql.'},
 image_fetch_failed:{meaning:'The server could not fetch an external image URL named by the document.',fix:'Check the URL is public and reachable, or register the local image with afbin add --json and reference its returned ID.'},
 dataset_read_only:{meaning:'The dataset does not accept row mutations: Postgres datasets are read-only and stored datasets need access: readwrite.',fix:'Publish a stored dataset with afbin push <file> --type dataset --access readwrite; Postgres datasets cannot be written.'},
 renderer_unavailable:{meaning:'This representation requires a published head, and this target is not one.',fix:'Use PNG/JPG for a local JSX image, push before exporting the HTML offline file, or export csv, json, yaml or original.'},
 unsupported_version_export:{meaning:'This target has no version to show: the published viewer opens the head, and a local file is a draft rather than a history.',fix:'Export a published id at a version (afbin export <id>@<n> --format png), open the head, or afbin pull <ref>@<n> for that content.'},
 previous_engine_version:{meaning:'That version was written for the previous query engine and needs converting by hand, so it cannot be restored as it stands.',fix:'Read it with afbin pull <id>@<v> --output -, carry what you need into the current document by hand, then afbin push.'},
 unpublished_draft:{meaning:'The published viewer requires a published, unchanged document.',fix:'Use afbin preview <path> for local drafts, or publish with afbin push, then open it.'},
 not_forkable:{meaning:'A folder names the original children and a Postgres dataset keeps its bound secret.',fix:'Fork a document, dataset rows or a file.'},
 output_exists:{meaning:'The destination is taken; fork and export never replace a source or an existing file.',fix:'Choose a free --output path, or use export --force to replace it after a recoverable backup.'},
 type_mismatch:{meaning:'--type disagrees with the type the named source actually is.',fix:'Remove --type, or name a source of that type.'},
 session_disconnected:{meaning:'The remote session was removed; a replacement is never created silently.',fix:'Start a new session with afbin remote <command>.'},
 transport_error:{meaning:'The selected server could not be reached, so no request was answered.',fix:'Check the server URL (--server or ARTIFACTBIN_URL) and your network, then retry; afbin config set host <url> changes the default server.'},
 auth_required:{meaning:'This remote operation needs credentials for the selected origin.',fix:'Run afbin auth, or set ARTIFACTBIN_TOKEN and ARTIFACTBIN_URL for the selected server.'},
 browser_unavailable:{meaning:'The browser could not be opened; authentication stopped immediately.',fix:'Ask for the user email and run afbin auth --email <email>, then complete with --otp <code>.'},
 otp_required:{meaning:'An email login code was sent; authentication is not complete.',fix:'Ask for the emailed code and run afbin auth --email <email> --otp <code>, using the same --server as before.'},
 otp_send_failed:{meaning:'The server could not send the login email.',fix:'Check the email and server, then retry afbin auth --email <email>; wait before retrying if rate limited.'},
 otp_rejected:{meaning:'The email code was invalid, expired, or already used.',fix:'Check the email and code, or request a new one with afbin auth --email <email>, then complete with --otp <code>.'},
 approval_required:{meaning:'Browser approval is pending; --yes cannot approve it.',fix:'Use afbin auth --email <email> when a browser is unavailable, or open verification_url, approve, and rerun afbin auth before expires_at.'},
 access_denied:{meaning:'Browser approval was denied.',fix:'Run afbin auth only when you intend to start a new approval request.'},
 approval_expired:{meaning:'The browser approval window expired.',fix:'Run afbin auth --email <email> when a browser is unavailable, or afbin auth to start another browser approval.'},
 cli_update_required:{meaning:'The server requires a newer CLI protocol.',fix:'Run afbin update, then retry the command.'},
 state_conflict:{meaning:'Metadata or content changed since the observed head.',fix:'Inspect afbin diff --remote <ref>, reconcile the changes, then push. Use --force only when you intend a conditional replacement.'},
 version_conflict:{meaning:'The content version changed since the observed head.',fix:'Inspect afbin diff --remote <ref> and reconcile the current content before pushing again.'},
 edit_conflict:{meaning:'The body edit could not be rebased without a conflict.',fix:'Inspect the returned diff and current source; reconcile your proposal before pushing again.'},
 outcome_unknown:{meaning:'A write has no confirmed response; it may have committed.',fix:'Keep the pending request journal and rerun afbin push to recover the frozen request. Do not create another artifact to retry.'},
 pending_recovery:{meaning:'An interrupted operation must be recovered before starting a different write.',fix:'Rerun afbin push. For an uncertain conditional update, afbin pull --force archives the proposal and reads the current head; uncertain creates must be recovered first.'},
 result_deleted:{meaning:'The original create result was deleted; its operation key will never create a replacement.',fix:'Restore that artifact and pull it, or deliberately create a new local file to fork. Keep the recovery record.'},
 wrong_server:{meaning:'The artifact URL or workspace belongs to a different server, and that origin is not one the selected server publishes as another address of itself. The refusal names both origins: the one that was selected and the one the URL or the workspace carries.',fix:'Pass --server <the origin named in the refusal> to select that server, or run the command from a workspace tracked against it; keep work for another server in a separate directory. When one deployment answers at two hostnames, its operator publishes the second one and afbin then treats them as one server.'},
 account_mismatch:{meaning:'The authenticated account differs from the workspace account.',fix:'Sign in with the workspace account before retrying. Do not discard tracking or recovery records.'},
 duplicate_identity:{meaning:'Two local files claim the same published artifact.',fix:'Keep one tracked file. To READ another version without a second working copy: afbin pull <id>@<v> --output - , or afbin export <id>@<v> --format original --output <file>. To keep working on one: afbin fork <id>@<v>, which gives the copy its own identity.'},
 /*
  * THE DATASET REFUSALS, which had no entries at all until an agent met four of
  * them in one session and was handed a code with no meaning and no fix — a
  * CliError raised with an uncatalogued code carries `fix: undefined`.
  */
 invalid_policy:{meaning:'The dataset policy is not one this server accepts: an unsupported field, a role other than viewer, or a table or column the dataset does not have.',fix:'The detail names the field, table or column. Read the dataset\'s own tables with afbin pull <ref> --format yaml, correct the policy there and push the YAML; afbin push <ref> --policy viewers-write writes a grant for every table the dataset declares.'},
 not_found:{meaning:'The selected server does not have this artifact, or this account cannot reach it — existence is never revealed, so the two are one answer.',fix:'Check the reference with afbin list and the account with afbin auth. Someone else\'s artifact becomes yours to push only through afbin fork <ref>.'},
 policy_locked:{meaning:'The dataset carries a write policy. Replacing the content of a governed dataset is the OWNER\'s alone, and reverting one is refused for everyone, because viewers\' rows are in it.',fix:'Ask the owner to push the change, or take your own copy with afbin fork <ref>. As the owner, push the rows you want — read an older version with afbin pull <ref>@<v> --output - and push that content instead of reverting.'},
 policy_mismatch:{meaning:'The policy does not fit the dataset it is aimed at: a policy declared in the YAML disagrees with --policy, or a replacement no longer has a table or column the policy grants.',fix:'The detail names the table or column. Keep it in the pushed rows, or change the policy first: afbin pull <ref> --format yaml, edit policy there and push the YAML before replacing the content.'},
 combined_policy_write:{meaning:'One request cannot both replace content and change the policy, and a dataset that does not exist yet cannot be given one.',fix:'Push the content first, then afbin pull <ref> --format yaml and push that YAML with its policy. afbin push <ref> --policy viewers-write does both, in that order, in one command.'},
 policy_changed:{meaning:'The policy revision moved since the one this push observed, so the compare-and-swap wrote nothing.',fix:'Run afbin pull <ref> --format yaml for the current policy and its policy_revision, reapply your change there and push the YAML again.'},
 dataset_error:{meaning:'The dataset itself could not be published, refreshed or restored: rows or columns the tier rejects, an unreadable stored table, or a connection the server could not use.',fix:'The detail names the fault. Correct the rows, columns or connection in the source file and push again; afbin validate checks the local definition first and afbin help data shows the Dataset and Table forms.'},
 version_not_writable:{meaning:'Historical selectors are read-only.',fix:'Use @version with pull, diff or log. To restore old content, pull that version into the tracked file and push the file without a suffix.'},
 invalid_reference:{meaning:'The value is not an artifact reference.',fix:'Use <url|id|path>[@version] at the command line, ref:<id> in published markup, and $query for result bindings.'},
 /*
  * THE SANDBOX REFUSALS. A test user is a full user toward artifacts test users own and exactly a
  * guest toward everything else, so an agent verifying an app meets these holding nothing but this
  * CLI. `sandbox_only` names the one door into the sandbox, because the thing an agent otherwise
  * reaches for — pressing Join on the real page as a test user — is what can never work.
  */
 testuser_limit:{meaning:'This account already holds as many live test users as it may at once.',fix:'Erase one you are finished with: afbin testuser list shows them, then delete one with afbin testuser delete <id>, or afbin testuser delete --all. Mint the next with afbin testuser new.'},
 testuser_expired:{meaning:'The named test user is past its 24-hour life; the sweep erases an expired test user and everything it owned.',fix:'Mint another with afbin testuser new, give it the page again with afbin fork <id> --as <testuser>, and rerun the session against that copy.'},
 not_your_testuser:{meaning:'That test user belongs to another account or has already been erased; a test user is only ever its own account\'s.',fix:'Run afbin testuser list for the ids this account holds, and afbin testuser new if there is none.'},
 testuser_requires_account:{meaning:'Only a signed-in account mints test users: a guest or a test user has no account to own the sandbox.',fix:'Run afbin auth to sign in as yourself, then afbin testuser new.'},
 sandbox_only:{meaning:'A test user may act on artifacts test users own and on other test users, and is a guest everywhere else: on an account\'s artifact it reads what the link grants and nothing more — no $_me write, like, follow, comment or fork.',fix:'Give the test user its own copy to act on: afbin fork <id> --as <testuser>, then point the session at that copy. Nothing a test user does reaches the original.'},
 sign_in_required:{meaning:'The page ran a <Mutation> binding $_me and the reader is signed out, so there is no account to record in the row.',fix:'Sign in, or verify with a test user: afbin testuser new, then afbin fork <id> --as <testuser> and browse the copy with afbin sessions script new --as <testuser>.'},
 invalid_markup:{meaning:'Static JSX does not satisfy the local authoring grammar.',fix:'Run afbin help markup and correct the indicated source. afbin validate --fix applies mechanical formatting only.'},
 invalid_dataset:{meaning:'A local dataset is not supported tabular data.',fix:'Use CSV, a JSON array of row objects, or a .geojson FeatureCollection. Use afbin help data for Query and Mutation examples.'},
 unsupported_file_type:{meaning:'This local format cannot be published through native push.',fix:'Use a .jsx document, CSV/JSON/GeoJSON rows, or an allowed media/file format. See afbin help publishing-datasets.'},
};
export function diagnosticsHelp():string{return '# Errors and recovery\n\nLocal checks run before authentication. Every refusal returns a stable code, the field or location at fault and a recovery instruction; with --json it is one document with error.code, error.message and error.fix, exit status 2. Follow the returned instruction; the codes below say the same. A server refusal may add current source or a diff. A conflict never touches your file. For a refusal or interrupted write, preserve the returned code, fix and pending request record, then retry push: its frozen request recovers the original result.\n\n'+Object.entries(diagnosticCatalog).map(([code,entry])=>`## ${code}\n\n${entry.meaning}\n\n${entry.fix}\n`).join('\n');}
