import { describe, expect, it } from 'vitest';
import { STORY_SYSTEMS, STORY_SYSTEM_NAMES, getStorySystem } from '../story-systems';
import { STORY_SYSTEM_SHEETS, storySystemSheetCss } from '../story-system-sheets';
import { STORY_THEMES, STORY_THEME_NAMES, resolveStoredStoryDesign, resolveStoryMode, storyThemeCss } from '../story-themes';
import { STORY_DESIGN_NAMES, StoryContent } from '@/lib/validation/atlas-schemas';
import { storyBaseCss } from '@/lib/story/styles/story-base-css';
import { documentStyleSheets } from '@/lib/story/styles/document-styles';

/** The shadcn contract every theme fills (story-themes.test pins the same list for themes). */
const CONTRACT = ['background', 'foreground', 'card', 'card-foreground', 'popover', 'popover-foreground', 'primary', 'primary-foreground', 'secondary', 'secondary-foreground', 'muted', 'muted-foreground', 'accent', 'accent-foreground', 'destructive', 'destructive-foreground', 'border', 'input', 'ring', 'chart-1', 'chart-2', 'chart-3', 'chart-4', 'chart-5'];

describe('STORY_SYSTEMS registry (generated by scripts/design-systems.mjs)', () => {
  it('is the thirteen, in roster order, disjoint from the six themes, one entry per name', () => {
    expect(STORY_SYSTEM_NAMES.length).toBe(13);
    expect(STORY_SYSTEMS.map((s) => s.name)).toEqual([...STORY_SYSTEM_NAMES]);
    for (const name of STORY_SYSTEM_NAMES) expect(STORY_THEME_NAMES).not.toContain(name);
    expect(STORY_DESIGN_NAMES).toEqual([...STORY_THEME_NAMES, ...STORY_SYSTEM_NAMES]);
    // The registry reaches the browser through story-themes; the sheets (half a megabyte) stay in their own file.
    expect(JSON.stringify(STORY_SYSTEMS)).not.toContain('@font-face');
    expect(JSON.stringify(STORY_SYSTEMS)).not.toContain('.t-label');
    expect(Object.keys(STORY_SYSTEM_SHEETS)).toEqual([...STORY_SYSTEM_NAMES]);
  });

  it('every system fills the full contract in both modes, with radius and the three font stacks on the light side', () => {
    for (const s of STORY_SYSTEMS) {
      for (const key of CONTRACT) {
        expect(s.cssVars[`--${key}`], `${s.name} light --${key}`).toMatch(/^var\(--ds-[a-z0-9-]+\)$/);
        expect(s.darkCssVars[`--${key}`], `${s.name} dark --${key}`).toMatch(/^var\(--ds-[a-z0-9-]+\)$/);
      }
      for (const v of ['--radius', '--font-display', '--font-body', '--font-mono']) expect(s.cssVars[v], `${s.name} ${v}`).toBeTruthy();
      expect(['light', 'dark']).toContain(s.defaultMode);
      expect(s.label.length).toBeGreaterThan(0);
      expect(s.description.length).toBeGreaterThan(0);
    }
  });

  it('every face is a Google-hosted woff2 with a weight, and the classes are scoped to the root data-theme at one class of specificity', () => {
    for (const s of STORY_SYSTEMS) {
      const sheet = STORY_SYSTEM_SHEETS[s.name];
      const faces = sheet.fontFaces.match(/@font-face \{[^}]*\}/g) ?? [];
      expect(faces.length, `${s.name} faces`).toBeGreaterThan(0);
      for (const face of faces) {
        expect(face).toMatch(/src: url\(https:\/\/fonts\.gstatic\.com\/[^)]+\) format\("woff2"\)/);
        expect(face).toMatch(/font-weight: \d+/);
      }
      expect(sheet.css, `${s.name} css`).toContain(`:where(:root[data-theme="${s.name}"]) .t-`);
      expect(sheet.css, `${s.name} keeps no page scope`).not.toContain(`.ds-${s.name}`);
      expect(sheet.css, `${s.name} carries no page chrome`).not.toContain('.ds-section');
    }
  });

  it('getStorySystem and storySystemSheetCss answer systems only', () => {
    expect(getStorySystem('volta')?.label).toBe('Volta');
    expect(getStorySystem('modernist')).toBeUndefined();
    expect(getStorySystem(null)).toBeUndefined();
    expect(storySystemSheetCss('volta')).toBe(`${STORY_SYSTEM_SHEETS.volta.fontFaces}\n${STORY_SYSTEM_SHEETS.volta.css}`);
    expect(storySystemSheetCss('modernist')).toBe('');
    expect(storySystemSheetCss(undefined)).toBe('');
  });
});

describe('a system is a theme to the fence, the emitter and the resolution', () => {
  it('the fence schema enumerates every system beside the six themes', () => {
    const themeSchema = JSON.stringify(StoryContent.properties.theme);
    for (const name of STORY_DESIGN_NAMES) expect(themeSchema).toContain(`"${name}"`);
    expect(themeSchema).not.toContain('"bauhaus"');
  });

  it('a stored system name resolves to itself, with its declared default mode', () => {
    expect(resolveStoredStoryDesign('volta', null)).toEqual({ theme: 'volta', colorMode: null });
    expect(resolveStoredStoryDesign('phosphor', 'light')).toEqual({ theme: 'phosphor', colorMode: 'light' });
    expect(resolveStoryMode('phosphor', null)).toBe('dark');
    expect(resolveStoryMode('volta', null)).toBe('light');
    expect(resolveStoryMode('volta', 'dark')).toBe('dark');
  });

  it('the theme suffix carries every system\'s variables with the themes\' selectors, and keeps only the document\'s own when asked', () => {
    const all = storyThemeCss();
    for (const s of STORY_SYSTEMS) {
      expect(all).toContain(`:root:where([data-theme="${s.name}"]) {\n  --ds-`);
      expect(all).toContain(`:root:where([data-theme="${s.name}"].dark) {\n  --ds-`);
      // The shared root paint and heading rules name the system beside the themes.
      expect(all).toMatch(new RegExp(`:root:where\\(:is\\([^)]*\\[data-theme="${s.name}"\\]`));
    }
    const only = storyThemeCss('volta');
    expect(only).toContain(':root:where([data-theme="volta"]) {');
    expect(only).not.toContain('[data-theme="phosphor"]) {');
    for (const t of STORY_THEMES) expect(only).not.toContain(`:root:where([data-theme="${t.name}"]) {`);
    // No faces or classes in the suffix: those ride the base sheet, per document.
    expect(all).not.toContain('@font-face');
    expect(all).not.toContain('.t-label');
  });

  it('the base sheet and the standalone document carry the system\'s faces and classes, after the fonts and before the author', () => {
    const fonts = { slots: {}, families: [] };
    const bare = storyBaseCss({ chrome: true, theme: 'volta', fonts });
    expect(bare).not.toContain('.t-label');
    const dressed = storyBaseCss({ chrome: true, theme: 'volta', fonts, systemCss: storySystemSheetCss('volta') });
    expect(dressed).toContain('@font-face { font-family: "Bricolage Grotesque"');
    expect(dressed).toContain(':where(:root[data-theme="volta"]) .t-label {');
    const sheets = documentStyleSheets({ compiledCss: null, chrome: true, bare: false, theme: 'volta', docFonts: fonts, systemCss: storySystemSheetCss('volta'), authorCss: ':root { --ds-volt: red }' });
    const attrs = sheets.map((s) => s.attr);
    expect(attrs.indexOf('data-mx-system')).toBeGreaterThan(attrs.indexOf('data-mx-fonts'));
    expect(attrs.indexOf('data-mx-system')).toBeLessThan(attrs.indexOf('data-mx-author'));
    expect(documentStyleSheets({ compiledCss: null, chrome: true, bare: false, theme: 'modernist', docFonts: fonts, systemCss: storySystemSheetCss('modernist'), authorCss: null }).map((s) => s.attr)).not.toContain('data-mx-system');
  });
});
