import { build } from 'esbuild';
import { mkdtemp, readFile, writeFile, chmod } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
const root = await mkdtemp(join(tmpdir(), 'afbin-npm-probe-'));
await build({ entryPoints: [resolve('services/cli/src/main.ts')], outfile: join(root,'afbin.mjs'), bundle:true, platform:'node', format:'esm', target:'node22', external:['node-pty'], banner:{js:'#!/usr/bin/env node'}, plugins:[{name:'lazy-remote-probe',setup(b){b.onLoad({filter:/src\/main\.ts$/},async args=>({loader:'ts',contents:(await readFile(args.path,'utf8')).replace('import { runRemote } from "./runner";','').replace('await runRemote(','await (await import("./runner")).runRemote(')}));}}] });
await chmod(join(root,'afbin.mjs'),0o755);
await writeFile(join(root,'package.json'),JSON.stringify({name:'afbin-planning-probe',version:'0.0.0',type:'module',bin:{afbin:'afbin.mjs'},files:['afbin.mjs'],optionalDependencies:{'node-pty':'1.1.0'}}));
const p=spawnSync('npm',['pack','--json'],{cwd:root,encoding:'utf8'});if(p.status!==0)throw Error(p.stderr);
console.log(join(root,JSON.parse(p.stdout)[0].filename));
