/** The artifacts module's interface: only what other modules import. */
export { canReadArtifact, editorScope, effectiveRole, linkRoleOf } from './access';
export type { ArtifactRow, RoleActor, Scope, TokenActor, Viewer, Visibility } from './access';
export { restoreBrowserArtifact, writeBrowserArtifact } from './browser-artifact-write';
export { can, capabilityGuard, capabilityRefusal } from './capabilities';
export type { CapabilityActor } from './capabilities';
export { CreationReplay } from './creation-ledger';
export { compiledForRow, dataflowForRow, datasetResolverForActor, datasetsForDocument, declarationsForRow, findDependentsFor, holdImport, holdableImports, nameablePeople, refDataForRow, refLoaderForActor, runDocumentDataflow, runDocumentMutation, viewerIdentityFor } from './dataflow';
export { setDocumentEditorPolicy } from './document-policy';
export type { DocumentEditorPolicy } from './document-policy';
export { artifactQuery } from './document';
export { forkArtifact, forkDatasetPreview, forkRefusal } from './fork';
export { claimArtifactId, reserveIds } from './identities';
export { resolveImageReference } from './image-references';
export { updateMetadataFromBody } from './metadata-wire';
export { setMutationInvocation } from './mutation-invocation';
export type { MutationInvocation, MutationInvocationFactory } from './mutation-invocation';
export { adaptMutationOperationReply, completeDocumentMutationReceipt, documentMutationReply, mutationInitiator, normalizeMutationOperation } from './mutation-operation';
export { durableMutation, pinMutationContext } from './mutation-receipt';
export type { MutationReceipt } from './mutation-receipt';
export { preflightPublication } from './publication-preflight';
export { readableArtifact } from './read-access';
export { ANONYMOUS_CEILING, ROLE_ORDER, SHARE_ROLES, SHARE_ROLE_LABEL, atLeast, canAnnotate, canEdit, canGovern, canRead, capRole, maxRole, rankOf, roleBehindLogin, shareRolesAtLeast } from './share-roles';
export type { ArtifactRole, ShareRole } from './share-roles';
export { getSharingFor, setAccessFor, updateSharing, updateSharingFor } from './sharing';
export type { SharingPatch } from './sharing';
export { runSqliteSyntaxMigrationBatch } from './sqlite-syntax-migration';
export type { SqliteSyntaxMigrationOutcome } from './sqlite-syntax-migration';
export { artifactState } from './state';
export { MAX_STALE_EDITS, applyEditFor, applyEditScoped, artifactQuotaExceeded, commitNormalizedMarkup, committedHeadsSettled, createArtifact, getArtifactById, getArtifactFor, getEditableArtifactFor, getVersionFor, listArtifactsFor, listVersionsFor, publishMarkupForArtifact, replaceArtifactFor, revertArtifactFor, setArtifactQuotaForTests, setMetadataFor, versionToWire } from './store';
export type { ArtifactSummary, EditOutcome } from './store';
export { recordArtifactView } from './view-admission';
export { artifactSummaryToWire, artifactToWireWithAnnotations, createArtifactFromBody, parseAccessValue, parseLinkRoleValue, parseShareEntries, parseVisibilityValue, refreshAssetsFor, replaceArtifactFromRequest, respondToAnnotationAction, respondToEdit } from './wire';
