/** The artifacts module's interface: only what other modules import. */
export { canReadArtifact, editorScope, effectiveRole, isOwner, linkRoleOf, roleFor } from './access';
export type { ArtifactRow, Scope } from './access';
export { can, capabilityGuard, capabilityRefusal } from './capabilities';
export type { CapabilityActor } from './capabilities';
export { CreationReplay } from './creation-ledger';
export { compiledForRow, dataflowForRow, datasetResolverForActor, datasetsForDocument, declarationsForRow, findDependentsFor, holdImport, holdableImports, nameablePeople, refDataForRow, refLoaderForActor, runDocumentDataflow, runDocumentMutation, viewerIdentityFor } from './dataflow';
export { setDocumentEditorPolicy } from './document-policy';
export type { DocumentEditorPolicy } from './document-policy';
export { artifactQuery } from './document';
export { claimArtifactId, reserveIds } from './identities';
export { accountProfile, updateAccountProfile } from './membership/account-profile';
export { membershipInbox, updateMembershipInbox } from './membership/membership-inbox';
export { MembershipError, changeMembership, invitePeople, membershipState, mentionCandidates } from './membership/membership';
export { resolveImageReference } from './image-references';
export { updateMetadataFromBody } from './metadata-wire';
export { setMutationInvocation } from './mutation-invocation';
export type { MutationInvocation, MutationInvocationFactory } from './mutation-invocation';
export { adaptMutationOperationReply, completeDocumentMutationReceipt, documentMutationReply, mutationInitiator, normalizeMutationOperation } from './mutation-operation';
export { durableMutation, pinMutationContext } from './mutation-receipt';
export type { MutationReceipt } from './mutation-receipt';
export { notificationArtifactAuthority, notificationAuthority, notificationExecutionFence, notificationExecutionSource, notificationSourceSchema, notificationSourcesReadable } from './notification-authority';
export { evaluateNotificationQuery, normalizeNotificationResult } from './notification-query';
export type { NotificationQueryDependencies } from './notification-query';
export { notificationJobStore } from './notification-runtime';
export { readableArtifact } from './read-access';
export { getSharingFor, setAccessFor, updateSharing, updateSharingFor } from './sharing';
export { artifactState } from './state';
export { MAX_STALE_EDITS, applyEditFor, applyEditScoped, artifactQuotaExceeded, commitNormalizedMarkup, committedHeadsSettled, createArtifact, getArtifactById, getArtifactFor, getEditableArtifactFor, getVersionFor, listArtifactsFor, listVersionsFor, replaceArtifactFor, revertArtifactFor, setArtifactQuotaForTests, setMetadataFor, versionToWire } from './store';
export type { ArtifactSummary } from './store';
export { recordArtifactView } from './view-admission';
export { artifactSummaryToWire, parseAccessValue, parseLinkRoleValue, parseShareEntries, parseVisibilityValue, respondToEdit } from './wire';

export { parseArtifactDestination, newArtifactDestination } from './ownership';
export { transferArtifact } from './transfer';
