import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
vi.mock('@/components/ArtifactEditor',()=>({default:(p:{onExit:()=>void})=><button aria-label="Exit edit mode" onClick={p.onExit}>done</button>}));
import ArtifactShell from '../ArtifactShell';
import ArtifactSurface,{type ArtifactSurfaceProps} from '../ArtifactSurface';
import {RIGHT_RAIL_W} from '@/lib/story/edit-bar';
const props:ArtifactSurfaceProps={id:'story1',editId:'e1',format:'markup',title:'doc',source:'<p>Hello</p>',content:'',template:null,refs:[],version:1,columns:[],compiledCss:null,theme:null,colorMode:'light',liveEnabled:false};
afterEach(()=>vi.unstubAllGlobals());
it('reserves document space for the desktop comment rail and restores it on close',async()=>{
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({annotations:[]})));
 vi.stubGlobal('innerWidth',1200);
 render(<ArtifactShell role="owner"><ArtifactSurface {...props}/></ArtifactShell>);
 await screen.findByText('Hello');
 fireEvent.click(screen.getByLabelText('Toggle comments'));
 expect(screen.getByLabelText('Artifact viewport')).toHaveStyle({paddingRight:`${RIGHT_RAIL_W}px`});
 fireEvent.click(await screen.findByLabelText('Close comments'));
 expect(screen.getByLabelText('Artifact viewport')).toHaveStyle({paddingRight:'0px'});
});
it('keeps the phone comment sheet overlaid without remounting or resetting document state',async()=>{
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({annotations:[]})));
 vi.stubGlobal('innerWidth',390);
 const mobileProps:ArtifactSurfaceProps={...props,source:'<input aria-label="Local value" type="range" min={0} max={10} value="$amount" />',dataflow:{flow:{values:[{kind:'scalar',name:'amount',type:'number',default:2,start:0,end:0}],queries:[]}}};
 render(<ArtifactShell role="owner"><ArtifactSurface {...mobileProps}/></ArtifactShell>);
 const input=await screen.findByLabelText('Local value') as HTMLInputElement;
 fireEvent.change(input,{target:{value:'7'}});
 expect(input).toHaveValue('7');
 const viewport=screen.getByLabelText('Artifact viewport');
 fireEvent.click(screen.getByLabelText('Toggle comments'));
 expect(viewport).toHaveStyle({paddingRight:'0px'});
 fireEvent.click(await screen.findByLabelText('Close comments'));
 fireEvent.click(screen.getByLabelText('Toggle comments'));
 expect(screen.getByLabelText('Local value')).toBe(input);
 expect(input).toHaveValue('7');
 expect(viewport).toHaveStyle({paddingRight:'0px'});
});
it('edits the mounted document in place and retains the same host on exit',async()=>{
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({})));
 render(<ArtifactShell role="owner"><ArtifactSurface {...props}/></ArtifactShell>);
 await waitFor(()=>expect(screen.getByText('Hello')).toBeVisible());
 const host=document.querySelector('[data-artifact-story-host]');
 fireEvent.click(screen.getByLabelText('Open artifact controls')); fireEvent.click(screen.getByLabelText('Edit artifact'));
 fireEvent.click(await screen.findByLabelText('Exit edit mode'));
 expect(document.querySelector('[data-artifact-story-host]')).toBe(host);
 expect(screen.getByText('Hello')).toBeVisible();
});
it('preserves the reading position when a toolbar changes the document inset',async()=>{
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({})));
 vi.stubGlobal('scrollY',900);
 const scroll=vi.fn((x:number|ScrollToOptions,y?:number)=>{vi.stubGlobal('scrollY',typeof x==='object'?x.top??window.scrollY:y??window.scrollY);});
 vi.stubGlobal('scrollTo',scroll);
 vi.stubGlobal('scrollBy',vi.fn((x:number|ScrollToOptions,y?:number)=>{vi.stubGlobal('scrollY',window.scrollY+(typeof x==='object'?x.top??0:y??0));}));
 render(<ArtifactShell role="owner"><ArtifactSurface {...props}/></ArtifactShell>);
 await screen.findByText('Hello');
 fireEvent.click(screen.getByLabelText('Open artifact controls'));fireEvent.click(screen.getByLabelText('Edit artifact'));
 await screen.findByLabelText('Exit edit mode');
 expect(window.scrollY).toBe(948);
 fireEvent.click(screen.getByLabelText('Exit edit mode'));
 expect(window.scrollY).toBe(900);
});
it('keeps the document origin fixed while adding edit clearance at the top',async()=>{
 vi.stubGlobal('fetch',vi.fn(async()=>Response.json({})));
 vi.stubGlobal('scrollY',0);
 const scrollBy=vi.fn();vi.stubGlobal('scrollBy',scrollBy);
 render(<ArtifactShell role="owner"><ArtifactSurface {...props}/></ArtifactShell>);
 await screen.findByText('Hello');
 fireEvent.click(screen.getByLabelText('Open artifact controls'));fireEvent.click(screen.getByLabelText('Edit artifact'));
 expect(screen.getByLabelText('Artifact viewport')).toHaveStyle({paddingTop:'92px'});
 expect(window.scrollY).toBe(0);expect(scrollBy).not.toHaveBeenCalled();
});
