-- grants.sql — the cross-schema READS, and nothing else: the proxy reads the
-- app's tokens table (an indexed SELECT through utils createTokenReader) and
-- the app reads the event log the events service owns and alone writes.
-- Generated by scripts/render-schema.mjs (npm run render:schema); never edit
-- by hand.
--
-- Applied AFTER the boot that creates each table: neither exists on a fresh
-- database until its owner's additive DDL creates it, and applying this any
-- earlier aborts init (compose runs each leg as a one-shot between its
-- owner's :healthy and the reader's :up).

GRANT SELECT ON app.tokens TO artifactbin_proxy;
GRANT SELECT ON events.events TO artifactbin_app;
