-- grants.sql — the ONE cross-schema grant: the proxy reads the app's tokens
-- table (an indexed SELECT through utils createTokenReader) and nothing
-- else. Generated by scripts/render-schema.mjs (npm run render:schema);
-- never edit by hand.
--
-- Applied AFTER the app's first boot: the tokens table does not exist on a
-- fresh database until the app's additive DDL creates it, and applying this
-- any earlier aborts init (compose runs it as a one-shot between
-- app:healthy and proxy:up).

GRANT SELECT ON app.tokens TO artifactbin_proxy;
