-- roles.sql — the two LOGIN roles and the two schemas they OWN, for a FRESH
-- database. Generated by scripts/render-schema.mjs (npm run render:schema);
-- never edit by hand. Passwords are the operator's business — nothing in
-- code names a role.
--
-- Ownership (AUTHORIZATION) carries every privilege inside a schema, so
-- nothing further is granted here, for existing objects or future ones:
-- widening anything would let the proxy read app.artifacts. Its single
-- cross-schema read (its SELECT on the tokens table) lives in grants.sql,
-- applied after the app's first boot creates it.

CREATE ROLE artifactbin_app   LOGIN;
CREATE ROLE artifactbin_proxy LOGIN;

CREATE SCHEMA app AUTHORIZATION artifactbin_app;
CREATE SCHEMA auth AUTHORIZATION artifactbin_proxy;

-- The proxy must reach the app schema at all to read its tokens table.
GRANT USAGE ON SCHEMA app TO artifactbin_proxy;
