-- roles.sql — one LOGIN role per package and the schema each one OWNS, for a FRESH
-- database. Generated by scripts/render-schema.mjs (npm run render:schema);
-- never edit by hand. Passwords are the operator's business — nothing in
-- code names a role.
--
-- Ownership (AUTHORIZATION) carries every privilege inside a schema, so
-- nothing further is granted here, for existing objects or future ones:
-- widening anything would let the proxy read app.artifacts. The
-- cross-schema READS (the proxy on the tokens table, the app on the event
-- log) live in grants.sql, applied after the boot that creates each table.

CREATE ROLE artifactbin_app    LOGIN;
CREATE ROLE artifactbin_proxy  LOGIN;
CREATE ROLE artifactbin_events LOGIN;

CREATE SCHEMA app AUTHORIZATION artifactbin_app;
CREATE SCHEMA auth AUTHORIZATION artifactbin_proxy;
-- The events service is the log's ONLY writer; every other process reads it.
CREATE SCHEMA events AUTHORIZATION artifactbin_events;

-- The proxy must reach the app schema at all to read its tokens table.
GRANT USAGE ON SCHEMA app TO artifactbin_proxy;
-- …and the app must reach the events schema at all to read the log.
GRANT USAGE ON SCHEMA events TO artifactbin_app;
