-- SCHEMA.sql — ONE rendered schema, generated by scripts/render-schema.mjs
-- (npm run render:schema). Never edit by hand: each package declares its own
-- tables and this file is both sides rendered together, so it cannot drift
-- from either declaration.
--
-- A FRESH-database / CI artifact, NOT something boot applies: Better
-- Auth's DDL has no IF NOT EXISTS, so
-- this file is for a clean database only. Boot still uses the additive
-- ensureTable (CREATE TABLE IF NOT EXISTS + ADD COLUMN IF NOT EXISTS) — the
-- two cannot disagree because both render the same declarations.
--
-- Apply order on a fresh database: roles.sql (the schemas, with their
-- owners) → SCHEMA.sql → grants.sql.

-- Better Auth tables — generated by getMigrations(...).compileMigrations().
-- No IF NOT EXISTS: this block is for a fresh database only.
create table "auth"."user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "auth"."session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "auth"."user" ("id") on delete cascade);

create table "auth"."account" ("id" text not null primary key, "issuer" text not null, "accountId" text not null, "providerId" text not null, "userId" text not null references "auth"."user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "auth"."verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "session_userId_idx" on "auth"."session" ("userId");

create index "account_userId_idx" on "auth"."account" ("userId");

create index "verification_identifier_idx" on "auth"."verification" ("identifier");

create unique index "account_issuer_accountId_uidx" on "auth"."account" ("issuer", "accountId");

-- schema "app" — owned by the app role; tables declared by lib/schema.ts

CREATE TABLE IF NOT EXISTS app.users (
  id TEXT NOT NULL,
  email TEXT NOT NULL,
  name TEXT,
  username TEXT,
  password_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS email TEXT NOT NULL;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS username TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS password_hash TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.users ALTER COLUMN password_hash DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON app.users (email);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON app.users (username);

CREATE TABLE IF NOT EXISTS app.tokens (
  id TEXT NOT NULL,
  name TEXT,
  token_hash TEXT NOT NULL,
  user_id TEXT,
  client_harness TEXT,
  audience TEXT,
  scope TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS token_hash TEXT NOT NULL;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS client_harness TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS audience TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS scope TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS idx_tokens_hash ON app.tokens (token_hash);

CREATE TABLE IF NOT EXISTS app.artifacts (
  id TEXT NOT NULL,
  token_id TEXT NOT NULL,
  user_id TEXT,
  visibility TEXT NOT NULL DEFAULT 'public',
  link_role TEXT,
  access TEXT NOT NULL DEFAULT 'read',
  folder TEXT NOT NULL DEFAULT '',
  title TEXT,
  description TEXT,
  format TEXT NOT NULL DEFAULT 'markup',
  content TEXT NOT NULL,
  source TEXT,
  meta JSONB NOT NULL DEFAULT '{}',
  version INTEGER NOT NULL DEFAULT 1,
  edit_id TEXT NOT NULL DEFAULT md5(random()::text),
  actor_user_id TEXT,
  actor_token_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  forked_from TEXT,
  PRIMARY KEY (id)
);

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS token_id TEXT NOT NULL;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'public';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS link_role TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS access TEXT NOT NULL DEFAULT 'read';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS folder TEXT NOT NULL DEFAULT '';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS title TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS format TEXT NOT NULL DEFAULT 'markup';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS content TEXT NOT NULL;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS source TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS meta JSONB NOT NULL DEFAULT '{}';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS edit_id TEXT NOT NULL DEFAULT md5(random()::text);

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS actor_user_id TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS actor_token_id TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS forked_from TEXT;

CREATE INDEX IF NOT EXISTS idx_artifacts_token_updated ON app.artifacts (token_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS app.artifact_versions (
  artifact_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  title TEXT,
  description TEXT,
  format TEXT NOT NULL DEFAULT 'markup',
  content TEXT NOT NULL,
  source TEXT,
  meta JSONB NOT NULL DEFAULT '{}',
  actor_user_id TEXT,
  actor_token_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (artifact_id, version)
);

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS title TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS format TEXT NOT NULL DEFAULT 'markup';

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS content TEXT NOT NULL;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS source TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS meta JSONB NOT NULL DEFAULT '{}';

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS actor_user_id TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS actor_token_id TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.artifact_edits (
  seq BIGSERIAL NOT NULL,
  artifact_id TEXT NOT NULL,
  edit_id TEXT NOT NULL,
  splice_start INTEGER NOT NULL,
  removed TEXT NOT NULL,
  inserted TEXT NOT NULL,
  span_start INTEGER NOT NULL,
  span_end INTEGER NOT NULL,
  actor_user_id TEXT,
  actor_token_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (seq),
  UNIQUE (edit_id)
);

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS seq BIGSERIAL NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS edit_id TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS splice_start INTEGER NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS removed TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS inserted TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS span_start INTEGER NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS span_end INTEGER NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS actor_user_id TEXT;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS actor_token_id TEXT;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_artifact_edits_artifact_seq ON app.artifact_edits (artifact_id, seq);

CREATE TABLE IF NOT EXISTS app.artifact_shares (
  artifact_id TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer',
  user_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (artifact_id, email)
);

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS email TEXT NOT NULL;

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'viewer';

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.annotations (
  id TEXT NOT NULL,
  seq BIGSERIAL NOT NULL,
  artifact_id TEXT NOT NULL,
  root_id TEXT,
  body TEXT NOT NULL,
  author_kind TEXT NOT NULL,
  author_token_id TEXT,
  author_user_id TEXT,
  author_label TEXT,
  author_transport TEXT NOT NULL DEFAULT 'unknown',
  status TEXT NOT NULL DEFAULT 'open',
  resolved_at TIMESTAMPTZ,
  anchor_key TEXT,
  anchor_version INTEGER,
  snippet TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  quote TEXT,
  range TEXT,
  PRIMARY KEY (id)
);

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS seq BIGSERIAL NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS root_id TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS body TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_kind TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_token_id TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_user_id TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_label TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_transport TEXT NOT NULL DEFAULT 'unknown';

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'open';

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS anchor_key TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS anchor_version INTEGER;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS snippet TEXT NOT NULL DEFAULT '';

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS quote TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS range TEXT;

CREATE INDEX IF NOT EXISTS idx_annotations_artifact_seq ON app.annotations (artifact_id, seq);

CREATE TABLE IF NOT EXISTS app.codes (
  kind TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  subject TEXT,
  payload JSONB NOT NULL DEFAULT '{}',
  attempts INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (kind, code_hash)
);

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS code_hash TEXT NOT NULL;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS subject TEXT;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}';

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_codes_kind_subject ON app.codes (kind, subject);

CREATE INDEX IF NOT EXISTS idx_codes_expires ON app.codes (expires_at);

CREATE TABLE IF NOT EXISTS app.analytics_events (
  seq BIGSERIAL NOT NULL,
  event TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  user_id TEXT,
  client TEXT,
  visitor TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (seq)
);

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS seq BIGSERIAL NOT NULL;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS event TEXT NOT NULL;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS client TEXT;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS visitor TEXT;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_analytics_events_artifact_created ON app.analytics_events (artifact_id, created_at);

CREATE INDEX IF NOT EXISTS idx_analytics_events_event ON app.analytics_events (event);

CREATE TABLE IF NOT EXISTS app.webfonts (
  family TEXT NOT NULL,
  assets JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (family)
);

ALTER TABLE app.webfonts ADD COLUMN IF NOT EXISTS family TEXT NOT NULL;

ALTER TABLE app.webfonts ADD COLUMN IF NOT EXISTS assets JSONB NOT NULL DEFAULT '[]';

ALTER TABLE app.webfonts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- schema "auth" — owned by the proxy role; tables declared by the proxy's schema module

CREATE TABLE IF NOT EXISTS auth.clients (
  id TEXT NOT NULL,
  kind TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL;

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}';

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS auth.credentials (
  kind TEXT NOT NULL,
  credential_hash TEXT NOT NULL,
  subject_id TEXT,
  group_id TEXT,
  payload JSONB NOT NULL DEFAULT '{}',
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (kind, credential_hash)
);

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS credential_hash TEXT NOT NULL;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS subject_id TEXT;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS group_id TEXT;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}';

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS consumed_at TIMESTAMPTZ;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_auth_credentials_group ON auth.credentials (group_id) WHERE group_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_auth_credentials_expiry ON auth.credentials (expires_at);

