-- SCHEMA.sql — ONE rendered schema, generated by scripts/render-schema.mjs
-- (npm run render:schema). Never edit by hand: each package declares its own
-- tables and this file is both sides rendered together, so it cannot drift
-- from either declaration.
--
-- A FRESH-database / CI artifact, NOT something boot applies: Better
-- Auth's DDL has no IF NOT EXISTS, so
-- this file is for a clean database only. Boot still uses the additive
-- ensureTable (CREATE TABLE IF NOT EXISTS + ADD COLUMN IF NOT EXISTS) — the
-- two cannot disagree because both render the same declarations.
--
-- Apply order on a fresh database: roles.sql (the schemas, with their
-- owners) → SCHEMA.sql → grants.sql.

-- Better Auth tables — generated by getMigrations(...).compileMigrations().
-- No IF NOT EXISTS: this block is for a fresh database only.
create table "auth"."user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "auth"."session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "auth"."user" ("id") on delete cascade);

create table "auth"."account" ("id" text not null primary key, "issuer" text not null, "accountId" text not null, "providerId" text not null, "userId" text not null references "auth"."user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "auth"."verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "session_userId_idx" on "auth"."session" ("userId");

create index "account_userId_idx" on "auth"."account" ("userId");

create index "verification_identifier_idx" on "auth"."verification" ("identifier");

create unique index "account_issuer_accountId_uidx" on "auth"."account" ("issuer", "accountId");

-- schema "app" — owned by the app role; tables declared by lib/schema.ts

CREATE TABLE IF NOT EXISTS app.event_outbox (
  id TEXT NOT NULL,
  envelope JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

ALTER TABLE app.event_outbox ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.event_outbox ADD COLUMN IF NOT EXISTS envelope JSONB NOT NULL;

ALTER TABLE app.event_outbox ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.artifact_members (
  artifact_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  status TEXT NOT NULL,
  direction TEXT NOT NULL,
  initiated_by TEXT NOT NULL,
  joined_at TIMESTAMPTZ,
  revision INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (artifact_id, user_id)
);

ALTER TABLE app.artifact_members ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_members ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL;

ALTER TABLE app.artifact_members ADD COLUMN IF NOT EXISTS status TEXT NOT NULL;

ALTER TABLE app.artifact_members ADD COLUMN IF NOT EXISTS direction TEXT NOT NULL;

ALTER TABLE app.artifact_members ADD COLUMN IF NOT EXISTS initiated_by TEXT NOT NULL;

ALTER TABLE app.artifact_members ADD COLUMN IF NOT EXISTS joined_at TIMESTAMPTZ;

ALTER TABLE app.artifact_members ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_members_pending_initiator ON app.artifact_members (initiated_by) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS app.member_notifications (
  id TEXT NOT NULL,
  artifact_id TEXT,
  user_id TEXT NOT NULL,
  recipient_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  source TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at TIMESTAMPTZ,
  revision INTEGER NOT NULL DEFAULT 1,
  seen_revision INTEGER NOT NULL DEFAULT 0,
  first_update_id TEXT,
  PRIMARY KEY (id)
);

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS artifact_id TEXT;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS recipient_id TEXT NOT NULL;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS sender_id TEXT NOT NULL;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS source TEXT;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS seen_revision INTEGER NOT NULL DEFAULT 0;

ALTER TABLE app.member_notifications ADD COLUMN IF NOT EXISTS first_update_id TEXT;

CREATE INDEX IF NOT EXISTS idx_member_notifications_recipient ON app.member_notifications (recipient_id, created_at);

CREATE TABLE IF NOT EXISTS app.user_blocks (
  user_id TEXT NOT NULL,
  blocked_user_id TEXT NOT NULL,
  PRIMARY KEY (user_id, blocked_user_id)
);

ALTER TABLE app.user_blocks ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL;

ALTER TABLE app.user_blocks ADD COLUMN IF NOT EXISTS blocked_user_id TEXT NOT NULL;

CREATE TABLE IF NOT EXISTS app.comment_images (
  id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  annotation_id TEXT,
  token_id TEXT NOT NULL,
  user_id TEXT,
  metadata JSONB NOT NULL,
  bytes BIGINT NOT NULL,
  ready BOOLEAN NOT NULL DEFAULT false,
  expires_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS annotation_id TEXT;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS token_id TEXT NOT NULL;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS bytes BIGINT NOT NULL;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS ready BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE app.comment_images ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL;

CREATE INDEX IF NOT EXISTS idx_comment_images_annotation ON app.comment_images (annotation_id);

CREATE INDEX IF NOT EXISTS idx_comment_images_expiry ON app.comment_images (expires_at);

CREATE TABLE IF NOT EXISTS app.remote_agents (
  id TEXT NOT NULL,
  owner TEXT NOT NULL,
  name TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  proof_hash TEXT NOT NULL,
  info JSONB NOT NULL,
  seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

ALTER TABLE app.remote_agents ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.remote_agents ADD COLUMN IF NOT EXISTS owner TEXT NOT NULL;

ALTER TABLE app.remote_agents ADD COLUMN IF NOT EXISTS name TEXT NOT NULL;

ALTER TABLE app.remote_agents ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE app.remote_agents ADD COLUMN IF NOT EXISTS proof_hash TEXT NOT NULL;

ALTER TABLE app.remote_agents ADD COLUMN IF NOT EXISTS info JSONB NOT NULL;

ALTER TABLE app.remote_agents ADD COLUMN IF NOT EXISTS seen_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_remote_agent_name ON app.remote_agents (owner, name) WHERE active;

CREATE TABLE IF NOT EXISTS app.remote_work (
  id TEXT NOT NULL,
  seq BIGSERIAL NOT NULL,
  owner TEXT NOT NULL,
  session_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  thread_id TEXT NOT NULL,
  comment_id TEXT NOT NULL,
  phase TEXT NOT NULL,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS seq BIGSERIAL NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS owner TEXT NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS session_id TEXT NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS thread_id TEXT NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS comment_id TEXT NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS phase TEXT NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS data JSONB NOT NULL;

ALTER TABLE app.remote_work ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_remote_work_comment ON app.remote_work (session_id, comment_id);

CREATE INDEX IF NOT EXISTS idx_remote_work_thread ON app.remote_work (artifact_id, thread_id);

CREATE TABLE IF NOT EXISTS app.export_images (
  id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  object_key TEXT NOT NULL,
  mime TEXT NOT NULL,
  bytes INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS object_key TEXT NOT NULL;

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS mime TEXT NOT NULL;

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS bytes INTEGER NOT NULL;

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS width INTEGER NOT NULL;

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS height INTEGER NOT NULL;

ALTER TABLE app.export_images ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_export_images_artifact ON app.export_images (artifact_id);

CREATE TABLE IF NOT EXISTS app.export_image_cache (
  cache_key TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  image_id TEXT,
  source_revision TEXT,
  expires_at TIMESTAMPTZ,
  claim_token TEXT,
  lease_until TIMESTAMPTZ,
  retry_after TIMESTAMPTZ,
  PRIMARY KEY (cache_key)
);

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS cache_key TEXT NOT NULL;

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS image_id TEXT;

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS source_revision TEXT;

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS claim_token TEXT;

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ;

ALTER TABLE app.export_image_cache ADD COLUMN IF NOT EXISTS retry_after TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS app.mutation_receipts (
  scope TEXT NOT NULL,
  operation_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  response JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (scope, operation_key)
);

ALTER TABLE app.mutation_receipts ADD COLUMN IF NOT EXISTS scope TEXT NOT NULL;

ALTER TABLE app.mutation_receipts ADD COLUMN IF NOT EXISTS operation_key TEXT NOT NULL;

ALTER TABLE app.mutation_receipts ADD COLUMN IF NOT EXISTS request_hash TEXT NOT NULL;

ALTER TABLE app.mutation_receipts ADD COLUMN IF NOT EXISTS response JSONB;

ALTER TABLE app.mutation_receipts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.dataset_policy_audit (
  dataset_id TEXT NOT NULL,
  revision INTEGER NOT NULL,
  policy JSONB,
  actor_user_id TEXT,
  actor_token_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (dataset_id, revision)
);

ALTER TABLE app.dataset_policy_audit ADD COLUMN IF NOT EXISTS dataset_id TEXT NOT NULL;

ALTER TABLE app.dataset_policy_audit ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL;

ALTER TABLE app.dataset_policy_audit ADD COLUMN IF NOT EXISTS policy JSONB;

ALTER TABLE app.dataset_policy_audit ADD COLUMN IF NOT EXISTS actor_user_id TEXT;

ALTER TABLE app.dataset_policy_audit ADD COLUMN IF NOT EXISTS actor_token_id TEXT;

ALTER TABLE app.dataset_policy_audit ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.dataset_usage (
  bucket TEXT NOT NULL,
  calls INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (bucket)
);

ALTER TABLE app.dataset_usage ADD COLUMN IF NOT EXISTS bucket TEXT NOT NULL;

ALTER TABLE app.dataset_usage ADD COLUMN IF NOT EXISTS calls INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS app.users (
  id TEXT NOT NULL,
  email TEXT,
  kind TEXT NOT NULL DEFAULT 'account',
  parent_user_id TEXT,
  expires_at TIMESTAMPTZ,
  is_guest BOOLEAN DEFAULT false,
  merged_into_user_id TEXT,
  name TEXT,
  username TEXT,
  image_key TEXT,
  auto_accept_mentions BOOLEAN NOT NULL DEFAULT true,
  welcome_pending BOOLEAN NOT NULL DEFAULT false,
  password_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS email TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'account';

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS parent_user_id TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS is_guest BOOLEAN DEFAULT false;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS merged_into_user_id TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS username TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS image_key TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS auto_accept_mentions BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS welcome_pending BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS password_hash TEXT;

ALTER TABLE app.users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.users ALTER COLUMN email DROP NOT NULL;

ALTER TABLE app.users ALTER COLUMN is_guest DROP NOT NULL;

ALTER TABLE app.users ALTER COLUMN password_hash DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON app.users (email);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON app.users (username);

CREATE INDEX IF NOT EXISTS idx_users_parent ON app.users (parent_user_id);

CREATE TABLE IF NOT EXISTS app.tokens (
  id TEXT NOT NULL,
  name TEXT,
  token_hash TEXT NOT NULL,
  user_id TEXT,
  client_harness TEXT,
  audience TEXT,
  scope TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS token_hash TEXT NOT NULL;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS client_harness TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS audience TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS scope TEXT;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

ALTER TABLE app.tokens ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMPTZ;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'app' AND table_name = 'tokens' AND column_name = 'revoked_at'
  ) THEN
    UPDATE app.tokens SET deleted_at = revoked_at WHERE deleted_at IS NULL AND revoked_at IS NOT NULL;
    ALTER TABLE app.tokens DROP COLUMN IF EXISTS revoked_at;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_tokens_hash ON app.tokens (token_hash);

CREATE TABLE IF NOT EXISTS app.artifacts (
  id TEXT NOT NULL,
  token_id TEXT NOT NULL,
  user_id TEXT,
  visibility TEXT NOT NULL DEFAULT 'public',
  dataset_policy JSONB,
  sharing_revision INTEGER NOT NULL DEFAULT 0,
  policy_revision INTEGER NOT NULL DEFAULT 0,
  link_role TEXT,
  access TEXT NOT NULL DEFAULT 'read',
  ancestor_ids TEXT[] NOT NULL DEFAULT '{}',
  title TEXT,
  description TEXT,
  format TEXT NOT NULL DEFAULT 'markup',
  content TEXT NOT NULL,
  source TEXT,
  meta JSONB NOT NULL DEFAULT '{}',
  version INTEGER NOT NULL DEFAULT 1,
  edit_id TEXT NOT NULL DEFAULT md5(random()::text),
  actor_user_id TEXT,
  actor_token_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  forked_from TEXT,
  deleted_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS token_id TEXT NOT NULL;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'public';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS dataset_policy JSONB;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS sharing_revision INTEGER NOT NULL DEFAULT 0;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS policy_revision INTEGER NOT NULL DEFAULT 0;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS link_role TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS access TEXT NOT NULL DEFAULT 'read';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS ancestor_ids TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS title TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS format TEXT NOT NULL DEFAULT 'markup';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS content TEXT NOT NULL;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS source TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS meta JSONB NOT NULL DEFAULT '{}';

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS edit_id TEXT NOT NULL DEFAULT md5(random()::text);

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS actor_user_id TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS actor_token_id TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS forked_from TEXT;

ALTER TABLE app.artifacts ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE app.artifacts DROP COLUMN IF EXISTS folder;

CREATE INDEX IF NOT EXISTS idx_artifacts_token_updated ON app.artifacts (token_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_artifacts_ancestors ON app.artifacts USING gin (ancestor_ids);

CREATE INDEX IF NOT EXISTS idx_artifacts_parent ON app.artifacts ((ancestor_ids[cardinality(ancestor_ids)]));

CREATE INDEX IF NOT EXISTS idx_artifacts_user_level ON app.artifacts (user_id, (cardinality(ancestor_ids)));

CREATE TABLE IF NOT EXISTS app.artifact_versions (
  artifact_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  title TEXT,
  description TEXT,
  format TEXT NOT NULL DEFAULT 'markup',
  content TEXT NOT NULL,
  source TEXT,
  meta JSONB NOT NULL DEFAULT '{}',
  actor_user_id TEXT,
  actor_token_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (artifact_id, version)
);

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS title TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS format TEXT NOT NULL DEFAULT 'markup';

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS content TEXT NOT NULL;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS source TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS meta JSONB NOT NULL DEFAULT '{}';

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS actor_user_id TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS actor_token_id TEXT;

ALTER TABLE app.artifact_versions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.artifact_edits (
  seq BIGSERIAL NOT NULL,
  artifact_id TEXT NOT NULL,
  edit_id TEXT NOT NULL,
  splice_start INTEGER NOT NULL,
  removed TEXT NOT NULL,
  inserted TEXT NOT NULL,
  span_start INTEGER NOT NULL,
  span_end INTEGER NOT NULL,
  changes JSONB,
  annotation_changes JSONB,
  actor_user_id TEXT,
  actor_token_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (seq),
  UNIQUE (edit_id)
);

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS seq BIGSERIAL NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS edit_id TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS splice_start INTEGER NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS removed TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS inserted TEXT NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS span_start INTEGER NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS span_end INTEGER NOT NULL;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS changes JSONB;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS annotation_changes JSONB;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS actor_user_id TEXT;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS actor_token_id TEXT;

ALTER TABLE app.artifact_edits ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_artifact_edits_artifact_seq ON app.artifact_edits (artifact_id, seq);

CREATE TABLE IF NOT EXISTS app.artifact_source_ids (
  artifact_id TEXT NOT NULL,
  source_id TEXT NOT NULL,
  provenance TEXT NOT NULL,
  first_version INTEGER NOT NULL,
  retired_version INTEGER,
  PRIMARY KEY (artifact_id, source_id)
);

ALTER TABLE app.artifact_source_ids ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_source_ids ADD COLUMN IF NOT EXISTS source_id TEXT NOT NULL;

ALTER TABLE app.artifact_source_ids ADD COLUMN IF NOT EXISTS provenance TEXT NOT NULL;

ALTER TABLE app.artifact_source_ids ADD COLUMN IF NOT EXISTS first_version INTEGER NOT NULL;

ALTER TABLE app.artifact_source_ids ADD COLUMN IF NOT EXISTS retired_version INTEGER;

CREATE TABLE IF NOT EXISTS app.artifact_node_aliases (
  artifact_id TEXT NOT NULL,
  legacy_key TEXT NOT NULL,
  source_id TEXT NOT NULL,
  source_path TEXT NOT NULL,
  created_version INTEGER NOT NULL,
  PRIMARY KEY (artifact_id, legacy_key)
);

ALTER TABLE app.artifact_node_aliases ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_node_aliases ADD COLUMN IF NOT EXISTS legacy_key TEXT NOT NULL;

ALTER TABLE app.artifact_node_aliases ADD COLUMN IF NOT EXISTS source_id TEXT NOT NULL;

ALTER TABLE app.artifact_node_aliases ADD COLUMN IF NOT EXISTS source_path TEXT NOT NULL;

ALTER TABLE app.artifact_node_aliases ADD COLUMN IF NOT EXISTS created_version INTEGER NOT NULL;

CREATE TABLE IF NOT EXISTS app.node_identity_migration_jobs (
  name TEXT NOT NULL,
  version INTEGER NOT NULL,
  cursor TEXT,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (name)
);

ALTER TABLE app.node_identity_migration_jobs ADD COLUMN IF NOT EXISTS name TEXT NOT NULL;

ALTER TABLE app.node_identity_migration_jobs ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL;

ALTER TABLE app.node_identity_migration_jobs ADD COLUMN IF NOT EXISTS cursor TEXT;

ALTER TABLE app.node_identity_migration_jobs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

ALTER TABLE app.node_identity_migration_jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.artifact_shares (
  artifact_id TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer',
  user_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (artifact_id, email)
);

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS email TEXT NOT NULL;

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'viewer';

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.artifact_shares ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.annotations (
  revision INTEGER NOT NULL DEFAULT 1,
  id TEXT NOT NULL,
  seq BIGSERIAL NOT NULL,
  artifact_id TEXT NOT NULL,
  root_id TEXT,
  body TEXT NOT NULL,
  author_kind TEXT NOT NULL,
  author_token_id TEXT,
  author_user_id TEXT,
  author_label TEXT,
  author_transport TEXT NOT NULL DEFAULT 'unknown',
  status TEXT NOT NULL DEFAULT 'open',
  resolved_at TIMESTAMPTZ,
  anchor_key TEXT,
  anchor_version INTEGER,
  snippet TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  quote TEXT,
  range TEXT,
  deleted_at TIMESTAMPTZ,
  author_remote JSONB,
  PRIMARY KEY (id)
);

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS seq BIGSERIAL NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS root_id TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS body TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_kind TEXT NOT NULL;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_token_id TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_user_id TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_label TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_transport TEXT NOT NULL DEFAULT 'unknown';

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'open';

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS anchor_key TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS anchor_version INTEGER;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS snippet TEXT NOT NULL DEFAULT '';

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS quote TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS range TEXT;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE app.annotations ADD COLUMN IF NOT EXISTS author_remote JSONB;

CREATE INDEX IF NOT EXISTS idx_annotations_artifact_seq ON app.annotations (artifact_id, seq);

CREATE TABLE IF NOT EXISTS app.codes (
  kind TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  subject TEXT,
  payload JSONB NOT NULL DEFAULT '{}',
  attempts INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (kind, code_hash)
);

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS code_hash TEXT NOT NULL;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS subject TEXT;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}';

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL;

ALTER TABLE app.codes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_codes_kind_subject ON app.codes (kind, subject);

CREATE INDEX IF NOT EXISTS idx_codes_expires ON app.codes (expires_at);

CREATE TABLE IF NOT EXISTS app.analytics_events (
  seq BIGSERIAL NOT NULL,
  event TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  user_id TEXT,
  client TEXT,
  visitor TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (seq)
);

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS seq BIGSERIAL NOT NULL;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS event TEXT NOT NULL;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS artifact_id TEXT NOT NULL;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS client TEXT;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS visitor TEXT;

ALTER TABLE app.analytics_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_analytics_events_artifact_created ON app.analytics_events (artifact_id, created_at);

CREATE INDEX IF NOT EXISTS idx_analytics_events_event ON app.analytics_events (event);

CREATE TABLE IF NOT EXISTS app.relations (
  subject_kind TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  verb TEXT NOT NULL,
  object_kind TEXT NOT NULL,
  object_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  PRIMARY KEY (subject_kind, subject_id, verb, object_kind, object_id)
);

ALTER TABLE app.relations ADD COLUMN IF NOT EXISTS subject_kind TEXT NOT NULL;

ALTER TABLE app.relations ADD COLUMN IF NOT EXISTS subject_id TEXT NOT NULL;

ALTER TABLE app.relations ADD COLUMN IF NOT EXISTS verb TEXT NOT NULL;

ALTER TABLE app.relations ADD COLUMN IF NOT EXISTS object_kind TEXT NOT NULL;

ALTER TABLE app.relations ADD COLUMN IF NOT EXISTS object_id TEXT NOT NULL;

ALTER TABLE app.relations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.relations ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_relations_like_object ON app.relations (object_id) WHERE verb = 'like' AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_relations_follow_subject ON app.relations (subject_id) WHERE verb = 'follow' AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_relations_follow_object ON app.relations (object_id) WHERE verb = 'follow' AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app.webfonts (
  family TEXT NOT NULL,
  assets JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (family)
);

ALTER TABLE app.webfonts ADD COLUMN IF NOT EXISTS family TEXT NOT NULL;

ALTER TABLE app.webfonts ADD COLUMN IF NOT EXISTS assets JSONB NOT NULL DEFAULT '[]';

ALTER TABLE app.webfonts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.web_assets (
  url_hash TEXT NOT NULL,
  url TEXT NOT NULL,
  object_key TEXT NOT NULL,
  content_type TEXT NOT NULL,
  bytes INTEGER NOT NULL DEFAULT 0,
  width INTEGER,
  height INTEGER,
  placeholder TEXT,
  small_object_key TEXT,
  small_width INTEGER,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  fetched_by_token_id TEXT,
  fetched_by_user_id TEXT,
  PRIMARY KEY (url_hash)
);

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS url_hash TEXT NOT NULL;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS url TEXT NOT NULL;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS object_key TEXT NOT NULL;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS content_type TEXT NOT NULL;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS bytes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS width INTEGER;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS height INTEGER;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS placeholder TEXT;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS small_object_key TEXT;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS small_width INTEGER;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS fetched_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS fetched_by_token_id TEXT;

ALTER TABLE app.web_assets ADD COLUMN IF NOT EXISTS fetched_by_user_id TEXT;

CREATE INDEX IF NOT EXISTS idx_web_assets_token ON app.web_assets (fetched_by_token_id);

CREATE INDEX IF NOT EXISTS idx_web_assets_user ON app.web_assets (fetched_by_user_id);

CREATE TABLE IF NOT EXISTS app.dataset_secrets (
  id TEXT NOT NULL,
  token_id TEXT NOT NULL,
  user_id TEXT,
  dataset_id TEXT,
  target_hash TEXT NOT NULL,
  ciphertext TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

ALTER TABLE app.dataset_secrets ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.dataset_secrets ADD COLUMN IF NOT EXISTS token_id TEXT NOT NULL;

ALTER TABLE app.dataset_secrets ADD COLUMN IF NOT EXISTS user_id TEXT;

ALTER TABLE app.dataset_secrets ADD COLUMN IF NOT EXISTS dataset_id TEXT;

ALTER TABLE app.dataset_secrets ADD COLUMN IF NOT EXISTS target_hash TEXT NOT NULL;

ALTER TABLE app.dataset_secrets ADD COLUMN IF NOT EXISTS ciphertext TEXT NOT NULL;

ALTER TABLE app.dataset_secrets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_dataset_secrets_dataset ON app.dataset_secrets (dataset_id);

CREATE TABLE IF NOT EXISTS app.dataset_result_cache (
  cache_key TEXT NOT NULL,
  result JSONB,
  bytes INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ,
  owner_token TEXT,
  lease_until TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (cache_key)
);

ALTER TABLE app.dataset_result_cache ADD COLUMN IF NOT EXISTS cache_key TEXT NOT NULL;

ALTER TABLE app.dataset_result_cache ADD COLUMN IF NOT EXISTS result JSONB;

ALTER TABLE app.dataset_result_cache ADD COLUMN IF NOT EXISTS bytes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE app.dataset_result_cache ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

ALTER TABLE app.dataset_result_cache ADD COLUMN IF NOT EXISTS owner_token TEXT;

ALTER TABLE app.dataset_result_cache ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ;

ALTER TABLE app.dataset_result_cache ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.artifact_creation_operations (
  scope TEXT NOT NULL,
  operation_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  artifact_id TEXT,
  response JSONB,
  response_status INTEGER,
  response_until TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (scope, operation_key)
);

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS scope TEXT NOT NULL;

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS operation_key TEXT NOT NULL;

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS request_hash TEXT NOT NULL;

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS artifact_id TEXT;

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS response JSONB;

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS response_status INTEGER;

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS response_until TIMESTAMPTZ NOT NULL;

ALTER TABLE app.artifact_creation_operations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS app.id_reservation_batches (
  owner TEXT NOT NULL,
  batch TEXT NOT NULL,
  PRIMARY KEY (owner, batch)
);

ALTER TABLE app.id_reservation_batches ADD COLUMN IF NOT EXISTS owner TEXT NOT NULL;

ALTER TABLE app.id_reservation_batches ADD COLUMN IF NOT EXISTS batch TEXT NOT NULL;

CREATE TABLE IF NOT EXISTS app.artifact_id_registry (
  id TEXT NOT NULL,
  owner TEXT NOT NULL,
  batch TEXT,
  ordinal INTEGER,
  consumed BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);

ALTER TABLE app.artifact_id_registry ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE app.artifact_id_registry ADD COLUMN IF NOT EXISTS owner TEXT NOT NULL;

ALTER TABLE app.artifact_id_registry ADD COLUMN IF NOT EXISTS batch TEXT;

ALTER TABLE app.artifact_id_registry ADD COLUMN IF NOT EXISTS ordinal INTEGER;

ALTER TABLE app.artifact_id_registry ADD COLUMN IF NOT EXISTS consumed BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS idx_reservation_batch_ordinal ON app.artifact_id_registry (owner, batch, ordinal);

CREATE TABLE IF NOT EXISTS app.browser_test_users (
  session_id TEXT NOT NULL,
  owner TEXT NOT NULL,
  user_id TEXT NOT NULL,
  token_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  touched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (session_id, owner)
);

ALTER TABLE app.browser_test_users ADD COLUMN IF NOT EXISTS session_id TEXT NOT NULL;

ALTER TABLE app.browser_test_users ADD COLUMN IF NOT EXISTS owner TEXT NOT NULL;

ALTER TABLE app.browser_test_users ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL;

ALTER TABLE app.browser_test_users ADD COLUMN IF NOT EXISTS token_id TEXT NOT NULL;

ALTER TABLE app.browser_test_users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE app.browser_test_users ADD COLUMN IF NOT EXISTS touched_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_browser_test_users_owner ON app.browser_test_users (owner);

-- schema "auth" — owned by the auth role; tables declared by the auth's schema module

CREATE TABLE IF NOT EXISTS auth.clients (
  id TEXT NOT NULL,
  kind TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL;

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}';

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE auth.clients ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'auth' AND table_name = 'clients' AND column_name = 'revoked_at'
  ) THEN
    UPDATE auth.clients SET deleted_at = revoked_at WHERE deleted_at IS NULL AND revoked_at IS NOT NULL;
    ALTER TABLE auth.clients DROP COLUMN IF EXISTS revoked_at;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS auth.credentials (
  kind TEXT NOT NULL,
  credential_hash TEXT NOT NULL,
  subject_id TEXT,
  group_id TEXT,
  payload JSONB NOT NULL DEFAULT '{}',
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (kind, credential_hash)
);

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS credential_hash TEXT NOT NULL;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS subject_id TEXT;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS group_id TEXT;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}';

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ NOT NULL;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS consumed_at TIMESTAMPTZ;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE auth.credentials ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'auth' AND table_name = 'credentials' AND column_name = 'revoked_at'
  ) THEN
    UPDATE auth.credentials SET deleted_at = revoked_at WHERE deleted_at IS NULL AND revoked_at IS NOT NULL;
    ALTER TABLE auth.credentials DROP COLUMN IF EXISTS revoked_at;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_auth_credentials_group ON auth.credentials (group_id) WHERE group_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_auth_credentials_expiry ON auth.credentials (expires_at);

-- schema "events" — owned by the events role; tables declared by services/events/src/schema.ts

CREATE TABLE IF NOT EXISTS events.events (
  id TEXT NOT NULL,
  at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source TEXT NOT NULL,
  subject_kind TEXT,
  subject_id TEXT,
  verb TEXT NOT NULL,
  object_kind TEXT NOT NULL,
  object_id TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}',
  PRIMARY KEY (id)
);

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS id TEXT NOT NULL;

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS source TEXT NOT NULL;

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS subject_kind TEXT;

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS subject_id TEXT;

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS verb TEXT NOT NULL;

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS object_kind TEXT NOT NULL;

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS object_id TEXT NOT NULL;

ALTER TABLE events.events ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_events_object_at ON events.events (object_id, at);

CREATE INDEX IF NOT EXISTS idx_events_subject_at ON events.events (subject_id, at);

CREATE INDEX IF NOT EXISTS idx_events_kind_verb_at ON events.events (object_kind, verb, at);

CREATE TABLE IF NOT EXISTS events.deliveries (
  event_id TEXT NOT NULL,
  subscriber TEXT NOT NULL,
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  attempts INTEGER NOT NULL DEFAULT 0,
  claim TEXT,
  delivered_at TIMESTAMPTZ,
  PRIMARY KEY (event_id, subscriber)
);

ALTER TABLE events.deliveries ADD COLUMN IF NOT EXISTS event_id TEXT NOT NULL;

ALTER TABLE events.deliveries ADD COLUMN IF NOT EXISTS subscriber TEXT NOT NULL;

ALTER TABLE events.deliveries ADD COLUMN IF NOT EXISTS available_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE events.deliveries ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE events.deliveries ADD COLUMN IF NOT EXISTS claim TEXT;

ALTER TABLE events.deliveries ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_delivery_pending ON events.deliveries (subscriber, available_at) WHERE delivered_at IS NULL;

