/**
 * PHASE 3 PROBE CORPUS: every document the static-renderer parity test compiles twice (React statics, Solid
 * statics). The page-speed fixtures, the compiled-parity fixtures, the kitchen sink with dummy refs, and one
 * snippet (at least) per registered tag, plus the shapes where React's server renderer does something implicit.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { kitchenSinkMarkup } from '@/lib/story/fixtures/kitchen-sink';
import { COMPILED_PARITY_FIXTURES } from '../../../../../../scripts/fixtures/compiled-parity/index.mjs';

export interface CorpusDoc { key: string; group: 'page-speed' | 'compiled-parity' | 'kitchen' | 'tag'; markup: string; template: string | null }

const FIXTURES = path.resolve(process.cwd(), '../../scripts/fixtures/page-speed');
const fixture = (name: string) => readFileSync(path.join(FIXTURES, name), 'utf8');

/** The kitchen sink's refs (a dataset, a recipe, an image, a pdf): ids nothing resolves, as an unreadable ref serves. */
export const KITCHEN_REFS = { dataset: 'KSDATA', recipe: 'KSRECIPE', image: 'KSIMAGE', pdf: 'KSPDF' };

const ROWS = '[{"k":"a","n":1,"on":true},{"k":"b","n":2,"on":false}]';
const HELMET = `<Helmet><Value name="who" type="string" default="Ada" /><Value name="q" type="string" default="b" /><Value name="rows" type="table" value={${ROWS}} /></Helmet>`;
const doc = (key: string, body: string, template: string | null = null): CorpusDoc => ({ key, group: 'tag', markup: `${HELMET}<div data-design="tw" className="px-6" id="root">${body}</div>`, template });

/** One snippet (at least) per registered tag, static where the tag allows it, plus the React-implicit shapes. */
const TAG_SNIPPETS: CorpusDoc[] = [
  doc('card', '<Card className="mt-6" id="c1"><CardHeader id="c2"><CardTitle id="c3">Title</CardTitle><CardDescription id="c4">Description</CardDescription><CardAction id="c5">Act</CardAction></CardHeader><CardContent id="c6"><p id="c7">Body</p></CardContent><CardFooter id="c8">Foot</CardFooter></Card>'),
  doc('badge-button-alert', '<Badge id="b1">default</Badge><Badge variant="outline" className="ml-2" id="b2">outline</Badge><Button id="b3">Primary</Button><Button variant="ghost" size="sm" id="b4">Ghost</Button><Button disabled type="submit" id="b5">Off</Button><Alert variant="destructive" id="b6"><AlertTitle id="b7">Oops</AlertTitle><AlertDescription id="b8">Details</AlertDescription></Alert>'),
  doc('table', '<Table className="mt-4" id="t1"><TableCaption id="t2">Caption</TableCaption><TableHeader id="t3"><TableRow id="t4"><TableHead id="t5">Key</TableHead><TableHead className="text-right" id="t6">Count</TableHead></TableRow></TableHeader><TableBody id="t7"><TableRow id="t8"><TableCell id="t9">a</TableCell><TableCell className="text-right" id="t10">1</TableCell></TableRow></TableBody><TableFooter id="t11"><TableRow id="t12"><TableCell colSpan={2} id="t13">Total</TableCell></TableRow></TableFooter></Table>'),
  doc('separator-skeleton-progress', '<Separator id="s1" /><Separator orientation="vertical" className="mx-2" id="s2" /><Separator decorative={false} id="s3" /><Skeleton className="h-6 w-1/2" id="s4" /><Progress value={62} id="s5" /><Progress id="s6" />'),
  doc('breadcrumb', '<Breadcrumb className="mt-6" id="r1"><BreadcrumbList id="r2"><BreadcrumbItem id="r3"><BreadcrumbLink href="#top" id="r4">Gallery</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator id="r5" /><BreadcrumbItem id="r6"><BreadcrumbEllipsis id="r7" /></BreadcrumbItem><BreadcrumbSeparator id="r8">/</BreadcrumbSeparator><BreadcrumbItem id="r9"><BreadcrumbPage id="r10">Here</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb>'),
  doc('icon', '<p id="i1"><Icon name="check" id="i2" /><Icon name="circle-check" className="size-5" id="i3" /><Icon name="ChartBar" aria-label="Chart" id="i4" /><Icon name="no-such-glyph" id="i5" /></p>'),
  doc('file', '<File src="https://example.com/files/report.pdf" bytes="123456" pages="3" id="f1" /><File src="ref:NOPE" title="Gone" id="f2" /><File src="https://example.com/a.pdf" name="Named.pdf" pages="1" className="mt-2" id="f3" /><File id="f4" />'),
  doc('grid-positioned', '<Grid className="mt-6" id="g1"><GridItem x={0} y={0} w={6} h={2} id="g2"><Card className="h-full" id="g3"><CardTitle id="g4">A</CardTitle></Card></GridItem><GridItem x={6} y={0} w={6} h={3} className="bg-muted" style={{padding: 4}} id="g5"><p id="g6">B</p></GridItem></Grid>'),
  doc('grid-flow', '<Grid mode="flow" cols={3} rowHeight={40} id="g1"><GridItem w={2} minHeight={120} id="g2"><Separator id="g3" /></GridItem><GridItem w={1} id="g4"><Badge id="g5">x</Badge></GridItem><p id="g6">stray</p></Grid>'),
  doc('grid-island', '<Grid id="g1"><GridItem x={0} y={0} w={12} h={2} id="g2"><p id="g3">Hello {$who}</p><Table id="g4"><TableBody id="g5"><TableRow id="g6"><TableCell id="g7">static cell</TableCell></TableRow></TableBody></Table></GridItem></Grid>'),
  doc('tabs-with-statics', '<Tabs defaultValue="one" id="k1"><TabsList id="k2"><TabsTrigger value="one" id="k3">One</TabsTrigger><TabsTrigger value="two" id="k4">Two</TabsTrigger></TabsList><TabsContent value="one" id="k5"><Separator id="k6" /><Table id="k7"><TableBody id="k8"><TableRow id="k9"><TableCell id="k10">in a tab</TableCell></TableRow></TableBody></Table><Skeleton className="h-4" id="k11" /></TabsContent><TabsContent value="two" id="k12"><Breadcrumb id="k13"><BreadcrumbList id="k14"><BreadcrumbItem id="k15">x</BreadcrumbItem></BreadcrumbList></Breadcrumb></TabsContent></Tabs>'),
  doc('accordion-collapsible', '<Accordion type="single" collapsible defaultValue="a" id="a1"><AccordionItem value="a" id="a2"><AccordionTrigger id="a3">Q</AccordionTrigger><AccordionContent id="a4"></AccordionContent></AccordionItem></Accordion><Collapsible defaultOpen id="a6"><CollapsibleTrigger id="a7">Toggle</CollapsibleTrigger><CollapsibleContent id="a8"><File src="https://example.com/x.pdf" id="a9" /></CollapsibleContent></Collapsible>'),
  doc('tooltip-popover', '<TooltipProvider id="p1"><Tooltip defaultOpen id="p2"><TooltipTrigger id="p3">Hover</TooltipTrigger><TooltipContent id="p4">Tip</TooltipContent></Tooltip></TooltipProvider><Popover id="p5"><PopoverAnchor id="p6" /><PopoverTrigger id="p7">Open</PopoverTrigger><PopoverContent id="p8"><PopoverHeader id="p9"><PopoverTitle id="p10">T</PopoverTitle><PopoverDescription id="p11">D</PopoverDescription></PopoverHeader></PopoverContent></Popover>'),
  doc('avatar', '<AvatarGroup id="av1"><Avatar id="av2"><AvatarImage src="https://example.com/a.png" alt="A" id="av3" /><AvatarFallback id="av4">AB</AvatarFallback><AvatarBadge id="av5" /></Avatar><AvatarGroupCount id="av6">+3</AvatarGroupCount></AvatarGroup>'),
  doc('dialog', '<Dialog id="d1"><DialogTrigger id="d2">Open</DialogTrigger><DialogContent aria-label="Dlg" id="d3"><p id="d4">Inside</p><Separator id="d5" /><DialogClose id="d6">Close</DialogClose></DialogContent></Dialog>'),
  doc('controls', '<Input label="Title" value="$who" placeholder="t" id="n1" /><Textarea label="Note" value="$who" rows={2} id="n2" /><Select label="Pick" value="$q" options={["a","b"]} id="n3" /><Segmented label="Seg" value="$q" options={["a","b"]} id="n4" /><Slider label="S" value={3} min={0} max={10} id="n5" /><DatePicker label="D" value="2026-01-01" id="n6" /><Switch label="On" checked={true} id="n7" />'),
  { key: 'file-upload', group: 'tag', template: null, markup: '<Helmet><Import name="attachments" src="ref:SALES1" /><Value name="attachment" type="string" url={false} /><Value name="attachment_refs" type="string" default="[]" url={false} /><Value name="uploading" type="boolean" default={false} url={false} /></Helmet><div data-design="tw" className="px-6" id="root"><FileUpload dataset="attachments" value="$attachment" label="One file" accept="image/png" id="upload-single" /><FileUpload dataset="attachments" value="$attachment_refs" busy="$uploading" multiple label="Screenshots" maxFiles={5} id="upload-multiple" /></div>' },
  doc('people', '<p id="u1">By <User userId="$_me.id" fallback="a guest" id="u2" /> <UserImage userId="$_me.id" size="lg" fallback="no picture" id="u3" /> <UserHandle userId="$_me.id" fallback="no handle" id="u4" /></p><SignIn id="u5">Sign in</SignIn>'),
  doc('data', '<p id="x1">Rows: <Number data="$rows" col="n" agg="sum" id="x2" /></p><DataTable data="$rows" height="200px" id="x3"><Column col="k" title="Key" /><Column col="n" title="N"><Badge id="x4">{$_row.n}</Badge></Column></DataTable><Files data="$rows" variant="icons" id="x5" /><Question title="Q" data="$rows" viz={{kind:"vega-lite", spec:{mark:"bar", encoding:{x:{field:"k", type:"nominal"}, y:{field:"n", type:"quantitative"}}}}} id="x6" />'),
  doc('embeds', '<Mermaid title="Flow" code="flowchart LR; A --> B" id="e2" />'),
  doc('for-rows', '<ul className="mt-4" id="f1"><For each={$rows} keyBy="k"><li className="flex gap-2" id="f2"><Icon name="check" id="f3" /><span id="f4">{$_row.k} is {$_row.n}</span><Separator id="f5" /></li></For></ul><Table id="f6"><TableBody id="f7"><For each={$rows} keyBy="k"><TableRow id="f8"><TableCell id="f9">{$_row.k}</TableCell></TableRow></For></TableBody></Table>'),
  doc('svg', '<svg viewBox="0 0 100 40" width="100" height="40" className="text-primary" id="sv1"><title id="sv2">Chart</title><defs id="sv3"><linearGradient id="grad" x1="0" x2="1"><stop offset="0" stopColor="red" stopOpacity={0.5} /><stop offset="1" stop-color="blue" /></linearGradient><clipPath id="clip"><rect width="100" height="40" /></clipPath></defs><g clipPath="url(#clip)" id="sv4"><path d="M0 40 L50 0 L100 40" fill="url(#grad)" strokeWidth={2} stroke-linecap="round" fillOpacity="0.3" /><circle cx="50" cy="20" r="4" /><text x="50" y="30" textAnchor="middle" dominantBaseline="middle" id="sv5">Peak &amp; trough</text><polyline points="0,0 10,10" strokeDasharray="2 2" /></g></svg>'),
  doc('native-forms', '<label htmlFor="in1" id="nf0">Name</label><input id="in1" type="text" value="Ada\'s" placeholder="a > b" /><input type="checkbox" checked id="nf2" /><input type="number" value={3} min={0} readOnly id="nf3" /><textarea value="line one" rows={3} id="nf4" /><select value="b" id="nf5"><option value="a">A</option><option value="b">B</option><option>c</option></select><select id="nf6"><option selected value="z">Z</option></select><button type="button" name="go" disabled id="nf7">Go</button><progress value={40} max={100} id="nf8" /><meter value={0.4} id="nf9" />'),
  doc('text-and-voids', '<p title="it\'s > 2 & &quot;ok&quot;" id="tv1">Ada\'s "quote" &amp; <b id="tv2">bold</b> 3 &gt; 2 &lt; 4 {"literal"} {42}</p><hr className="my-2" id="tv3" /><p id="tv4">Line<br />break<wbr />here</p><img src="https://example.com/a.png" alt="An image" width={20} id="tv5" /><table id="tv6"><colgroup><col span={2} /></colgroup><tbody><tr><td>1</td></tr></tbody></table><pre id="tv7">{`\nleading newline kept`}</pre><pre id="tv8">{`no newline`}</pre><details open id="tv9"><summary id="tv10">S</summary>D</details><a href="https://example.com" target="_blank" rel="noopener" id="tv11">link</a><span style={{marginTop: 4, opacity: 0.5, "--x": "1"}} id="tv12">styled</span><div style="margin-top: 4px; -webkit-line-clamp: 2" aria-hidden="true" hidden tabIndex={0} data-flag={true} id="tv13" /><ol reversed start={3} id="tv14"><li value={7}>seven</li></ol>'),
  doc('bound-natives', '<input value="$who" id="bn1" /><img src="$who" alt="bound" id="bn2" /><p hidden={$q} id="bn3">maybe</p>'),
  doc('deck-rail', `<SlideDeck id="dk1"><Slide title="One" className="py-10" id="dk2"><h1 id="dk3">Hello {$who}</h1><Badge id="dk4">b</Badge><Card id="dk5"><CardContent id="dk6">c</CardContent></Card><Separator id="dk7" /><Table id="dk8"><TableBody id="dk9"><TableRow id="dk10"><TableCell id="dk11">cell</TableCell></TableRow></TableBody></Table></Slide><Slide title="Two" id="dk12"><ul id="dk13"><For each={$rows} keyBy="k"><li id="dk14">{$_row.k}</li></For></ul><Icon name="check" id="dk15" /><File src="https://example.com/r.pdf" id="dk17" /><svg viewBox="0 0 10 10" id="dk18"><circle cx="5" cy="5" r="4" /></svg><img src="https://example.com/i.png" alt="i" id="dk19" /><hr id="dk20" /></Slide><Slide title="Three" id="dk21"><Breadcrumb id="dk22"><BreadcrumbList id="dk23"><BreadcrumbItem id="dk24"><BreadcrumbPage id="dk25">p</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb><Skeleton id="dk26" /><Progress value={10} id="dk27" /><Alert id="dk28"><AlertTitle id="dk29">t</AlertTitle></Alert><Button id="dk30">btn</Button><p id="dk31">It's {$q} &gt; a</p><input value="$who" id="dk32" /><Grid id="dk33"><GridItem x={0} y={0} w={6} h={1} id="dk34">gi</GridItem></Grid><Number data="$rows" col="n" id="dk35" /><DataTable data="$rows" id="dk36" /></Slide></SlideDeck>`, 'deck'),
  doc('deck-rail-islands', '<SlideDeck id="di1"><Slide title="Tabs" id="di2"><Tabs defaultValue="a" id="di3"><TabsList id="di4"><TabsTrigger value="a" id="di5">A</TabsTrigger></TabsList><TabsContent value="a" id="di6">pane</TabsContent></Tabs></Slide><Slide title="Controls" id="di7"><Switch label="On" checked={true} id="di8" /><Input label="T" value="$who" id="di9" /><Accordion type="single" id="di10"><AccordionItem value="x" id="di11"><AccordionTrigger id="di12">Q</AccordionTrigger><AccordionContent id="di13">A</AccordionContent></AccordionItem></Accordion></Slide></SlideDeck>', 'deck'),
];

export async function corpus(): Promise<CorpusDoc[]> {
  const pageSpeed: CorpusDoc[] = [
    { key: 'prose', group: 'page-speed', markup: fixture('prose.jsx'), template: null },
    { key: 'kit', group: 'page-speed', markup: fixture('kit.jsx'), template: null },
    { key: 'dashboard', group: 'page-speed', markup: fixture('dashboard.jsx').replaceAll('{{sales}}', 'SALES1'), template: 'dashboard' },
    { key: 'deck', group: 'page-speed', markup: fixture('deck.jsx'), template: 'deck' },
    { key: 'mermaid', group: 'page-speed', markup: fixture('mermaid.jsx'), template: null },
  ];
  const parity: CorpusDoc[] = (COMPILED_PARITY_FIXTURES as Array<{ key: string; template: string | null; markup: string }>)
    .map((f) => ({ key: f.key, group: 'compiled-parity' as const, markup: f.markup, template: f.template }));
  const kitchen: CorpusDoc = { key: 'kitchen-sink', group: 'kitchen', markup: kitchenSinkMarkup(KITCHEN_REFS), template: null };
  return [...pageSpeed, ...parity, kitchen, ...TAG_SNIPPETS];
}
