/**
 * GENERATED by scripts/design-systems.mjs from design-systems/specs — do not edit.
 *
 * The design systems a document may name in its fence `theme`, beside the six themes
 * (./story-theme-names). A dependency-free leaf for the same reason: the reader route resolves a
 * document's mode from the name alone. The registry itself is lib/data/story/story-systems.
 */
export const STORY_SYSTEM_NAMES = ['volta', 'phosphor', 'drafting', 'meridian', 'dossier', 'riso', 'almanac', 'redline', 'nocturne', 'broadsheet', 'signout', 'sorbet', 'arcade'] as const;
export type StorySystemName = (typeof STORY_SYSTEM_NAMES)[number];
