/** The serving module's interface: only what other modules import. */
export { agentContract } from './agent-contract';
export { existingPaste } from './agent-copy';
export type { AgentDiscovery } from './agent-discovery-tags';
export { AGENT_HELP_TITLE, agentBlurb, agentDiscovery, agentDiscoveryHead, agentDiscoveryTail, llmsText, withAgentDiscoveryTail } from './agent-discovery';
export { COMPUTED_FIGURE_RULE, IMAGE_URL_FIELD_GUIDANCE, MARKUP_FIELD_GUIDANCE, MARKUP_STYLE_RULE } from './agent-guidance';
export { APP_SHELL_FONT_PRELOADS } from './app-fonts';
export { archivedReadOnly, archivedVersionFor, archivedVersionForActor, servedRow } from './archived-version';
export type { ArchivedRender } from './archived-version';
export { artifactPageAnswer, artifactPageResponse } from './artifact-page';
export type { ArtifactPageAnswer, CompiledStory } from './artifact-page';
export { artifactAppIcon, artifactManifest, artifactPwaEnabled, readableApp, withArtifactAppHead } from './artifact-pwa.server';
export { artifactAppPath } from './artifact-pwa';
export { assetByteQuotaExceeded, assetBytesForToken, setAssetByteQuotaForTests } from './asset-quota';
export { BASEMAP_ALLOWED, BASEMAP_UPSTREAM } from './basemap';
export { DOMAIN_HOME_CSP, linkedStylesheets, renderDomainHome } from './custom-domain-home';
export type { ProfileListingData } from './custom-domain-home';
export { attachDomain, canonicalDocumentUrl, customHostCandidate, domainOf, domainPostUrl, domainResolver, isServable, normalizeHostname, ownerForHost, recheckDomains, removeDomain, servesDocument, servesEmbeddedArtifact, servesWebAsset, setDomainResolver, startDomainRecheck, verifiedHostOf, verifyDomain } from './custom-domains';
export type { CaaRecord, DomainResolver } from './custom-domains';
export { mintExportKey, verifyExportKey } from './export-read-key';
export { GITHUB_EXTERNAL_URL } from './github-star';
export { CARD_HEIGHT, CARD_RENDER_GENERATION, CARD_WIDTH } from './og-card';
export { publicRefAsset, publicRefAssetResponse } from './public-ref-assets';
export { REPO_URL } from './repo';
export { BLANK_REPORT_MARKUP, START_PLACEHOLDER_MARKUP } from './start-placeholder';
export { THEME_BOOTSTRAP_HASH, THEME_BOOTSTRAP_SCRIPT } from './theme-bootstrap';
export { TILE_UPSTREAM_ORIGIN, tileUpstreamUrl, tileUrlTemplate } from './tiles';
export { WEB_ASSET_KINDS, WebAssetRefused, importForDocument, importWebAsset, lookupWebAssets, refreshWebAsset, refreshWebAssets, webAssetByHash } from './web-assets';
export type { AssetWarning, WebAssetKind } from './web-assets';
