/**
 * The agent plugin (Claude Code + Codex), generated — `plugin/` on disk and the
 * repo-root `.claude-plugin/marketplace.json` are BUILD ARTIFACTS of this
 * module. The plugin's `skills/` IS the repo's `skills/` tree (lib/skills)
 * rendered once with the production base: the same files `/docs/*` serves,
 * frontmatter and all, so the plugin cannot drift from the served docs — and
 * an agent with an installed skill and an agent fetching `/docs` read the same source.
 *
 * `npm run build:plugin` writes the files; the staleness test in
 * lib/__tests__/plugin-package.test.ts fails when disk and generator disagree.
 *
 * Layout notes:
 * - One plugin directory serves BOTH ecosystems: Claude Code reads
 *   `.claude-plugin/plugin.json`, Codex reads `.codex-plugin/plugin.json`,
 *   and both share `skills/` and `.mcp.json` at the plugin root. Every skill
 *   loader treats a SUBDIRECTORY holding a `SKILL.md` as one skill — the tree
 *   is ONE skill (`skills/artifact-bin/SKILL.md` over `references/`), so one
 *   preloaded description triggers the whole surface.
 * - This repo is private, so it is NOT the marketplace. The generated mirror
 *   tree (buildMirrorFiles) is force-forwarded to the public PLUGIN_REPO by
 *   scripts/publish-plugin.ts (CI on master), and users install from there.
 *   Nothing generated is committed here: `npm run build:plugin` writes
 *   plugin/ (gitignored) only for local `claude --plugin-dir ./plugin` runs.
 */
import { renderTree, skillFileWithFrontmatter, skillTree } from './skills';
import { MARKETPLACE_NAME, PLUGIN_INSTALL, PLUGIN_NAME } from './plugin-id';

// Bump whenever generated content changes meaningfully — installed clients
// only pull a mirror update when this moves.
export const PLUGIN_VERSION = '0.5.0';

/**
 * The canonical public deployment baked into the published plugin files.
 * Self-hosters regenerate with `npm run build:plugin -- --base <their url>`.
 */
export const PLUGIN_BASE_URL = 'https://artifactbin.dev';

// The plugin's identity lives in the client-safe leaf; server callers still
// import it all from here.
export { MARKETPLACE_NAME, PLUGIN_INSTALL, PLUGIN_NAME, PLUGIN_REPO, PLUGIN_REPO_URL } from './plugin-id';

const DESCRIPTION = 'Publish self-contained HTML artifacts (reports, dashboards, slides, datasets, charts, images) to artifact-bin and share the public link.';

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

/**
 * Every file of the plugin directory, as plugin-root-relative path → content.
 * Deterministic for a given base (no timestamps, no randomness).
 */
export function buildPluginFiles(base: string = PLUGIN_BASE_URL, transport: 'curl' | 'mcp' = 'mcp'): Record<string, string> {
  const tree = skillTree();
  const files: Record<string, string> = {
    '.claude-plugin/plugin.json': json({
      name: PLUGIN_NAME,
      description: DESCRIPTION,
      version: PLUGIN_VERSION,
      author: { name: 'minusx' },
      homepage: base,
    }),
    '.codex-plugin/plugin.json': json({
      name: PLUGIN_NAME,
      description: DESCRIPTION,
      version: PLUGIN_VERSION,
      skills: './skills/',
      mcpServers: './.mcp.json',
    }),
    '.mcp.json': json({
      mcpServers: { [PLUGIN_NAME]: { type: 'http', url: `${base}/mcp` } },
    }),
    'README.md': `# artifact-bin plugin

Skills + MCP server for publishing self-contained HTML artifacts to ${base} —
public links your user can open, share, and co-edit live.

## Install (Claude Code)

\`\`\`
${PLUGIN_INSTALL}
\`\`\`

Local development (from the artifact-bin repo): \`npm run build:plugin\`, then
\`claude --plugin-dir ./plugin\`.

## What you get

- **MCP tools** (\`create_artifact\`, \`edit_artifact\`, …) against \`${base}/mcp\`.
- **The skill** — the same files ${base}/docs serves: one \`SKILL.md\` brief with
  a dispatch table over \`references/\` topic files, loaded on demand:
${tree.dirs.map((d) => `  - \`${d.name}\` — ${d.skill.description}`).join('\n')}

## Self-hosting

The committed files point at ${base}. Running your own deployment? Regenerate
against it from the repo root:

\`\`\`
npm run build:plugin -- --base https://your-deployment.example
\`\`\`

This directory is generated by \`lib/plugin-package.ts\` from the repo's
\`skills/\` tree — edit those files, never these.
`,
  };
  // The plugin's reader has the MCP tools REGISTERED (.mcp.json above), so the
  // SHIPPED skills teach the tool calls — the `mcp` transport; every
  // HTTP-served copies can teach either action transport too. The eval's
  // installed_skill+api_action overrides to `curl`, while keeping local references.
  for (const { file, text } of renderTree(tree, base, transport, 'installed')) files[`skills/${file.path}`] = skillFileWithFrontmatter(file, text);
  return files;
}

/**
 * The complete public mirror repo (PLUGIN_REPO), as repo-relative path →
 * content: the org marketplace catalog at its root, each plugin under
 * plugins/<name>/.
 */
export function buildMirrorFiles(base: string = PLUGIN_BASE_URL, transport: 'curl' | 'mcp' = 'mcp'): Record<string, string> {
  const plugin = buildPluginFiles(base, transport);
  return {
    ...Object.fromEntries(Object.entries(plugin).map(([rel, content]) => [`plugins/${PLUGIN_NAME}/${rel}`, content])),
    '.claude-plugin/marketplace.json': json({
      name: MARKETPLACE_NAME,
      description: 'minusx plugins for Claude Code.',
      owner: { name: 'minusx' },
      plugins: [{ name: PLUGIN_NAME, source: `./plugins/${PLUGIN_NAME}`, description: DESCRIPTION }],
    }),
    'README.md': `# minusx plugins

Claude Code marketplace for minusx plugins. Add it once, install what you want:

\`\`\`
${PLUGIN_INSTALL}
\`\`\`

## Plugins

- **${PLUGIN_NAME}** — ${DESCRIPTION} Details: [plugins/${PLUGIN_NAME}/README.md](plugins/${PLUGIN_NAME}/README.md)

Everything in this repo is GENERATED and force-forwarded by the source repos'
publish pipelines — do not edit or PR here.
`,
  };
}
