/**
 * Deterministic Claude Code and Codex plugin generation from the canonical
 * skill tree. Hosted channels share content but have isolated identities.
 */
import { renderTree, skillFileWithFrontmatter, skillTree } from './skills';
import {
  MARKETPLACE_NAME,
  PLUGIN_BASE_URL,
  PLUGIN_INSTALL,
  PLUGIN_NAME,
  type PluginChannel,
  pluginChannel,
  pluginInstall,
} from './plugin-id';

export const PLUGIN_VERSION = '0.6.0';

export {
  CODEX_APP_PLUGIN_REF,
  CODEX_APP_PLUGIN_REPO_URL,
  MARKETPLACE_NAME,
  PLUGIN_BASE_URL,
  PLUGIN_CHANNELS,
  PLUGIN_INSTALL,
  PLUGIN_NAME,
  PLUGIN_REPO,
  PLUGIN_REPO_URL,
  pluginChannel,
  pluginInstall,
} from './plugin-id';
export type { PluginChannel, PluginIdentity } from './plugin-id';

const DESCRIPTION = 'Publish self-contained HTML artifacts (reports, dashboards, decks, datasets, charts, images) to artifactbin and share the public link.';
const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

function channelSkillFile(filePath: string, content: string, name: string): [string, string] {
  const canonicalPath = filePath.replace(/^artifactbin(?=\/|$)/, name);
  const canonicalContent = content.replace(/^name:\s*artifactbin\s*$/m, `name: ${name}`);
  return [canonicalPath, canonicalContent];
}

export function buildPluginFiles(
  base: string = PLUGIN_BASE_URL,
  transport: 'curl' | 'mcp' = 'mcp',
  channel: PluginChannel = 'production',
): Record<string, string> {
  const identity = pluginChannel(channel);
  const tree = skillTree();
  const files: Record<string, string> = {
    '.claude-plugin/plugin.json': json({
      name: identity.name,
      description: DESCRIPTION,
      version: PLUGIN_VERSION,
      author: { name: 'minusx' },
      homepage: base,
    }),
    '.codex-plugin/plugin.json': json({
      name: identity.name,
      description: DESCRIPTION,
      version: PLUGIN_VERSION,
      skills: './skills/',
      mcpServers: './.mcp.json',
    }),
    '.mcp.json': json({
      mcpServers: { [identity.name]: { type: 'http', url: `${base}/mcp` } },
    }),
    'README.md': `# ${identity.name} plugin

Skills and MCP server for publishing self-contained HTML artifacts to ${base}.
This is the **${identity.channel}** release channel.

## Install (Claude Code)

\`\`\`
${pluginInstall(channel)}
\`\`\`

Local development from the artifactbin repository: \`npm run build:plugin\`,
then \`claude --plugin-dir ./plugin\`.

## What you get

- MCP tools (\`create_artifact\`, \`edit_artifact\`, and others) against \`${base}/mcp\`.
- The \`${identity.name}\` skill generated from the same files served by \`${base}/docs\`.

## Self-hosting

This hosted-channel plugin points at ${base}. Self-hosters should generate
their own plugin from the source repository:

\`\`\`
npm run build:plugin -- --base https://your-deployment.example
\`\`\`

This directory is generated. Do not edit it directly.
`,
  };

  for (const { file, text } of renderTree(tree, base, transport, 'installed')) {
    const [rel, content] = channelSkillFile(file.path, skillFileWithFrontmatter(file, text), identity.name);
    files[`skills/${rel}`] = content;
  }
  return files;
}

export function buildMirrorFiles(
  base: string = PLUGIN_BASE_URL,
  transport: 'curl' | 'mcp' = 'mcp',
  channel: PluginChannel = 'production',
  sourceSha = 'development',
): Record<string, string> {
  const identity = pluginChannel(channel);
  const plugin = buildPluginFiles(base, transport, channel);
  return {
    ...Object.fromEntries(Object.entries(plugin).map(([rel, content]) => [`plugins/${identity.name}/${rel}`, content])),
    '.artifactbin-release.json': json({
      channel: identity.channel,
      plugin: identity.name,
      baseUrl: base,
      sourceRepository: 'minusxai/artifactbin',
      sourceSha,
      version: PLUGIN_VERSION,
    }),
    '.claude-plugin/marketplace.json': json({
      name: identity.marketplace,
      description: identity.description,
      owner: { name: 'minusx' },
      plugins: [{ name: identity.name, source: `./plugins/${identity.name}`, description: DESCRIPTION }],
    }),
    'README.md': `# ${identity.name} plugins

Generated ${identity.channel} plugin release for ${base}.

\`\`\`
${pluginInstall(channel)}
\`\`\`

- **${identity.name}**: ${DESCRIPTION}
- Source: \`minusxai/artifactbin@${sourceSha}\`
- Details: [plugins/${identity.name}/README.md](plugins/${identity.name}/README.md)

Everything in this repository is generated by the artifactbin source
publication workflow. Do not edit or open pull requests here.
`,
  };
}
