import {useNotifications,type InboxState} from './notification-context';
import {useEffect,useRef,useState} from 'react';
import {Button} from './ui';
type Inbox=InboxState;
export function PeopleInbox({compact=false}:{compact?:boolean}){
 const shared=useNotifications();
 const displayed=useRef<Map<string,number>|null>(null);
 const [email,setEmail]=useState<{invitations:boolean;comments:boolean;activity:boolean}|null>(null);
 useEffect(()=>{if(compact)return;void fetch('/api/my/people/email').then(r=>r.ok?r.json():null).then(data=>{if(data?.enabled)setEmail(data.preferences);}).catch(()=>{});},[compact]);
 const [state,setState]=useState<Inbox|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(input?:object){if(shared){await shared.load(input);return;}setBusy(true);setError('');try{const res=await fetch('/api/my/people',input?{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:undefined);const data=await res.json();if(!res.ok)throw Error(data.error??'Could not load notifications');if(!Array.isArray(data.notifications)||!Array.isArray(data.blocks)||typeof data.autoAccept!=='boolean')throw Error('Could not load notifications');setState(data);}catch(e){setError(e instanceof Error?e.message:'Could not load notifications');}finally{setBusy(false);}}
 async function respond(n:Inbox['notifications'][number],action:'accept'|'approve'|'dismiss'){
  if(!n.artifact_id)return;
  setBusy(true);setError('');try{
   const res=await fetch(`/api/my/artifacts/${encodeURIComponent(n.artifact_id)}/members`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(n.direction==='request'?{userId:n.user_id}:{})})});
   if(!res.ok){const result=await res.json();throw Error(result.detail??'Could not update invitation');}
   await load({read:n.id,revision:n.revision});
  }catch(e){setError(e instanceof Error?e.message:'Could not update invitation');}finally{setBusy(false);}
 }
 useEffect(()=>{if(!shared)void load();},[]);
 useEffect(()=>{if(shared){setState(shared.state);setError(shared.error);}},[shared?.state,shared?.error]);
 useEffect(()=>{if(!compact||!state)return;displayed.current??=new Map(state.notifications.map(n=>[n.id,n.revision]));const root=document.getElementById('notification-list');if(!root||typeof IntersectionObserver==='undefined')return;const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting||document.visibilityState!=='visible')continue;const n=state.notifications.find(n=>n.id===(entry.target as HTMLElement).dataset.notificationId);if(n&&!n.read_at&&displayed.current?.get(n.id)===n.revision)void load({read:n.id,revision:n.revision});}},{root,threshold:0.9});root.querySelectorAll('[data-notification-id]').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[compact,state]);
 return <section id={compact?"notification-list":"notifications"} aria-label="People and notifications" className={compact?"space-y-3":"space-y-4 rounded-xl border border-edge bg-surface p-5"}>{!compact&&<h2 className="font-medium">People & notifications</h2>}{error&&<p role="alert" className="text-sm text-danger">{error} <button onClick={()=>void load()}>Retry</button></p>}{state&&<>
  {!compact&&<label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={state.autoAccept} disabled={busy} onChange={e=>void load({autoAccept:e.target.checked})}/><span>Automatically accept invitations from people I follow.<span className="mt-1 block text-xs leading-5 text-muted">Otherwise, you can accept or decline each invitation.</span></span></label>}
  {email&&!compact&&<fieldset className="space-y-2 border-t border-edge pt-3"><legend className="text-sm font-medium">Email notifications</legend>{(['invitations','comments','activity'] as const).map(key=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={email[key]} onChange={async e=>{const preferences={...email,[key]:e.target.checked};try{const r=await fetch('/api/my/people/email',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(preferences)});if(!r.ok)throw Error();setEmail((await r.json()).preferences);}catch{setError('Could not save email preferences');}}}/>{key==='invitations'?'Invitations':key==='comments'?'Unread comment updates':'Daily likes and follows'}</label>)}</fieldset>}
  {!state.notifications.length&&<p className="text-sm text-muted">You’re all caught up.</p>}
  <ul className="divide-y divide-edge">{state.notifications.map(n=><li key={n.id} data-notification-id={n.id} className="space-y-2 py-3"><a className={`block text-sm hover:text-accent ${n.read_at?'text-muted':'text-fg'}`} href={n.kind==='follow'?`/people/${n.sender_id}`:`/a/${n.artifact_id}${n.source?.startsWith('node:')?`#${n.source.slice(5)}`:n.source?.startsWith('comment:')?`?thread=${n.source.slice(8)}${n.first_update_id?`&comment=${encodeURIComponent(n.first_update_id)}`:''}`:''}`} onClick={()=>void load({read:n.id,revision:n.revision})}>@{n.username??'someone'} {n.kind==='request'?'asked to join':n.kind==='invitation'?'invited you to':n.kind==='joined'?'added you to':n.kind==='follow'?'followed you':n.kind==='like'?'liked':n.kind==='reply_resolved'?'replied and resolved your comment in':n.kind==='reply'?'replied in':n.kind==='resolved'?'resolved a comment in':n.kind==='reopened'?'reopened a comment in':'mentioned you in'} <strong>{n.kind==='follow'?'':n.title??'Untitled artefact'}</strong></a>{n.status==='pending'&&(n.kind==='invitation'||n.kind==='request'||(n.source?.startsWith('comment:')&&n.direction==='invitation'))&&<div className="flex gap-2"><Button disabled={busy} onClick={()=>void respond(n,n.direction==='request'?'approve':'accept')}>{n.direction==='request'?'Approve request':'Accept invitation'}</Button><Button variant="ghost" disabled={busy} onClick={()=>void respond(n,'dismiss')}>Dismiss</Button></div>}{n.status==='accepted'&&(n.kind==='invitation'||n.kind==='request'||n.kind==='joined'||(n.source?.startsWith('comment:')&&n.direction==='invitation'))&&<div className="space-y-2"><p role="status" className="text-sm text-accent">{n.kind==='request'?'Approved — this person has joined the artefact.':n.kind==='invitation'?'Accepted — you’ve joined this artefact.':'You’ve joined this artefact.'}</p><a className="inline-flex rounded-md border border-edge px-3 py-1.5 text-sm hover:bg-raised" href={`/a/${n.artifact_id}`}>Open artefact</a></div>}<details className="text-xs text-muted"><summary className="cursor-pointer">More options</summary><Button variant="ghost" disabled={busy} onClick={()=>void load({block:n.sender_id})}>Block @{n.username??'sender'}</Button></details></li>)}</ul>
  {state.next!==null&&state.next!==undefined&&<Button onClick={async()=>{if(shared?.loadMore){await shared.loadMore();return;}try{const r=await fetch(`/api/my/people?offset=${state.next}`);if(!r.ok)throw Error();const next=await r.json();setState({...next,notifications:[...state.notifications,...next.notifications]});}catch{setError('Could not load more notifications');}}}>Load more</Button>}
  {!!state.blocks.length&&<details><summary className="cursor-pointer text-xs text-muted">Blocked people</summary>{state.blocks.map(b=><div className="mt-2 flex items-center justify-between" key={b.user_id}><span className="text-sm">@{b.username??b.user_id}</span><Button variant="ghost" disabled={busy} onClick={()=>void load({unblock:b.user_id})}>Unblock</Button></div>)}</details>}
 </>}</section>;
}
