import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,readdir,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {importLocalHtml,readArtifactFileHtml} from '../src/local-html-import';
import {localWorkspaceState,LOCAL_WORKSPACE_SCOPE} from '../src/local-workspace';
import {digest} from '../src/files';
import {sourceDigest,type ArtifactFile} from '../../app/lib/offline/file-format';
const base='<p id="words">Initial</p>';
function file(source=base):ArtifactFile{return {format:1,origin:'http://localhost',artifactId:'Ab12Cd',liveUrl:'',downloadedBy:'Local',downloadedAt:new Date().toISOString(),base:{version:0,editId:'',source:base},source,metadata:{title:'Report',description:null,theme:null,template:null,colorMode:null},css:{base:'',compiled:null,author:null},island:{nodes:[],refData:{},colorMode:'light'},snapshot:{at:'now',state:{values:{},tables:{},errors:{}},variants:[],frozen:[]},journal:[],threads:[],localIds:[],bundle:'solid',localWorkspace:{documentId:'Ab12Cd',baseDigest:sourceDigest(base),threadsDigest:digest('[]'),assets:{data01:{path:'rows.csv',contentType:'text/csv',base64:Buffer.from('amount\n10\n').toString('base64')}}}} as ArtifactFile;}
const html=(value:ArtifactFile)=>`<html><script>throw new Error('MUST NOT RUN')</script><script type="application/json" id="afbin-file">${JSON.stringify(value).replace(/</g,'\\u003c')}</script></html>`;
async function fixture(run:(root:string,workspace:{root:string;cwd:string;home:string;tracking:null})=>Promise<void>){const root=await mkdtemp(join(tmpdir(),'local-html-'));try{await run(root,{root,cwd:root,home:join(root,'home'),tracking:null});}finally{await rm(root,{recursive:true,force:true});}}
test('imports source and referenced bytes without executing scripts and preserves local identity',()=>fixture(async(root,workspace)=>{await writeFile(join(root,'input.html'),html(file()));const result=await importLocalHtml(workspace,'input.html','report.jsx');assert.equal(result.path,'report.jsx');assert.match(await readFile(join(root,'report.jsx'),'utf8'),/id: Ab12Cd/);assert.equal(await readFile(join(root,'rows.csv'),'utf8'),'amount\n10\n');const state=await localWorkspaceState(root);assert.equal(state.get<{id:string}>(LOCAL_WORKSPACE_SCOPE,'draft-identity','rows.csv')?.value.id,'data01');}));
test('imports an offline edit only when local body still equals its baseline; duplicate import is idempotent',()=>fixture(async(root,workspace)=>{await writeFile(join(root,'input.html'),html(file()));await importLocalHtml(workspace,'input.html','report.jsx');await writeFile(join(root,'input.html'),html(file(base.replace('Initial','Offline'))));await importLocalHtml(workspace,'input.html','report.jsx');await importLocalHtml(workspace,'input.html','report.jsx');assert.match(await readFile(join(root,'report.jsx'),'utf8'),/Offline/);}));
test('divergent edits retain both original local source and incoming HTML',()=>fixture(async(root,workspace)=>{await writeFile(join(root,'report.jsx'),'---\nid: Ab12Cd\n---\n'+base.replace('Initial','Local'));await writeFile(join(root,'input.html'),html(file(base.replace('Initial','Offline'))));await assert.rejects(importLocalHtml(workspace,'input.html','report.jsx'),/conflict/i);assert.match(await readFile(join(root,'report.jsx'),'utf8'),/Local/);assert.equal((await readdir(join(root,'.artifactbin','conflicts'))).length,1);}));
test('rejects traversal, overwritten unknown assets, symlink escape, and duplicate payload before touching source',()=>fixture(async(root,workspace)=>{for(const path of ['../outside','/absolute','C:/outside','a\\b','.artifactbin/state.sqlite']){const bad=file();bad.localWorkspace!.assets.data01!.path=path;await writeFile(join(root,'input.html'),html(bad));await assert.rejects(importLocalHtml(workspace,'input.html','report.jsx'));}await writeFile(join(root,'rows.csv'),'existing');await writeFile(join(root,'input.html'),html(file()));await assert.rejects(importLocalHtml(workspace,'input.html','report.jsx'),/asset/i);assert.equal(await readFile(join(root,'rows.csv'),'utf8'),'existing');await symlink(tmpdir(),join(root,'escape'));const escaped=file();escaped.localWorkspace!.assets.data01!.path='escape/rows.csv';await writeFile(join(root,'input.html'),html(escaped));await assert.rejects(importLocalHtml(workspace,'input.html','report.jsx'));assert.throws(()=>readArtifactFileHtml(html(file())+html(file())),/payload/i);}));
test('imports remote downloads as local documents without inheriting remote mutation credentials',()=>fixture(async(root,workspace)=>{const remote=file();delete remote.localWorkspace;remote.base.version=9;remote.base.editId='secret_edit_capability';remote.liveUrl='https://remote.invalid/a/Ab12Cd';await writeFile(join(root,'input.html'),html(remote));await importLocalHtml(workspace,'input.html','report.jsx');const source=await readFile(join(root,'report.jsx'),'utf8');assert.doesNotMatch(source,/secret_edit_capability|head_version|state:/);assert.equal(workspace.tracking,null);}));
test('preserves comment thread and reply IDs, refuses concurrent comment edits, and retains a private incoming copy',()=>fixture(async(root,workspace)=>{
 const wire={id:'thread1',status:'open' as const,anchor:{key:'words',nodeId:'words',path:'0',spanStart:0,spanEnd:20},orphaned:false,anchor_version:null,snippet:'Initial',quote:null,range:null,quote_found:null,thread:[{id:'reply1',body:'Original',author:{kind:'human' as const,label:'Sam',transport:'browser' as const,user_id:null,image:null},created_at:'2026-10-04'}],created_at:'2026-10-04',resolved_at:null};
 const initial=file();initial.threads=[wire];initial.localWorkspace!.threadsDigest=digest(JSON.stringify(initial.threads));await writeFile(join(root,'input.html'),html(initial));await importLocalHtml(workspace,'input.html','report.jsx');
 const store=await localWorkspaceState(root),imported=store.get<{file:string;node:string;value:typeof wire}>(LOCAL_WORKSPACE_SCOPE,'preview-thread','thread1')!.value;assert.equal(imported.value.thread[0]!.id,'reply1');
 const incoming=structuredClone(initial);incoming.threads[0]!.thread[0]!.body='Offline';await writeFile(join(root,'input.html'),html(incoming));
 store.put(LOCAL_WORKSPACE_SCOPE,'preview-thread','thread1',{...imported,value:{...wire,thread:[{...wire.thread[0]!,body:'Local'}]}});
 await assert.rejects(importLocalHtml(workspace,'input.html','report.jsx'),/comments.*changed/i);assert.equal(store.get<{value:typeof wire}>(LOCAL_WORKSPACE_SCOPE,'preview-thread','thread1')!.value.value.thread[0]!.body,'Local');
}));
test('default nested JSX HTML filename resolves next to the input, and rejects symlinks within the workspace',()=>fixture(async(root,workspace)=>{
 const {mkdir}=await import('node:fs/promises');await mkdir(join(root,'nested'));await writeFile(join(root,'nested','report.jsx.html'),html(file()));const result=await importLocalHtml({...workspace,cwd:join(root,'nested')},'report.jsx.html');assert.equal(result.path,'nested/report.jsx');
 await symlink(join(root,'nested','report.jsx'),join(root,'linked.jsx'));await assert.rejects(importLocalHtml(workspace,'nested/report.jsx.html','linked.jsx'),/symlink/);
}));
