/**
 * The runtime registry the server serves a design system from: services/app/lib/validation/story-system-names.ts
 * (the thirteen names, a dependency-free leaf like story-theme-names.ts), services/app/lib/data/story/story-systems.json
 * (per system: label, description, default mode, the light and dark variable maps — small, and shared with the
 * browser through story-themes) and services/app/lib/data/story/story-system-sheets.json (per system: the @font-face
 * rules for every weight and the class css: type roles, components, the hand and the page-type kit, scoped to the
 * document root's data-theme — half a megabyte the server and the CLI read and the browser never carries).
 *
 * A document names its system in the fence `theme`; the server emits the variables with the theme suffix of the
 * compiled sheet (lib/data/story/story-themes storyThemeCss, pruned per reader) and the fonts and classes with the
 * document's base sheet (lib/compiled-page/styles/story-base-css). The agent writes no CSS. Output is committed and reviewed
 * in the diff; scripts/__tests__/design-systems.test.mjs regenerates in process and fails on drift.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { REPO, ROSTER, STATUS, SKELETON_CSS, loadSpec, typeCss } from './pages.mjs';
import { fontFaceCss } from './fonts.mjs';
import { PAGE_CHROME, filterBlock, selectorOf } from './css-blocks.mjs';

export const NAMES = path.join(REPO, 'services', 'app', 'lib', 'validation', 'story-system-names.ts');
export const DATA = path.join(REPO, 'services', 'app', 'lib', 'data', 'story', 'story-systems.json');
export const SHEETS = path.join(REPO, 'services', 'app', 'lib', 'data', 'story', 'story-system-sheets.json');

/** The variable block as a map, in the order the page's binding block writes it. */
export function varsMap(spec, mode) {
  const out = {};
  const names = new Set(spec.tokens.map((tk) => tk.name));
  for (const tk of spec.tokens) out[`--ds-${tk.name}`] = mode in tk ? tk[mode] : tk.light;
  const alias = spec.status_alias ?? {};
  for (const s of STATUS) if (!names.has(s) && s in alias) out[`--ds-${s}`] = `var(--ds-${alias[s]})`;
  for (const [k, src] of Object.entries(spec.contract)) out[`--${k}`] = `var(--ds-${src})`;
  if (mode === 'light') {
    out['--radius'] = spec.radius_contract;
    const fam = spec.families;
    out['--font-display'] = fam.display; out['--font-body'] = fam.sans; out['--font-mono'] = fam.mono;
  }
  for (const [k, v] of Object.entries(spec.extra_vars ?? {})) {
    const val = v && typeof v === 'object' ? v[mode] : v;
    if (val !== null && val !== undefined) out[`--ds-${k}`] = val;
  }
  return out;
}

/**
 * `.ds-<slug>` scopes become the document root's data-theme, at the themes' specificity: the vars and hooks on
 * `:root:where([data-theme])`, the dark hooks on `:root:where([data-theme].dark)`, every class under
 * `:where(:root[data-theme])` so an authored rule of the same class wins by coming later.
 */
export function scoped(css, slug) {
  css = css.replaceAll(`.dark .ds-${slug}`, `:root:where([data-theme="${slug}"].dark)`);
  css = css.replace(new RegExp(`\\.ds-${slug}(?=\\s*\\{)`, 'g'), `:root:where([data-theme="${slug}"])`);
  css = css.replaceAll(`.ds-${slug} `, `:where(:root[data-theme="${slug}"]) `);
  return css.replaceAll(`.ds-${slug}`, `:where(:root[data-theme="${slug}"])`);
}

export function systemCss(spec) {
  const slug = spec.slug;
  const own = filterBlock(spec.css ?? '', (l) => !PAGE_CHROME.some((c) => selectorOf(l).includes(c)));
  const kit = filterBlock(SKELETON_CSS.replaceAll('.ds-X', `.ds-${slug}`), (l) => ['.h-', '.ds-row', '.ds-tpl'].some((w) => selectorOf(l).includes(w)));
  return scoped([typeCss(spec), own, kit].join('\n'), slug);
}

export function entry(slug) {
  const S = loadSpec(slug);
  return {
    name: slug, label: S.name,
    description: `${S.tagline} ${S.jobs}.`,
    defaultMode: S.color_mode === 'dark' ? 'dark' : 'light',
    cssVars: varsMap(S, 'light'), darkCssVars: varsMap(S, 'dark'),
    fontFaces: S.fonts.map(([f, a]) => fontFaceCss(f, a)).join('\n'),
    css: systemCss(S),
  };
}

/** The three generated files as text, so a test can compare them to the committed copies. */
export function renderRuntime() {
  const full = ROSTER.map(entry);
  // The registry the browser shares: everything but the sheets. The sheets, keyed by name, for the server alone.
  const entries = full.map(({ fontFaces, css, ...rest }) => { void fontFaces; void css; return rest; });
  const sheets = Object.fromEntries(full.map((e) => [e.name, { fontFaces: e.fontFaces, css: e.css }]));
  const names = `/**
 * GENERATED by scripts/design-systems.mjs from design-systems/specs — do not edit.
 *
 * The design systems a document may name in its fence \`theme\`, beside the six themes
 * (./story-theme-names). A dependency-free leaf for the same reason: the reader route resolves a
 * document's mode from the name alone. The registry itself is lib/data/story/story-systems.
 */
export const STORY_SYSTEM_NAMES = [${ROSTER.map((s) => `'${s}'`).join(', ')}] as const;
export type StorySystemName = (typeof STORY_SYSTEM_NAMES)[number];
`;
  return { names, data: JSON.stringify(entries, null, 1) + '\n', sheets: JSON.stringify(sheets, null, 1) + '\n', entries: full };
}

export function writeRuntime() {
  const { names, data, sheets, entries } = renderRuntime();
  writeFileSync(NAMES, names);
  writeFileSync(DATA, data);
  writeFileSync(SHEETS, sheets);
  const files = [[NAMES, names], [DATA, data], [SHEETS, sheets]].map(([p, text]) => ({ path: p, bytes: Buffer.byteLength(text) }));
  return { files, entries };
}
