/* GENERATED by scripts/generate-routes.mjs — do not edit. `npm run generate:routes` refreshes it. */
/* eslint-disable */
import * as r0 from '@/app/a/[id]/assets/route';
import * as r1 from '@/app/a/[id]/events/authorize/route';
import * as r2 from '@/app/a/[id]/events/frame/route';
import * as r3 from '@/app/a/[id]/events/route';
import * as r4 from '@/app/a/[id]/export/route';
import * as r5 from '@/app/a/[id]/mutate/route';
import * as r6 from '@/app/a/[id]/query/route';
import * as r7 from '@/app/a/[id]/raw/route';
import * as r8 from '@/app/a/[id]/start/route';
import * as r9 from '@/app/api/artifacts/[id]/annotations/[annId]/route';
import * as r10 from '@/app/api/artifacts/[id]/annotations/route';
import * as r11 from '@/app/api/artifacts/[id]/edits/route';
import * as r12 from '@/app/api/artifacts/[id]/fork/route';
import * as r13 from '@/app/api/artifacts/[id]/mutate/route';
import * as r14 from '@/app/api/artifacts/[id]/restore/route';
import * as r15 from '@/app/api/artifacts/[id]/revert/route';
import * as r16 from '@/app/api/artifacts/[id]/route';
import * as r17 from '@/app/api/artifacts/[id]/versions/[version]/route';
import * as r18 from '@/app/api/artifacts/[id]/versions/route';
import * as r19 from '@/app/api/artifacts/assets/refresh/route';
import * as r20 from '@/app/api/artifacts/route';
import * as r21 from '@/app/api/health/route';
import * as r22 from '@/app/api/my/artifacts/[id]/agent-prompt/route';
import * as r23 from '@/app/api/my/artifacts/[id]/annotations/[annId]/route';
import * as r24 from '@/app/api/my/artifacts/[id]/annotations/route';
import * as r25 from '@/app/api/my/artifacts/[id]/assets/refresh/route';
import * as r26 from '@/app/api/my/artifacts/[id]/edits/route';
import * as r27 from '@/app/api/my/artifacts/[id]/fork/route';
import * as r28 from '@/app/api/my/artifacts/[id]/like/route';
import * as r29 from '@/app/api/my/artifacts/[id]/restore/route';
import * as r30 from '@/app/api/my/artifacts/[id]/revert/route';
import * as r31 from '@/app/api/my/artifacts/[id]/route';
import * as r32 from '@/app/api/my/artifacts/[id]/sharing/route';
import * as r33 from '@/app/api/my/artifacts/[id]/versions/[version]/route';
import * as r34 from '@/app/api/my/artifacts/[id]/versions/route';
import * as r35 from '@/app/api/my/artifacts/route';
import * as r36 from '@/app/api/my/profile/route';
import * as r37 from '@/app/api/my/tokens/[id]/route';
import * as r38 from '@/app/api/my/tokens/route';
import * as r39 from '@/app/api/page/account/route';
import * as r40 from '@/app/api/page/artifact/[id]/route';
import * as r41 from '@/app/api/page/assets/route';
import * as r42 from '@/app/api/page/home/route';
import * as r43 from '@/app/api/page/profile/[user]/[[...path]]/route';
import * as r44 from '@/app/api/page/session/route';
import * as r45 from '@/app/api/page/trash/route';
import * as r46 from '@/app/api/preview/route';
import * as r47 from '@/app/api/query/route';
import * as r48 from '@/app/api/session/token/route';
import * as r49 from '@/app/api/start/route';
import * as r50 from '@/app/api/tokens/[id]/route';
import * as r51 from '@/app/api/tokens/anonymous/route';
import * as r52 from '@/app/api/tokens/claim/route';
import * as r53 from '@/app/api/tokens/claimable/route';
import * as r54 from '@/app/api/tokens/reject/route';
import * as r55 from '@/app/api/tokens/route';
import * as r56 from '@/app/api/users/[id]/follow/route';
import * as r57 from '@/app/assets/[hash]/route';
import * as r58 from '@/app/docs/[[...path]]/route';
import * as r59 from '@/app/health/route';
import * as r60 from '@/app/llms.txt/route';
import * as r61 from '@/app/mcp/route';
import * as r62 from '@/app/tiles/[...tile]/route';
import * as r63 from '@/app/webfonts/[file]/route';

export interface RouteEntry { path: string; dir: string; methods: string[]; module: Record<string, unknown> }
export const ROUTES: RouteEntry[] = [
  { path: "/a/:id/assets", dir: "/a/[id]/assets", methods: ["GET"], module: r0 },
  { path: "/a/:id/events/authorize", dir: "/a/[id]/events/authorize", methods: ["GET"], module: r1 },
  { path: "/a/:id/events/frame", dir: "/a/[id]/events/frame", methods: ["GET"], module: r2 },
  { path: "/a/:id/events", dir: "/a/[id]/events", methods: ["GET"], module: r3 },
  { path: "/a/:id/export", dir: "/a/[id]/export", methods: ["GET"], module: r4 },
  { path: "/a/:id/mutate", dir: "/a/[id]/mutate", methods: ["POST","OPTIONS"], module: r5 },
  { path: "/a/:id/query", dir: "/a/[id]/query", methods: ["GET","POST"], module: r6 },
  { path: "/a/:id/raw", dir: "/a/[id]/raw", methods: ["GET","HEAD"], module: r7 },
  { path: "/a/:id/start", dir: "/a/[id]/start", methods: ["GET","POST"], module: r8 },
  { path: "/api/artifacts/:id/annotations/:annId", dir: "/api/artifacts/[id]/annotations/[annId]", methods: ["POST"], module: r9 },
  { path: "/api/artifacts/:id/annotations", dir: "/api/artifacts/[id]/annotations", methods: ["GET"], module: r10 },
  { path: "/api/artifacts/:id/edits", dir: "/api/artifacts/[id]/edits", methods: ["POST"], module: r11 },
  { path: "/api/artifacts/:id/fork", dir: "/api/artifacts/[id]/fork", methods: ["POST"], module: r12 },
  { path: "/api/artifacts/:id/mutate", dir: "/api/artifacts/[id]/mutate", methods: ["POST"], module: r13 },
  { path: "/api/artifacts/:id/restore", dir: "/api/artifacts/[id]/restore", methods: ["POST"], module: r14 },
  { path: "/api/artifacts/:id/revert", dir: "/api/artifacts/[id]/revert", methods: ["POST"], module: r15 },
  { path: "/api/artifacts/:id", dir: "/api/artifacts/[id]", methods: ["GET","PUT","DELETE"], module: r16 },
  { path: "/api/artifacts/:id/versions/:version", dir: "/api/artifacts/[id]/versions/[version]", methods: ["GET"], module: r17 },
  { path: "/api/artifacts/:id/versions", dir: "/api/artifacts/[id]/versions", methods: ["GET"], module: r18 },
  { path: "/api/artifacts/assets/refresh", dir: "/api/artifacts/assets/refresh", methods: ["POST"], module: r19 },
  { path: "/api/artifacts", dir: "/api/artifacts", methods: ["GET","POST"], module: r20 },
  { path: "/api/health", dir: "/api/health", methods: ["GET"], module: r21 },
  { path: "/api/my/artifacts/:id/agent-prompt", dir: "/api/my/artifacts/[id]/agent-prompt", methods: ["POST"], module: r22 },
  { path: "/api/my/artifacts/:id/annotations/:annId", dir: "/api/my/artifacts/[id]/annotations/[annId]", methods: ["POST","DELETE"], module: r23 },
  { path: "/api/my/artifacts/:id/annotations", dir: "/api/my/artifacts/[id]/annotations", methods: ["GET","POST"], module: r24 },
  { path: "/api/my/artifacts/:id/assets/refresh", dir: "/api/my/artifacts/[id]/assets/refresh", methods: ["POST"], module: r25 },
  { path: "/api/my/artifacts/:id/edits", dir: "/api/my/artifacts/[id]/edits", methods: ["POST"], module: r26 },
  { path: "/api/my/artifacts/:id/fork", dir: "/api/my/artifacts/[id]/fork", methods: ["POST"], module: r27 },
  { path: "/api/my/artifacts/:id/like", dir: "/api/my/artifacts/[id]/like", methods: ["GET","POST","DELETE"], module: r28 },
  { path: "/api/my/artifacts/:id/restore", dir: "/api/my/artifacts/[id]/restore", methods: ["POST"], module: r29 },
  { path: "/api/my/artifacts/:id/revert", dir: "/api/my/artifacts/[id]/revert", methods: ["POST"], module: r30 },
  { path: "/api/my/artifacts/:id", dir: "/api/my/artifacts/[id]", methods: ["GET","PUT","PATCH","DELETE"], module: r31 },
  { path: "/api/my/artifacts/:id/sharing", dir: "/api/my/artifacts/[id]/sharing", methods: ["GET","PUT"], module: r32 },
  { path: "/api/my/artifacts/:id/versions/:version", dir: "/api/my/artifacts/[id]/versions/[version]", methods: ["GET"], module: r33 },
  { path: "/api/my/artifacts/:id/versions", dir: "/api/my/artifacts/[id]/versions", methods: ["GET"], module: r34 },
  { path: "/api/my/artifacts", dir: "/api/my/artifacts", methods: ["GET","POST"], module: r35 },
  { path: "/api/my/profile", dir: "/api/my/profile", methods: ["GET","PATCH"], module: r36 },
  { path: "/api/my/tokens/:id", dir: "/api/my/tokens/[id]", methods: ["DELETE"], module: r37 },
  { path: "/api/my/tokens", dir: "/api/my/tokens", methods: ["GET"], module: r38 },
  { path: "/api/page/account", dir: "/api/page/account", methods: ["GET"], module: r39 },
  { path: "/api/page/artifact/:id", dir: "/api/page/artifact/[id]", methods: ["GET"], module: r40 },
  { path: "/api/page/assets", dir: "/api/page/assets", methods: ["GET"], module: r41 },
  { path: "/api/page/home", dir: "/api/page/home", methods: ["GET"], module: r42 },
  { path: "/api/page/profile/:user/:path{.*}?", dir: "/api/page/profile/[user]/[[...path]]", methods: ["GET"], module: r43 },
  { path: "/api/page/session", dir: "/api/page/session", methods: ["GET"], module: r44 },
  { path: "/api/page/trash", dir: "/api/page/trash", methods: ["GET"], module: r45 },
  { path: "/api/preview", dir: "/api/preview", methods: ["POST"], module: r46 },
  { path: "/api/query", dir: "/api/query", methods: ["POST"], module: r47 },
  { path: "/api/session/token", dir: "/api/session/token", methods: ["POST","DELETE"], module: r48 },
  { path: "/api/start", dir: "/api/start", methods: ["POST"], module: r49 },
  { path: "/api/tokens/:id", dir: "/api/tokens/[id]", methods: ["DELETE"], module: r50 },
  { path: "/api/tokens/anonymous", dir: "/api/tokens/anonymous", methods: ["POST"], module: r51 },
  { path: "/api/tokens/claim", dir: "/api/tokens/claim", methods: ["POST"], module: r52 },
  { path: "/api/tokens/claimable", dir: "/api/tokens/claimable", methods: ["POST"], module: r53 },
  { path: "/api/tokens/reject", dir: "/api/tokens/reject", methods: ["POST"], module: r54 },
  { path: "/api/tokens", dir: "/api/tokens", methods: ["POST"], module: r55 },
  { path: "/api/users/:id/follow", dir: "/api/users/[id]/follow", methods: ["GET","POST","DELETE"], module: r56 },
  { path: "/assets/:hash", dir: "/assets/[hash]", methods: ["GET"], module: r57 },
  { path: "/docs/:path{.*}?", dir: "/docs/[[...path]]", methods: ["GET"], module: r58 },
  { path: "/health", dir: "/health", methods: ["GET"], module: r59 },
  { path: "/llms.txt", dir: "/llms.txt", methods: ["GET"], module: r60 },
  { path: "/mcp", dir: "/mcp", methods: ["GET","POST","DELETE"], module: r61 },
  { path: "/tiles/:tile{.+}", dir: "/tiles/[...tile]", methods: ["GET"], module: r62 },
  { path: "/webfonts/:file", dir: "/webfonts/[file]", methods: ["GET"], module: r63 },
];
