/**
 * Non-artifact pages (home, /tokens, login, profiles…) unfurled with no image:
 * the only `openGraph` in the app was `artifactPageMetadata`, so every other
 * URL fell back to a text-only card. The fix is ONE generic card — a checked-in
 * `public/og.png` generated by `npm run generate:og` — wired in the root
 * layout, which every non-artifact page inherits (artifact pages override the
 * whole `openGraph` key with their own on-demand export).
 *
 * Two halves, because each fails alone: the file can exist unwired, and the
 * layout can point at a file nobody generated.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '../..');

/** og:image contract: scrapers want 1200×630 (and crop anything else). */
const OG_WIDTH = 1200;
const OG_HEIGHT = 630;

describe('generic og image for non-artifact pages', () => {
  it('public/og.png exists and is a 1200×630 PNG', () => {
    const png = readFileSync(path.join(ROOT, 'public', 'og.png'));
    // PNG signature, then IHDR is always the first chunk: width/height are
    // big-endian u32 at fixed offsets 16 and 20.
    expect(png.subarray(0, 8)).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
    expect(png.readUInt32BE(16)).toBe(OG_WIDTH);
    expect(png.readUInt32BE(20)).toBe(OG_HEIGHT);
  });

  it('the SPA\'s document head names it, absolute, with the title and description', () => {
    const html = readFileSync(path.join(ROOT, 'web', 'index.html'), 'utf8');
    expect(html).toContain('<title>artifact-bin</title>');
    expect(html).toContain('name="description"');
    // The absolute og:image is stamped by the server from the request's own
    // origin (lib/http publicOrigin), so the page itself carries the file name.
    expect(readFileSync(path.join(ROOT, 'server', 'app.ts'), 'utf8')).toContain('APP_CSP');
  });
});
