/**
 * The generic unfurl card: `public/og.png`, checked in and regenerated by
 * `npm run generate:og` (scripts/generate-og-image.ts).
 *
 * A checked-in binary rots silently — nothing fails when it is the wrong size
 * or was never regenerated — so its dimensions are read out of the PNG header
 * here, together with the SPA shell's own head.
 *
 * WHO STAMPS THE TAG is server/app.ts, not the shell: `withGenericSocial` puts
 * an absolute `og:image` on every page with no document of its own, and
 * `withInitialStory` puts an artifact's own export address on the ones that
 * have. Both are asserted in server/__tests__/app.test.ts and not repeated here.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '../..');

/** og:image contract: scrapers want 1200×630 (and crop anything else). */
const OG_WIDTH = 1200;
const OG_HEIGHT = 630;

describe('generic og image for non-artifact pages', () => {
  it('public/og.png exists and is a 1200×630 PNG', () => {
    const png = readFileSync(path.join(ROOT, 'public', 'og.png'));
    // PNG signature, then IHDR is always the first chunk: width/height are
    // big-endian u32 at fixed offsets 16 and 20.
    expect(png.subarray(0, 8)).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
    expect(png.readUInt32BE(16)).toBe(OG_WIDTH);
    expect(png.readUInt32BE(20)).toBe(OG_HEIGHT);
  });

  it('the SPA shell carries the title and description, and leaves og:image to the server', () => {
    const html = readFileSync(path.join(ROOT, 'web', 'index.html'), 'utf8');
    expect(html).toContain('<title>artifactbin</title>');
    expect(html).toContain('name="description"');
    // A shell-side og:image would be relative and would collide with the tag
    // the server stamps from the request's own origin.
    expect(html).not.toContain('og:image');
  });
});
