/**
 * Named boundary-asset registry: the MinusX-approved boundaries the
 * vega geo recipes look up against. Vega may NOT fetch geometry from the network (the
 * data policy rejects `data.url`), so choropleth/point recipes reference a boundary by
 * a reserved local DATASET NAME and the render pipeline injects the resolved features
 * via `view.data()` — exactly the mechanism that binds the query result under `main`.
 *
 * Only ids in this allowlist can be resolved. US/world geometry are the standard
 * projection-clean atlas boundaries (us-atlas / world-atlas — the same Natural Earth /
 * Census sources vega-datasets derives from, with `properties.name` baked in and proper
 * Alaska/Hawaii antimeridian handling for albersUsa). They ship as TopoJSON (compact,
 * shared arcs) and are converted to GeoJSON features at load; India stays a plain
 * GeoJSON FeatureCollection. All key their region name on `properties.name`.
 */
import type { Feature, FeatureCollection } from 'geojson';
import { feature as topojsonFeature } from 'topojson-client';

/**
 * The reserved dataset name a geo recipe's boundary layer references
 * (`data: {name: GEO_BOUNDARY_DATASET}`). The renderer resolves the recipe's
 * declared asset id and injects the features under this name.
 */
export const GEO_BOUNDARY_DATASET = '__mx_geo_boundary';

/** A vega projection choice paired with a boundary set (vector basemap). */
type GeoProjection = 'albersUsa' | 'mercator' | 'equalEarth';

interface GeoAsset {
  /** Menu label. */
  label: string;
  /** Public file under `/geojson/<file>.json`. */
  file: string;
  /** GeoJSON feature `properties` key holding the region name (the lookup key). */
  nameProp: string;
  /** Vega projection that frames this boundary set well. */
  projection: GeoProjection;
  /**
   * When set, the file is a TopoJSON Topology and this names the object to extract
   * (`states`, `countries`); features are converted at load. Absent → plain GeoJSON.
   */
  topojsonObject?: string;
}

/**
 * The approved boundary sets. `albersUsa` composites Alaska/Hawaii as insets for the
 * US; world uses equalEarth; India keeps its lng/lat GeoJSON under mercator.
 */
export const GEO_ASSETS = {
  'us-states': { label: 'US (States)', file: 'us-atlas-states-10m', nameProp: 'name', projection: 'albersUsa', topojsonObject: 'states' },
  'us-counties': { label: 'US (Counties)', file: 'us-atlas-counties-10m', nameProp: 'name', projection: 'albersUsa', topojsonObject: 'counties' },
  'world': { label: 'World (Countries)', file: 'world-atlas-countries-110m', nameProp: 'name', projection: 'equalEarth', topojsonObject: 'countries' },
  'india-states': { label: 'India (States)', file: 'india-states', nameProp: 'name', projection: 'mercator' },
} as const satisfies Record<string, GeoAsset>;

type GeoAssetId = keyof typeof GEO_ASSETS;

/** The default boundary when a recipe omits `mapName`. */
const DEFAULT_GEO_ASSET: GeoAssetId = 'us-states';

/** Whether `id` is an allowlisted boundary asset. */
function isGeoAsset(id: unknown): id is GeoAssetId {
  return typeof id === 'string' && id in GEO_ASSETS;
}

/** Resolve `id` to a known asset, falling back to the default for unknown ids. */
export function resolveGeoAsset(id: unknown): GeoAssetId {
  return isGeoAsset(id) ? id : DEFAULT_GEO_ASSET;
}

/**
 * The boundary sets `<DeckGL>` may draw (`"data":"boundary:<id>"`): the Vega set
 * above plus `countries` (Natural Earth, with ISO codes; generated by
 * scripts/generate-geo-boundaries). Only these ids resolve to a file; anything
 * else is the author's own GeoJSON dataset.
 */
const GENERATED: Record<string, { file: string; topojsonObject: string }> = {
  countries: { file: 'countries', topojsonObject: 'countries' },
};

/** Every id `boundary:<id>` accepts. */
export const BOUNDARY_IDS: readonly string[] = [...Object.keys(GEO_ASSETS), ...Object.keys(GENERATED)];

/** Whether `id` names a bundled boundary set. */
export function isBoundary(id: unknown): id is string {
  return isGeoAsset(id) || (typeof id === 'string' && Object.hasOwn(GENERATED, id));
}

/** The file under `/geojson/` a boundary set lives in, or null for anything unlisted. */
export function boundaryFile(id: string): string | null {
  return isGeoAsset(id) ? GEO_ASSETS[id].file : Object.hasOwn(GENERATED, id) ? GENERATED[id]!.file : null;
}

// us-atlas keys features by FIPS in `id`; the postal code is the common join key for states.
const US_POSTAL: Record<string, string> = {
  '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO', '09': 'CT', '10': 'DE', '11': 'DC', '12': 'FL',
  '13': 'GA', '15': 'HI', '16': 'ID', '17': 'IL', '18': 'IN', '19': 'IA', '20': 'KS', '21': 'KY', '22': 'LA', '23': 'ME',
  '24': 'MD', '25': 'MA', '26': 'MI', '27': 'MN', '28': 'MS', '29': 'MO', '30': 'MT', '31': 'NE', '32': 'NV', '33': 'NH',
  '34': 'NJ', '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND', '39': 'OH', '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI',
  '45': 'SC', '46': 'SD', '47': 'TN', '48': 'TX', '49': 'UT', '50': 'VT', '51': 'VA', '53': 'WA', '54': 'WV', '55': 'WI',
  '56': 'WY', '60': 'AS', '66': 'GU', '69': 'MP', '72': 'PR', '78': 'VI',
};

/**
 * Extract GeoJSON features from a loaded boundary file per its asset config —
 * converting TopoJSON when the asset names an object, and giving the US sets
 * their FIPS (and, for states, postal) codes to join on. Pure: the render
 * pipeline's injectable seam and the unit-test entry point (no network).
 */
export function assetFeatures(id: string, json: unknown): Feature[] {
  const object = isGeoAsset(id) ? (GEO_ASSETS[id] as GeoAsset).topojsonObject : Object.hasOwn(GENERATED, id) ? GENERATED[id]!.topojsonObject : undefined;
  let features: Feature[];
  if (object) {
    // topojson-client's Topology types are structural; the object exists by construction.
    const topo = json as { objects: Record<string, unknown> };
    features = (topojsonFeature(topo as never, topo.objects[object] as never) as unknown as FeatureCollection).features;
  } else features = (json as FeatureCollection).features;
  if (id === 'us-states' || id === 'us-counties') {
    features = features.map(f => {
      const fips = String(f.id ?? '').padStart(id === 'us-states' ? 2 : 5, '0');
      return { ...f, properties: { ...f.properties, fips, ...(id === 'us-states' && US_POSTAL[fips] ? { postal: US_POSTAL[fips] } : {}) } };
    });
  }
  return features;
}

const cache: Record<string, Feature[]> = {};

/**
 * How a boundary file is fetched, given its PUBLIC path (`/geojson/<file>.json`). The default is
 * the browser fetch (same-origin static asset). Root-relative URLs are unparseable in Node, so
 * a NO-ORIGIN context (a headless server render — Slack images, scripts) has to replace this
 * fetcher with a filesystem one, or its geo charts silently render without geometry.
 */
type GeoAssetFetcher = (publicPath: string) => Promise<unknown>;

const defaultFetcher: GeoAssetFetcher = async (publicPath) => {
  const resp = await fetch(publicPath);
  if (!resp.ok) throw new Error(`Failed to load boundary asset ${publicPath}`);
  return resp.json();
};

// eslint-disable-next-line no-restricted-syntax -- module-level seam, deliberately swappable per runtime
let assetFetcher: GeoAssetFetcher = defaultFetcher;

/**
 * Load an allowlisted boundary's features for injection. Rejects unknown ids —
 * geometry only ever comes from the registry, never an arbitrary reference.
 */
export async function loadGeoFeatures(id: string): Promise<Feature[]> {
  const file = boundaryFile(id);
  if (file === null) {
    throw new Error(`unknown geo boundary "${id}" — available: ${BOUNDARY_IDS.join(', ')}`);
  }
  if (cache[id]) return cache[id];
  const features = assetFeatures(id, await assetFetcher(`/geojson/${file}.json`));
  cache[id] = features;
  return features;
}
