/** Build-only projection: authoring references + executable command/operation registries. */
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {commands,commandHelp} from '../src/commands';
import {diagnosticsHelp} from '../src/diagnostics';
import {manPage} from '../src/man';
import {skillExample,skillFileWithFrontmatter,skillTree} from '../../app/lib/skills';
import {renderSkill,condenseForBundle,stripBundleMarkers} from '../../app/lib/skills/render';
import {CLI_PROTOCOL_VERSION} from '@artifactbin/contracts';
import {TEACHING_BASE} from '../src/teaching-origin';
const root=fileURLToPath(new URL('../',import.meta.url));
// NOT an origin: the bundle ships addressed to nobody and the CLI substitutes
// the SELECTED server when it installs the skill or prints a reference
// (src/teaching-origin). A literal here would teach every self-hoster's agent
// to talk to one particular deployment.
const BASE=TEACHING_BASE;
const example=skillExample();
const brief=skillTree().get('artifactbin/SKILL.md');
if(!brief)throw new Error('skills/artifactbin/SKILL.md is missing');
// The brief keeps its frontmatter: the harness preloads the name and description, then loads the body on trigger.
const files:Record<string,string>={'SKILL.md':skillFileWithFrontmatter(brief,renderSkill(brief,{base:BASE}))};
/**
 * The SECOND length of a reference that carries `<!--bundle:skip-->` spans: what `afbin help
 * <template>` concatenates, without the rationale a single-file read can afford. Only files that
 * actually mark something appear here, so the bundle carries no duplicate of an unmarked file.
 */
const condensed:Record<string,string>={};
for(const file of skillTree().files){
 if(!file.ref||file.file.startsWith('publishing'))continue;
 const path=`references/${file.file}`;
 files[path]=renderSkill(file,{base:BASE});
 const short=renderSkill(file,{base:BASE,bundle:true});
 if(short!==files[path])condensed[path]=short;
}
files['references/errors.md']=diagnosticsHelp();
files['references/commands.md']=commands.map(command=>'## '+command.name+'\n\n```text\n'+commandHelp(command.name)+'```\n').join('\n');
/**
 * A guide is its domain rules plus the usage screens of the commands that carry them. The screens are
 * marked bundle-skippable: `afbin help <template>` concatenates seven references, and `afbin push -h`
 * already prints the screen on demand — 2.3 KB of flags is the first thing that should leave a bundle
 * an agent has to read whole. `afbin help publishing-datasets` still prints them.
 */
const guide=(title:string,body:string,names:string[])=>'# '+title+'\n\n'+body+'\n\n<!--bundle:skip-->\n'+names.map(name=>'```text\n'+commandHelp(name)+'```\n').join('\n')+'<!--/bundle:skip-->\n';
files['references/markdown.md']='# One-time Markdown import\n\nRun `afbin push report.md` to convert and publish `report.jsx`. The Markdown file stays untouched; edit and push JSX thereafter. A second Markdown push is refused, even if the generated JSX was deleted. An existing JSX destination is never overwritten.\n\n`afbin validate report.md` checks the conversion locally. `afbin push report.md --dry-run` preflights the virtual JSX without writing conversion records, files or remote objects.\n\nSupported: headings, paragraphs, emphasis, lists, block quotes, tables, links, images, fenced/inline code and horizontal rules. Raw HTML/JSX and task checkboxes are refused. Author interactive components directly in JSX. Local file references are refused. Register files with afbin add --json and use their IDs.\n';
files['references/publishing.md']=guide('Files, sync and recovery','A .jsx file has a YAML fence and static JSX body. The fence is authoritative; afbin records the accepted server state privately in ~/.artifactbin/state.sqlite and writes nothing into your working directory, so there is nothing to commit or ignore. Omitted push paths select registered and tracked files. Missing tracked files are skipped. Referenced unpublished IDs publish first; explicitly push a published dataset to update it.\n\nA CLI reference is <url|id|path>[@version]; an existing complete filename wins over an id. Published references inside markup use ref:<id>. Run afbin add --json to assign IDs before authoring references; publication preserves them.\n\nRun afbin validate report.jsx before publishing; validate --fix applies mechanical fixes. status and diff use saved state; add --remote only to refresh a comparison. An unchanged push makes no request. push --dry-run performs authoritative server validation without publishing or saving state.\n\nSuccessful writes return canonical source and identity in the same response. Push preserves edits made while the request was in flight. Retry an uncertain write with push: its frozen journal recovers the original result. A refused conflict leaves your proposal untouched and supplies a diff. pull --force overwrites local changes, so preserve a wanted proposal first; it keeps the replaced bytes under ~/.artifactbin/backups/local and reports that absolute path, archives a pending conditional proposal before replacing the working file, and cannot cancel an uncertain create. push --force observes and conditionally replaces the remote head; it never fixes markup. Deleted create results remain retired.\n\nTo adapt a document you can read, run afbin fork <ref>: it writes a private local draft without identity or invitations and records forked_from; push creates the copy. A historical pull keeps the current head conditions separately; pushing it performs a conditional replacement.', ['preview','pull','push','validate','status','diff']);
files['references/publishing.md']+='\n## Local preview\n\nRun `afbin preview report.jsx appendix.jsx` or `afbin preview .` to view and edit files without publishing. Browser saves write to disk; clean viewers refresh after external changes. Local comments stay in client SQLite. `--share` lets anyone reaching the foreground session edit and comment on selected files. Stop with Ctrl-C.\n\nRun `afbin add <files> --json` to obtain stable IDs before writing cross-file references. Artifact source uses `ref:ID` for datasets/media and `/a/ID` for document links. Preview resolves registered local files first and other IDs through the workspace host/account. Push publishes unpublished dependencies under their reserved IDs; no path-reference rewriting occurs. Preview and push register directly named files automatically. Local preview can differ from published content until edits are pushed. Preview never increments server versions or changes the saved remote baseline.\n';
files['references/publishing-auth.md']=guide('Authentication and local installation','Install or repair the CLI with the verified installer: `curl -fsSL '+TEACHING_BASE+'/chat/install.sh | sh`, or download `/chat/install.sh` from the server you use and run it with `sh`. It verifies the published SHA-256 checksum and leaves an existing installation untouched when verification fails; `/install.sh` is the separate self-hosted server installer. `afbin update` replaces that executable and the selected skills with recoverable copies of both. A skill installed or updated for a harness that reads its skills at startup (Claude Code, Codex) is marked `restart_required` and named on stderr: restart that harness to load it. `afbin update --dry-run` resolves the release and reports the same changes without installing anything.\n\nafbin authenticates itself the first time a command needs the server: it opens browser approval (log in, or continue anonymously), waits, and resumes the command — nothing to paste, no token you or the agent handle. Run afbin auth to establish or check credentials deliberately; it is idempotent. Credentials live in ~/.artifactbin/hosts/<origin-id>/credentials.env (0600), inside ~/.artifactbin (0700). Environment credentials override saved credentials and remain origin-scoped. Local help, validation, status and diff never sign in or create state.\n\nAgents never invoke auth in the normal path; a server command signs in on demand and resumes once approved. On an unattended approval timeout the command returns a structured error carrying the approval URL and expiry to relay to a person. Denial and expiry never create credentials. Standalone installs check for updates in the background; `afbin config set updates false` disables checks.\n\nCredentials are kept per server origin under ~/.artifactbin (one file per origin), so `--server`, a tracked workspace or an exported ARTIFACTBIN_URL selects the matching credential without re-approval; login never changes the default. Use `afbin config set host <origin>` to select it. Set ARTIFACTBIN_HOME to use a different private state directory, for example one per environment; exported variables reach every afbin your agent runs.', ['auth','update','serve']);
files['references/publishing-auth.md']+='\n`afbin serve --dir ./team --port 7445` initializes and runs an authenticated server in the foreground. Its directory owns settings, objects and the default PGLite database. `--db-url postgres://…` or `--db-url pglite://…` overrides only the application database. Server settings are separate from client defaults and per-host credentials. There is no managed self daemon.\n';
files['references/publishing-annotations.md']=guide('Comments','Use the artifact reference consistently. New threads use exactly one node ID or quote. An ambiguous quote is refused; use the returned current node IDs. Replies name a thread on the same artifact. Pagination applies only to listing.', ['comment']);
files['references/publishing-datasets.md']=guide('Datasets and media','Register CSV or JSON files with afbin add --json and use the returned ref:ID in a Query source. Push accepts file paths directly. SQL names public.rows for flat datasets; data="$query" binds the result. Published Query and Mutation sources use ref:<id>. A dataset a document will WRITE to is published with `afbin push tasks.csv --type dataset --access readwrite`; without that flag it is read-only and a <Mutation> against it is refused at publish. Add `--policy viewers-write` when everyone with the link must be able to work the page, not only its editors.\n\n<!--bundle:skip-->Typed user columns use a dataset YAML resource pointing at a `<Dataset>` JSX definition: `afbin help users` contains the complete files and publish command.<!--/bundle:skip-->\n\nImages and PDFs use their native formats; other supported files use file artifacts. Artifact references use IDs, never local paths. Each registered file retains its identity through preview and publication. Standalone asset replacement reports affected dependents. Read [data authoring](markup-data.md) and [catalogs](databases.md) when using connected or multi-table datasets; connection, table and notebook definitions live in dataset YAML.', ['push','pull']);
files['references/publishing-versions.md']=guide('History, deletion and export','History includes the current head. Add @version to pull or diff; log starts at that version or earlier. Delete retains local files and forgets the returned subtree identities. Repeating an owned deletion is safe. Revert by pulling ref@version and pushing conditionally; restore with push --restore; export with export.\n\n## Screenshot / export\n\nPNG/JPG export renders local JSX files and locally registered IDs with the preview runtime and Chromium, without publishing or changing source. Registered ID dependencies resolve locally first; remote dependencies require their host credentials. Other IDs and explicit artifact URLs use server rendering. HTML requires a published head.\n\nA successful push is the check: the head is exactly the file you pushed, so there is nothing to read back. If you must look, one `afbin export <ref> --output out.png` shows the whole document, every slide, in one image — never one slide at a time.\n\n## Social preview\n\nThe card a link unfurls is set in the document itself, by `<meta>` tags inside `<Helmet>`, pushed like any other source. `<meta name="artifactbin:og-image" content="ref:<imageId>" />` names the card image (publish it first with `afbin push cover.png`); `<meta name="artifactbin:og-crop" content="x=0;y=0;width=1600" />` frames the document shot instead — 40:21 out of a 1600px-wide layout, width 400–1600; `<meta name="artifactbin:og-image-crop" content="x=0;y=0;width=1600" />` takes the same `x;y;width` on the named image. Omit them all for the default full-width framing.\n\n## List your artifacts\n\n`afbin list` includes datasets and media, not only documents. Each item names its format; use --limit and --cursor for pages.', ['log','list','delete']);
files['references/publishing-query.md']=guide('Query results','Use query to read dataset rows or run a document\'s declared queries; local files run locally when their inputs are present. Standalone releases download and verify the optional SQL engine on first use; run afbin setup --service sql before disconnecting to prepare offline queries. Download requests contain no local data. Cached queries run in the CLI process. Declare Query/Mutation source="ref:<id>"; SQL names tables. Local values and query bindings are separate from artifact references. Writes require --write and a dataset target.',['query']);
// Domain rules stay in the local bundle; command syntax above comes only from its registry.
files['references/publishing.md']+='\n## Identity and authored scripts\n\nEvery body element has a persistent id for its lifetime. Move a node with the same id; never reuse an id for another node. Preserve existing data-annotation-anchor values with their element; never author, change or reuse one. New comments do not add it.\n\nScripts can reach the document endpoints /query, /events, /mutate and /geojson/ under the document CSP. They cannot make arbitrary network requests.\n\nSee [authentication](publishing-auth.md) for how afbin signs in. Full replacement, metadata and folder settings are fields of the file you push.\n';
files['references/publishing-annotations.md']+='\nComments are sidecar relations to the node\'s persistent BODY `id`; reading or writing a comment does not rewrite source or flush the editor. Legacy data-annotation-anchor attributes are preservation-only: preserve an existing value with its element; never author, change or reuse one. New comments do not add it.\n\nListing a document returns its OPEN threads only. Read the ones already settled with `afbin comment <ref> --filter state=resolved`, or both lists at once with `--filter state=all`.\n\n"snippet" is the current node text. "quote" is the selected text; quote_found says whether it is still present. Comment Markdown supports links and emphasis: `![alt](url)` is not an image, but a literal exclamation mark plus a link. A comment cannot embed a picture. A deleted thread is not erased; there is no undo for it here.\n\nBearer requests retain their account attribution.\n';
files['references/publishing-versions.md']+='\n## Trash, folders and visibility\n\nDelete is a trash: artifacts are restorable with no deadline using push --restore <id>. Deleted content still counts against your quota. Actual erasure is an administrative act on the database, outside this API. A restore can land a row deeper than the 6-level cap. An unlisted artifact is excluded from public listings, a folder page included; owners can still see their own artifacts.\n\nA folder has no content: its page is an app listing. Only title, visibility and folder are editable, through folder YAML. Do not push JSX to a folder.\n';
// Bundle-skipped for the same reason the typed-columns note above is: the per-template bundle holds
// under the shell's inline limit (help.test.ts), and this is what an agent reads when it is actually
// publishing a dataset — `afbin help publishing-datasets` and the served reference both carry it.
files['references/publishing-datasets.md']+='\n<!--bundle:skip-->A stored `<Table>` that declares its `columns` may start with `rows={[]}`: a sheet the people using the page fill in later publishes empty, with its shape, and needs no seed row. A dataset published `--policy viewers-write` stays its OWNER\'s to re-push — new rows, new columns, the grant kept — as long as the columns the policy names are still there; anyone else with edit access is refused `policy_locked`, and a governed dataset is never reverted, because viewers\' rows are in it. Read an earlier version with `afbin pull <id>@<v> --output -` or take a copy with `afbin fork <id>@<v>`, then push the content you want.<!--/bundle:skip-->\n';
files['references/publishing-datasets.md']+='\nAn imported URL is NOT an artifact and never appears in `afbin list`. Imported bytes count against your ACCOUNT\'s byte quota; a URL is charged once, to whoever first named the URL. Your external URL stays in the document while the server serves its stored copy.\n';
// The guides written here take the same markers as a reference file does; `renderSkill` never saw them.
for(const [path,text] of Object.entries(files)){
 if(!text.includes('bundle:skip'))continue;
 condensed[path]=condenseForBundle(text);
 files[path]=stripBundleMarkers(text);
}
const version=JSON.parse(readFileSync(join(root,'package.json'),'utf8')).version;
const contents=JSON.stringify({version,protocol:CLI_PROTOCOL_VERSION,files,condensed,example,man:manPage()},null,2)+'\n';
const target=join(root,'src/generated/teaching.json');
if(process.argv.includes('--check')){if(readFileSync(target,'utf8')!==contents)throw new Error('Bundled teaching is stale; run npm run generate:teaching -w services/cli.');}
else{mkdirSync(dirname(target),{recursive:true});writeFileSync(target,contents);}
console.log(`Generated local teaching: ${Object.keys(files).length} files, ${Buffer.byteLength(contents)} bytes.`);
