/** Build-only projection: authoring references + executable command/operation registries. */
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {commands,commandHelp} from '../src/commands';
import {diagnosticsHelp} from '../src/diagnostics';
import {manPage} from '../src/man';
import {skillTree} from '../../app/lib/skills';
import {renderSkill} from '../../app/lib/skills/render';
import {CLI_PROTOCOL_VERSION} from '@artifactbin/contracts';
const root=fileURLToPath(new URL('../',import.meta.url));
const files:Record<string,string>={'SKILL.md':readFileSync(join(root,'skill/SKILL.md'),'utf8')};
for(const file of skillTree().files){
 if(!file.ref||file.file.startsWith('publishing'))continue;
 files[`references/${file.file}`]=renderSkill(file,{base:'https://artifactbin.dev'});
}
files['references/errors.md']=diagnosticsHelp();
files['references/commands.md']=commands.map(command=>'## '+command.name+'\n\n```text\n'+commandHelp(command.name)+'```\n').join('\n');
const guide=(title:string,body:string,names:string[])=>'# '+title+'\n\n'+body+'\n\n'+names.map(name=>'```text\n'+commandHelp(name)+'```\n').join('\n');
files['references/markdown.md']='# One-time Markdown import\n\nRun `afbin push report.md` to convert and publish `report.jsx`. The Markdown file stays untouched; edit and push JSX thereafter. A second Markdown push is refused, even if the generated JSX was deleted. An existing JSX destination is never overwritten.\n\n`afbin validate report.md` checks the conversion locally. `afbin push report.md --dry-run` preflights the virtual JSX without writing conversion records, files or remote objects.\n\nSupported: headings, paragraphs, emphasis, lists, block quotes, tables, links, images, fenced/inline code and horizontal rules. Raw HTML/JSX and task checkboxes are refused. Author interactive components directly in JSX. Relative images are published through the same dependency pipeline as JSX.\n';
files['references/publishing.md']=guide('Files, sync and recovery','A .jsx file has a YAML fence and static JSX body. The fence is authoritative; afbin.lock records the accepted server state. Omitted push paths select tracked files only. Missing tracked files are skipped. Relative dependencies publish before their document under new IDs; an explicit standalone file push updates that file conditionally.\n\nSuccessful writes return canonical source and identity in the same response. Push preserves edits made while the request was in flight. Retry an uncertain write with push: its frozen journal recovers the original result. A refused conflict leaves your proposal untouched and supplies a diff. Forced pull archives a pending conditional proposal before replacing the working file; it cannot cancel an uncertain create. Deleted create results remain retired.\n\nTo adapt a document you can read, run afbin fork <ref>: it writes a private local draft without identity or invitations and records forked_from; push creates the copy. A historical pull keeps the current head conditions separately; pushing it performs a conditional replacement.', ['pull','push','validate','status','diff']);
files['references/publishing-auth.md']=guide('Authentication and local installation','Install or repair the CLI with the verified installer: `curl -fsSL https://artifactbin.dev/chat/install.sh | sh`, or download `/chat/install.sh` from the server you use and run it with `sh`. It verifies the published SHA-256 checksum and leaves an existing installation untouched when verification fails; `/install.sh` is the separate self-hosted server installer. `afbin update` replaces that executable and the selected skills with recoverable copies of both, and reports plugin-managed skill copies for their owning harness to refresh instead of editing a plugin cache. `afbin update --dry-run` resolves the release and reports the same changes without installing anything.\n\nRun setup to sign in through your browser and choose local harness skills. Credentials live in ~/.artifactbin/.env (0600), inside ~/.artifactbin (0700). Environment credentials override saved credentials and remain origin-scoped. Local help, validation, status and diff never sign in or create state.\n\nAgents use --yes --json without terminal prompts. --harness selects exactly the named integrations; repeat it, or choose none. Browser approval is still required. An unattended pending setup returns a URL and expiry; approve, then rerun setup. Denial and expiry never create credentials. Updates are explicit; normal commands do not poll for releases.', ['setup','update']);
files['references/publishing-annotations.md']=guide('Comments','Use the artifact reference consistently. New threads use exactly one node ID or quote. An ambiguous quote is refused; use the returned current node IDs. Replies name a thread on the same artifact. Pagination applies only to listing.', ['comment']);
files['references/publishing-datasets.md']=guide('Datasets and media','Push CSV or JSON arrays of row objects directly, or reference their relative paths from a document Query source. SQL names public.rows for flat datasets; data="$query" binds the result. Published Query and Mutation sources use ref:<id>.\n\nImages and PDFs use their native formats; other supported files use file artifacts. Relative paths must resolve inside the workspace. Standalone asset replacement reports affected dependents. Read [data authoring](markup-data.md) and [catalogs](databases.md) when using connected or multi-table datasets; connection, table and notebook definitions live in dataset YAML.', ['push','pull']);
files['references/publishing-versions.md']=guide('History, deletion and export','History includes the current head. Add @version to pull or diff; log starts at that version or earlier. Delete retains local files and forgets the returned subtree identities. Repeating an owned deletion is safe. Revert by pulling ref@version and pushing conditionally; restore with push --restore; export with export.\n\n## Screenshot / export\n\nOnly export if you can view images; otherwise read the stored markup. Use `afbin export <ref> --format png --page 2 --output slide.png` for one deck slide (1-based).\n\n## List your artifacts\n\n`afbin list` includes datasets and media, not only documents. Each item names its format; use --limit and --cursor for pages.', ['log','list','delete']);
files['references/publishing-query.md']=guide('Query results','Use query to read dataset rows or run a document\'s declared queries; local files run locally when their inputs are present. Declare Query/Mutation source="ref:<id>"; SQL names tables. Local values and query bindings are separate from artifact references. Writes require --write and a dataset target.',['query']);
// Domain rules stay in the local bundle; command syntax above comes only from its registry.
files['references/publishing.md']+='\n## Identity and authored scripts\n\nEvery body element has a persistent id for its lifetime. Move a node with the same id; never reuse an id for another node. Preserve existing data-annotation-anchor values with their element; never author, change or reuse one. New comments do not add it.\n\nScripts can reach the document endpoints /query, /events, /mutate and /geojson/ under the document CSP. They cannot make arbitrary network requests.\n\nSee [authentication](publishing-auth.md) for setup. Full replacement, metadata and folder settings are fields of the file you push.\n';
files['references/publishing-annotations.md']+='\nComments are sidecar relations to the node\'s persistent BODY `id`; reading or writing a comment does not rewrite source or flush the editor. Legacy data-annotation-anchor attributes are preservation-only: preserve an existing value with its element; never author, change or reuse one. New comments do not add it.\n\n"snippet" is the current node text. "quote" is the selected text; quote_found says whether it is still present. Comment Markdown supports links and emphasis: `![alt](url)` is not an image, but a literal exclamation mark plus a link. A comment cannot embed a picture. A deleted thread is not erased; there is no undo for it here.\n\nBearer requests retain their account attribution.\n';
files['references/publishing-versions.md']+='\n## Trash, folders and visibility\n\nDelete is a trash: artifacts are restorable with no deadline using push --restore <id>. Deleted content still counts against your quota. Actual erasure is an administrative act on the database, outside this API. A restore can land a row deeper than the 6-level cap. An unlisted artifact is excluded from public listings, a folder page included; owners can still see their own artifacts.\n\nA folder has no content: its page is an app listing. Only title, visibility and folder are editable, through folder YAML. Do not push JSX to a folder.\n';
files['references/publishing-datasets.md']+='\nAn imported URL is NOT an artifact and never appears in `afbin list`. Imported bytes count against your ACCOUNT\'s byte quota; a URL is charged once, to whoever first named the URL. Your external URL stays in the document while the server serves its stored copy.\n';
const version=JSON.parse(readFileSync(join(root,'package.json'),'utf8')).version;
const contents=JSON.stringify({version,protocol:CLI_PROTOCOL_VERSION,files,man:manPage()},null,2)+'\n';
const target=join(root,'src/generated/teaching.json');
if(process.argv.includes('--check')){if(readFileSync(target,'utf8')!==contents)throw new Error('Bundled teaching is stale; run npm run generate:teaching -w services/cli.');}
else{mkdirSync(dirname(target),{recursive:true});writeFileSync(target,contents);}
console.log(`Generated local teaching: ${Object.keys(files).length} files, ${Buffer.byteLength(contents)} bytes.`);
