/**
 * Regenerate lib/story-ui/recipe-classes.ts — the Tailwind candidate tokens used by the
 * vendored shadcn component sources. The per-story compile extracts
 * candidates from STORY markup only; component chrome classes (rounded-xl, shadow-sm, …)
 * live in the component sources, so they are pre-extracted here and unioned at compile
 * time for format:'jsx' stories.
 *
 * Run after changing anything under components/kit/:
 *   npm run generate-story-ui-classes
 * A freshness test (lib/story-ui/__tests__/recipe-classes.test.ts) fails when this file
 * is stale. Extraction is a deliberate superset: every whitespace-separated token of every
 * string literal in the sources. Non-class tokens are harmless — Tailwind emits nothing
 * for candidates it doesn't recognize.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const COMPONENTS_DIR = join(ROOT, 'components', 'kit');

// EMBED CHROME: these render INSIDE stories (portaled into the iframe), so
// their Tailwind classes must be part of every story's compiled CSS. Add each
// embed-chrome file here — every entry must exist on disk (the
// embed-chrome-coverage test enforces it, so a renamed file cannot silently
// fall out of the sheet).
/**
 * Sources OUTSIDE components/kit whose class literals still reach a story.
 * A component that leaves that directory has to be named here or its classes
 * silently stop compiling into the base sheet — the authored element renders
 * unstyled, with nothing anywhere to say why.
 */
export const EXTRA_CLASS_SOURCES = [
  join(ROOT, 'components', 'viz', 'VegaChart.tsx'),
  join(ROOT, 'components', 'views', 'story', 'InlineNumber.tsx'),
  join(ROOT, 'components', 'views', 'story', 'QuestionEmbed.tsx'),
  // The in-frame runtime composition renders embed chrome of its own (the
  // DataTable adapter's loading/error box) — its utilities must compile too.
  join(ROOT, 'lib', 'story-runtime', 'StoryRuntimeApp.tsx'),
  // App chrome AND a registered story component, so it lives beside the app's
  // primitives (the reader graph may not reach components/kit) — but a story
  // still renders it, so its classes belong in the sheet.
  join(ROOT, 'components', 'Tooltip.tsx'),
];
const OUT_FILE = join(ROOT, 'lib', 'story-ui', 'recipe-classes.ts');

export function extractRecipeClasses(dir: string, extraFiles: string[] = []): string[] {
  const tokens = new Set<string>();
  const files = [
    ...readdirSync(dir).filter((f) => f.endsWith('.tsx')).sort().map((f) => join(dir, f)),
    ...extraFiles.filter((f) => existsSync(f)),
  ];
  for (const file of files) {
    const raw = readFileSync(file, 'utf8');
    // Comments carry no class candidates, and an apostrophe inside one ("the
    // realm's document") desyncs the naive quote pairing below — a phantom
    // literal opens at the apostrophe and swallows every real class string
    // until the next one. Strip them first; line comments only when the `//`
    // is not a URL's (`http://…` inside a string must survive).
    const src = raw.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(?<!:)\/\/[^\n]*/g, ' ');
    // Every string literal (' " `) — cva recipes, className constants, template chunks.
    for (const m of src.matchAll(/'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"|`((?:[^`\\]|\\.)*)`/g)) {
      const lit = m[1] ?? m[2] ?? m[3] ?? '';
      for (const tok of lit.split(/\s+/)) {
        // Plausible utility tokens only: no quotes/braces/template holes, at least one letter.
        if (tok && !/[{}$'"`<>]/.test(tok) && /[a-zA-Z]/.test(tok)) tokens.add(tok);
      }
    }
  }
  return [...tokens].sort();
}

function main() {
  const classes = extractRecipeClasses(COMPONENTS_DIR, EXTRA_CLASS_SOURCES);
  const body = classes.map((c) => `  ${JSON.stringify(c)},`).join('\n');
  writeFileSync(
    OUT_FILE,
    `/**
 * GENERATED by scripts/generate-story-ui-classes.ts — do not edit by hand.
 * Tailwind candidate tokens extracted from components/kit sources; unioned with
 * per-story candidates when compiling format:'jsx' story CSS (see story-css.server.ts).
 * Regenerate with: npm run generate-story-ui-classes
 */
export const STORY_UI_RECIPE_CLASSES: readonly string[] = [
${body}
];
`,
  );
  console.log(`wrote ${classes.length} tokens to lib/story-ui/recipe-classes.ts`);
}

// Run only when executed directly (npm run generate-story-ui-classes) — the freshness test
// imports extractRecipeClasses and must not trigger a rewrite.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
