#!/usr/bin/env node
/**
 * The route table, GENERATED from the filesystem the way Next derived it:
 * every `app/**\/route.ts` is one entry, its exported HTTP methods its
 * handlers, its directory its path — `[id]` → `:id`, `[...rest]` → `:rest{.+}`,
 * `[[...rest]]` → an optional tail. Written to server/routes.generated.ts so
 * the server bundle has static imports; `server/__tests__/routes.test.ts`
 * fails when the file is stale, so a new route joins the table by existing.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD'];

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (name === 'route.ts') out.push(p);
  }
  return out;
}

export function toHonoPath(dir) {
  return '/' + dir.split('/').filter(Boolean).map((seg) => {
    let m;
    if ((m = /^\[\[\.\.\.(\w+)\]\]$/.exec(seg))) return `:${m[1]}{.*}?`;
    if ((m = /^\[\.\.\.(\w+)\]$/.exec(seg))) return `:${m[1]}{.+}`;
    if ((m = /^\[(\w+)\]$/.exec(seg))) return `:${m[1]}`;
    return seg;
  }).join('/');
}

export function buildTable(root = join(APP_ROOT, 'app')) {
  return walk(root).sort().map((file, i) => {
    const src = readFileSync(file, 'utf8');
    const methods = METHODS.filter((m) => new RegExp(`export (async function|const|function) ${m}\\b`).test(src) || new RegExp(`export \\{[^}]*\\b${m}\\b[^}]*\\}`).test(src));
    const dir = relative(root, file).replace(/\/?route\.ts$/, '');
    return { file, dir: '/' + dir, path: toHonoPath(dir), methods, alias: `r${i}` };
  });
}

if (process.argv[1]?.endsWith('generate-routes.mjs')) {
  const table = buildTable();
  const lines = [
    '/* GENERATED by scripts/generate-routes.mjs — do not edit. `npm run generate:routes` refreshes it. */',
    '/* eslint-disable */',
    ...table.map((t) => `import * as ${t.alias} from '@/${relative(APP_ROOT, t.file).replace(/\.ts$/, '')}';`),
    '',
    'export interface RouteEntry { path: string; dir: string; methods: string[]; module: Record<string, unknown> }',
    'export const ROUTES: RouteEntry[] = [',
    ...table.map((t) => `  { path: ${JSON.stringify(t.path)}, dir: ${JSON.stringify(t.dir)}, methods: ${JSON.stringify(t.methods)}, module: ${t.alias} },`),
    '];',
    '',
  ];
  writeFileSync(join(APP_ROOT, 'server/routes.generated.ts'), lines.join('\n'));
  console.log(`routes: ${table.length} entries → server/routes.generated.ts`);
}
