import {it,expect} from 'vitest';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm,copyFile,symlink} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {installLinuxAcceptanceDependencies,runCommand,validateRestoredAptArchives} from '../ci/linux-acceptance-deps.mjs';
async function fixture(body){const root=await mkdtemp(join(tmpdir(),'afbin-apt-cache-'));const configDirectory=join(root,'apt.conf.d'),cacheDirectory=join(root,'cache'),playwrightCli=join(root,'playwright.mjs'),aptMirrorFile=join(root,'apt-mirrors.txt');await mkdir(configDirectory);const calls=[];
const run=async(command,args)=>{calls.push({command,args});if(command===process.execPath)return runCommand(command,args);expect(command).toBe('sudo');expect(args[0]).toBe('--');const [tool,...rest]=args.slice(1);if(tool==='install'){expect(rest.slice(0,6)).toEqual(['-o','root','-g','root','-m','644']);await copyFile(rest[6],rest[7]);}else if(tool==='rm'){await rm(rest.at(-1),{force:true});}else if(tool==='chown'){expect(rest.slice(0,3)).toEqual(['--no-dereference','--','123:456']);}else if(tool==='apt-get'){expect(rest).toEqual(['update','-o','APT::Update::Error-Mode=any']);const mirrors=await readFile(aptMirrorFile,'utf8').catch(error=>error.code==='ENOENT'?null:Promise.reject(error));if(mirrors!==null)expect(mirrors).not.toContain('http://azure.archive.ubuntu.com/ubuntu');}else if(tool==='sed'){await runCommand('sed',rest);}else throw new Error('Unexpected privilege command '+tool);};
const configure=async tail=>writeFile(playwrightCli,`import assert from 'node:assert/strict';import {readFileSync,readdirSync,writeFileSync} from 'node:fs';const configs=readdirSync(${JSON.stringify(configDirectory)});assert.equal(configs.length,1,'APT archive configuration must exist before unchanged Playwright installation');const config=readFileSync(${JSON.stringify(configDirectory)}+'/'+configs[0],'utf8');assert.match(config,/Dir::Cache::archives/);assert.match(config,/Keep-Downloaded-Packages \"true\"/);assert.doesNotMatch(config,/AllowUnauthenticated|AllowInsecure|Trusted|Verify|APT::Sandbox|sources|lists/);assert.deepEqual(process.argv.slice(2),['install-deps','chromium']);${tail}`);
try{await body({root,configDirectory,cacheDirectory,playwrightCli,aptMirrorFile,calls,run,configure,options:{run,configDirectory,aptMirrorFile,uid:123,gid:456,readMetadata:async args=>{expect(calls.some(c=>c.args[1]==='apt-get')).toBe(true);expect(args).toEqual(['show','--no-all-versions','fonts-fixture=1.0']);return metadata('signed archive fixture');}}});}finally{await rm(root,{recursive:true,force:true});}}
it('always delegates a cold or warm archive cache to the unchanged Playwright signed APT/dpkg installer',()=>fixture(async f=>{await f.configure(`writeFileSync(${JSON.stringify(join(f.cacheDirectory,'fonts-fixture_1.0_all.deb'))},'signed archive fixture');`);await installLinuxAcceptanceDependencies(f,f.options);expect(await readFile(join(f.cacheDirectory,'fonts-fixture_1.0_all.deb'),'utf8')).toBe('signed archive fixture');expect(await readdir(f.configDirectory)).toEqual([]);await installLinuxAcceptanceDependencies(f,f.options);expect(f.calls.filter(c=>c.args[1]==='apt-get')).toHaveLength(2);expect(f.calls.filter(c=>c.command===process.execPath)).toHaveLength(2);expect(f.calls.filter(c=>c.args[1]==='chown')).toHaveLength(2);expect(await readdir(f.configDirectory)).toEqual([]);}));
it('cleans root configuration and retains downloaded archives when provisioning fails',()=>fixture(async f=>{await f.configure(`writeFileSync(${JSON.stringify(join(f.cacheDirectory,'fonts-fixture_1.0_all.deb'))},'retained');process.exitCode=7;`);await expect(installLinuxAcceptanceDependencies(f,f.options)).rejects.toThrow(/failed/);expect(await readdir(f.configDirectory)).toEqual([]);expect(await readFile(join(f.cacheDirectory,'fonts-fixture_1.0_all.deb'),'utf8')).toBe('retained');expect(f.calls.some(c=>c.args[1]==='chown')).toBe(true);}));
it('refuses an archive cache symlink before privileged configuration or provisioning',()=>fixture(async f=>{await symlink(f.configDirectory,f.cacheDirectory);await expect(installLinuxAcceptanceDependencies(f,f.options)).rejects.toThrow(/real directory/);expect(f.calls).toEqual([]);}));

it('rewrites the legacy Ubuntu mirror before signed APT update and skips it once rewritten',()=>fixture(async f=>{const original='deb http://azure.archive.ubuntu.com/ubuntu noble main\ndeb https://security.ubuntu.com/ubuntu noble-security main\ndeb http://archive.ubuntu.com/ubuntu noble-updates main\n';await writeFile(f.aptMirrorFile,original);await f.configure('');await installLinuxAcceptanceDependencies(f,f.options);const rewritten='deb https://archive.ubuntu.com/ubuntu noble main\ndeb https://security.ubuntu.com/ubuntu noble-security main\ndeb http://archive.ubuntu.com/ubuntu noble-updates main\n';expect(await readFile(f.aptMirrorFile,'utf8')).toBe(rewritten);const mirrorEdit=f.calls.findIndex(c=>c.args[1]==='sed'),aptUpdate=f.calls.findIndex(c=>c.args[1]==='apt-get');expect(mirrorEdit).toBeGreaterThanOrEqual(0);expect(mirrorEdit).toBeLessThan(aptUpdate);await installLinuxAcceptanceDependencies(f,f.options);expect(await readFile(f.aptMirrorFile,'utf8')).toBe(rewritten);expect(f.calls.filter(c=>c.args[1]==='sed')).toHaveLength(1);}));

it('skips the optional Ubuntu mirror file when it is absent',()=>fixture(async f=>{await f.configure('');await installLinuxAcceptanceDependencies(f,f.options);expect(f.calls.some(c=>c.args[1]==='sed')).toBe(false);expect(f.calls.some(c=>c.args[1]==='apt-get')).toBe(true);}));

it('propagates mirror read errors instead of treating them as a missing file',()=>fixture(async f=>{await mkdir(f.aptMirrorFile);await f.configure('');await expect(installLinuxAcceptanceDependencies(f,f.options)).rejects.toThrow();expect(f.calls.some(c=>c.args[1]==='apt-get')).toBe(false);}));

it('propagates mirror write errors before refreshing signed APT metadata',()=>fixture(async f=>{await writeFile(f.aptMirrorFile,'deb http://azure.archive.ubuntu.com/ubuntu noble main\n');await f.configure('');const run=async(command,args)=>{if(command==='sudo'&&args[1]==='sed')throw new Error('mirror write failed');return f.run(command,args);};await expect(installLinuxAcceptanceDependencies(f,{...f.options,run})).rejects.toThrow('mirror write failed');expect(f.calls.some(c=>c.args[1]==='apt-get')).toBe(false);}));

function metadata(bytes,{version='1.0',arch='all',hash=true}={}){return 'Package: fonts-fixture\nVersion: '+version+'\nArchitecture: '+arch+'\nSize: '+Buffer.byteLength(bytes)+'\n'+(hash?'SHA256: '+createHash('sha256').update(bytes).digest('hex')+'\n':'')+'Filename: pool/main/f/fonts-fixture/fonts-fixture_1.0_all.deb\n';}
async function hashFixture(run){const root=await mkdtemp(join(tmpdir(),'afbin-apt-hash-'));try{await run(root);}finally{await rm(root,{recursive:true,force:true});}}
it('verifies real cached archive content hashes against exact fresh metadata, including epoch versions',()=>hashFixture(async root=>{const file=join(root,'fonts-fixture_1%3a1.0_all.deb');await writeFile(file,'valid signed bytes');const result=await validateRestoredAptArchives(root,async args=>{expect(args).toEqual(['show','--no-all-versions','fonts-fixture=1:1.0']);return metadata('valid signed bytes',{version:'1:1.0'});});expect(result).toEqual({verified:1,discarded:0});expect(await readFile(file,'utf8')).toBe('valid signed bytes');}));
it('discards same-size corrupted archives before APT can execute their maintainer scripts',()=>hashFixture(async root=>{const file=join(root,'fonts-fixture_1.0_all.deb');await writeFile(file,'bad bytes');expect(Buffer.byteLength('bad bytes')).toBe(Buffer.byteLength('goodbytes'));expect(await validateRestoredAptArchives(root,async()=>metadata('goodbytes'))).toEqual({verified:0,discarded:1});expect(await readdir(root)).toEqual([]);}));
it.each([{hash:false},{version:'2.0'},{arch:'arm64'}])('discards archives not authorized by exact SHA256/version/architecture metadata (%j)',options=>hashFixture(async root=>{await writeFile(join(root,'fonts-fixture_1.0_all.deb'),'signed bytes');expect(await validateRestoredAptArchives(root,async()=>metadata('signed bytes',options))).toEqual({verified:0,discarded:1});expect(await readdir(root)).toEqual([]);}));
it('discards unknown archive names without interpreting them as commands',()=>hashFixture(async root=>{await writeFile(join(root,'unknown.deb'),'bytes');let reads=0;expect(await validateRestoredAptArchives(root,async()=>{reads++;return '';})).toEqual({verified:0,discarded:1});expect(reads).toBe(0);expect(await readdir(root)).toEqual([]);}));

it('refuses symlinked archive files without reading metadata or touching their targets',()=>hashFixture(async root=>{const target=join(root,'outside'),link=join(root,'fonts-fixture_1.0_all.deb');await writeFile(target,'untouched');await symlink(target,link);let lookups=0;await expect(validateRestoredAptArchives(root,async()=>{lookups++;return '';})).rejects.toThrow(/regular files/);expect(lookups).toBe(0);expect(await readFile(target,'utf8')).toBe('untouched');}));
