import { z } from 'zod';
import type { Operation, OpReply } from './registry';
import type { MembershipInput } from '@artifactbin/contracts';
import { changeMembership, membershipState, mentionCandidates, MembershipError } from '../membership';
const errors=[{status:403,code:'membership_refused',fix:'Check document access, invitation eligibility and who may approve this request.'},{status:409,code:'membership_changed',fix:'Refresh membership state; you may have reached the 30 pending request limit.'}];
async function response(work:()=>Promise<object>):Promise<OpReply>{try{return {status:200,body:{...await work()}};}catch(error){if(error instanceof MembershipError)return {status:error.status,body:{error:error.status===409?'membership_changed':'membership_refused',detail:error.message}};throw error;}}
export const MEMBERSHIP_OPERATIONS:Operation[]=[
 {name:'get_artifact_members',title:'Read artifact members',http:{method:'GET',path:'/api/artifacts/{id}/members'},description:'Read accepted members and your own membership. Owners and editors also see pending requests. Comment access is independent of joining.',input:{id:z.string(),query:z.string().max(100).optional()},annotations:{readOnly:true},example:{input:{id:'a1B2c3'}},errors,run:(ctx,input)=>response(async()=>input.query===undefined?membershipState(ctx.actor,String(input.id)):{people:await mentionCandidates(ctx.actor,String(input.id),String(input.query))})},
 {name:'change_artifact_membership',title:'Join or invite people',http:{method:'POST',path:'/api/artifacts/{id}/members'},description:'Join, invite @usernames, accept an invitation, approve/dismiss a request, or leave. Owners/editors join immediately; others request approval. Invite only followers or existing members. Recipients who follow you auto-accept unless disabled. At most 30 pending requests per sender across all agents.',input:{id:z.string(),action:z.enum(['join','invite','accept','approve','dismiss','leave']),usernames:z.array(z.string()).min(1).max(30).optional(),userId:z.string().optional()},annotations:{},example:{input:{id:'a1B2c3',action:'invite',usernames:['@alex','@sam']}},errors,run:(ctx,input)=>response(()=>changeMembership(ctx.actor,String(input.id),input as unknown as MembershipInput))},
];
