/** The command registry is projected into the versioned local bundle; HTTP integrations have their own email-authenticated reference. */
import {expect,it} from 'vitest';
import {commands,commandHelp} from '../../../../cli/src/commands';
import teaching from '../../../../cli/src/generated/teaching.json';
it('documents every command/flag and direct HTTP while refusing retired CLI and remote-skill transports',()=>{
 const reference=teaching.files['references/commands.md'];
 for(const command of commands)expect(reference,command.name).toContain(commandHelp(command.name));
 for(const [file,text] of Object.entries(teaching.files))expect(text,file).not.toMatch(/afbin api|--method|MCP|\/docs\/|references\/api\.md/);
 expect(Object.keys(teaching.files)).not.toContain('references/api.md');
 const http=teaching.files['references/http-api.md'];
 expect(http).toContain('/api/auth/email-otp/send-verification-otp');
 expect(http).toContain('/api/authentication/token');
 expect(http).toContain('Only verified email account sessions qualify');
 expect(http).toContain('http-authoring.md');
 expect(http).toContain('GET /api/artifacts/<id>/policy` to observe `revision`');
 expect(http).toContain('`expectedPolicyRevision`');
 expect(http).not.toContain('to observe `policy_revision`');
 expect(http).toContain('## Browser preview and interactive QA');
 expect(http).toContain('POST /api/browser-sessions');
 expect(http).toContain('output.image(await page.screenshot())');
 expect(http).toContain("op:'status'");
 expect(http).toContain("op:'close'");
 expect(http).toMatch(/scripts run for at most 20 seconds/i);
 expect(http).toMatch(/no local Chrome/i);
 expect(http).toContain('POST /api/artifacts/<page-id>/mutate');
 expect(http).toContain('{"name":"vote","args":{"choice":"ramen"}}');
 expect(http).toContain('A public or unlisted link does not grant writes');
 expect(http).toContain('may return 403 even to its owner under the default policy');
 expect(http).toContain('[actions](markup-data.md#declarations-helmet-only)');
 expect(http).toContain('[dataset rules](apps.md#dataset-rules)');
 expect(teaching.files['references/http-authoring.md']).toContain('function buildPlainTextUpdate');
 expect(teaching.files['references/http-document-graph.md']).toContain('patch.claims');
});
