/**
 * WHICH READERS THE SERVER OFFERS STORED MERMAID DRAWINGS TO — server-side,
 * per request and per drawing.
 *
 * A reader keeps a stored drawing only when it measures the drawing's faces as
 * the harvest's browser did (lib/mermaid-images/match); one that would not
 * checks, finds the drawing is not its own, and downloads the engine as well.
 * The server cannot measure a reader, so it predicts, from what it knows —
 * the reader's user agent and the faces the drawing was drawn in — using a
 * MEASURED table (reader-match.json, generated by scripts/mermaid-reader-match.mjs:
 * every manifest family at 11–16px in each reader class vs the unhinted Linux
 * harvest). Measured, Blink on macOS agrees with the harvest for Inter at 16px
 * but not at 14px (line box 17.02px vs 18px), for JetBrains Mono at every
 * size, for Noto Serif only at 14px. A class or face the table does not hold —
 * Windows, Linux, Android, ChromeOS, WebKit, Gecko: not measured to agree — is
 * served the engine's page: no stored drawing, and the engine's code preloaded.
 */
import table from './reader-match.json';
import { storedMermaidMetrics, type MermaidFaces } from './match';

export type MermaidReaderClass = keyof typeof table.classes;

/** Blink on macOS (Chrome, Edge and the other Chromium browsers; not Chrome on iOS, which is WebKit). */
export function mermaidReaderClass(userAgent: string | null | undefined): MermaidReaderClass | null {
  if (!userAgent) return null;
  const blink = /\b(?:Headless)?Chrom(?:e|ium)\/\d/.test(userAgent) && !/\b(?:CriOS|EdgiOS|FxiOS|OPiOS)\//.test(userAgent) && !/\bFirefox\//.test(userAgent);
  return blink && /\(Macintosh;/.test(userAgent) && !/Android|CrOS|Linux|iPhone|iPad|iPod/.test(userAgent) ? 'macos-blink' : null;
}

const EDGE_LABEL_PX = 11;
const agrees = (reader: MermaidReaderClass, family: string, size: number): boolean =>
  ((table.classes[reader].faces as Record<string, number[] | undefined>)[family] ?? []).includes(size);

/**
 * May this stored drawing be offered to this reader? Only one drawn entirely
 * in the document's web fonts (`portable`), stored with its measurements, in
 * faces the reader's class is measured to lay out as the harvest did: the
 * label face at its size and the edge-label face at 11px.
 */
export function servableTo(info: { portable?: boolean; metrics?: readonly number[]; faces?: MermaidFaces }, reader: MermaidReaderClass): boolean {
  if (info.portable !== true || !storedMermaidMetrics(info.metrics) || !info.faces) return false;
  return agrees(reader, info.faces.label, info.faces.size) && agrees(reader, info.faces.edge, EDGE_LABEL_PX);
}
