import {it,expect,afterEach} from 'vitest';
import {DEFAULT_SOCIAL_PREVIEW_CROP} from '@/lib/story/social-preview';
import {fakeBrowser} from '@artifactbin/utils';
import {setServices} from '@/lib/services';
import {resetExportRenderer} from '@/lib/export';
import {request,useAppHarness} from './harness';
import {mintToken} from '@/lib/tokens';
import {POST as create} from '@/app/api/artifacts/route';
import {PUT as replace,GET as read} from '@/app/api/artifacts/[id]/route';
import {POST as revert} from '@/app/api/artifacts/[id]/revert/route';
import {GET as exportImage} from '@/app/api/artifacts/[id]/export/route';
useAppHarness();afterEach(()=>setServices({}));
it('revert returns the complete canonical head so the next write needs no read-back',async()=>{
 const token=await mintToken('cli-revert');const original=await(await create(request('/api/artifacts',{method:'POST',token:token.token,json:{markup:'<p>Original</p>',title:'Doc'}}))).json();
 const params={params:Promise.resolve({id:original.id})},path=`/api/artifacts/${original.id}`;
 const updated=await(await replace(request(path,{method:'PUT',token:token.token,json:{markup:'<p>Changed</p>',expectedVersion:original.version,expectedState:original.state}}),params)).json();
 const restored=await revert(request(path+'/revert',{method:'POST',token:token.token,json:{version:original.version,expectedVersion:updated.version,expectedState:updated.state}}),params);
 expect(restored.status).toBe(200);const body=await restored.json();
 const canonical=await(await read(request(path,{token:token.token}),params)).json();
 for(const key of ['id','version','edit_id','state','markup','title','theme','template','visibility'])expect(body[key],key).toEqual(canonical[key]);
 expect(body.state).toMatch(/^[a-f0-9]{64}$/);
});
it('authenticated export forwards card mode and refuses an unknown mode',async()=>{
 await resetExportRenderer();const browser=fakeBrowser();setServices({browser});
 const token=await mintToken('cli-export');const doc=await(await create(request('/api/artifacts',{method:'POST',token:token.token,json:{markup:'<h1>Card</h1>'}}))).json();
 const params={params:Promise.resolve({id:doc.id})};
 const invalid=await exportImage(request(`/api/artifacts/${doc.id}/export?mode=wrong`,{token:token.token}),params);expect(invalid.status).toBe(400);
 const result=await exportImage(request(`/api/artifacts/${doc.id}/export?mode=card`,{token:token.token}),params);expect(result.status).toBe(200);
 expect((browser as unknown as {calls:Array<{capture:string}>}).calls.at(-1)?.capture).toEqual({card:DEFAULT_SOCIAL_PREVIEW_CROP});
});
