import { changeMembership,claimToken,createUser,mintToken } from '@/lib/accounts';
import { updateSharingFor } from '@/lib/artifacts';
import { setDatasetPolicy } from '@/lib/datasets/policy';
import { POST as createArtifact } from '@/app/api/artifacts/route';
import { POST as uploadImage } from '@/app/a/[id]/datasets/[datasetId]/images/route';
import { GET as readImage } from '@/app/a/[id]/datasets/[datasetId]/images/[imageId]/route';
import { getDb } from '@/lib/platform';
import sharp from 'sharp';
import { expect,it } from 'vitest';
import { request,useAppHarness } from './harness';

useAppHarness();
const imageParams=(id:string,datasetId:string,imageId:string)=>({params:Promise.resolve({id,datasetId,imageId})});
it('uploads through a real pages actor, replays safely, and rechecks the current dataset read grant',async()=>{
  const owner=await createUser({email:'mxmx_test_image_owner@example.test'}),reporter=await createUser({email:'mxmx_test_image_reporter@example.test'});
  const token=await mintToken('feedback-images-owner');await claimToken(owner.id,token.token);
  const ownerActor={userId:owner.id,tokenId:token.id};
  const make=async(body:object)=>{const response=await createArtifact(request('/api/artifacts',{method:'POST',token:token.token,json:body}));expect(response.status,await response.clone().text()).toBe(201);return response.json();};
  const dataset=await make({dataset:[{message:'initial',image_ref:''}],visibility:'private',access:'readwrite'});
  const document=await make({visibility:'public',markup:`<Helmet><Import name="feedback" src="ref:${dataset.id}" /><Value name="message" type="string" default="" /><Value name="image_ref" type="string" default="" /><Mutation name="submit">{\`insert into feedback.rows (message,image_ref) values ($message,$image_ref)\`}</Mutation></Helmet>`});
  await updateSharingFor(ownerActor,dataset.id,{shares:[{email:reporter.email!,role:'viewer'}]});
  await setDatasetPolicy(ownerActor,dataset.id,{version:2,allow:[{actions:['read'],from:{user:'*'}},{actions:['insert'],from:{artifact:document.id}}]},0);
  await changeMembership({userId:reporter.id,tokenId:null},document.id,{action:'join'});
  await changeMembership(ownerActor,document.id,{action:'approve',userId:reporter.id});
  const bytes=await sharp({create:{width:40,height:24,channels:3,background:'#c0392b'}}).png().toBuffer();
  const pageActor={credential:'session' as const,userId:reporter.id,email:reporter.email!,emailVerified:true};
  const post=(body:Buffer,key='upload-operation-123')=>uploadImage(request(`/a/${document.id}/datasets/${dataset.id}/images`,{method:'POST',actor:pageActor,headers:{'Content-Type':'image/png','X-Edit-Id':document.edit_id,'Idempotency-Key':key},body:new Uint8Array(body)}),{params:Promise.resolve({id:document.id,datasetId:dataset.id})});
  const created=await post(bytes);expect(created.status,await created.clone().text()).toBe(201);const uploaded=await created.json() as {ref:string;url:string};
  expect(uploaded.ref).toMatch(/^dimg:/);expect(uploaded.url).toContain(`/a/${document.id}/datasets/${dataset.id}/images/`);
  const repeated=await post(bytes);expect(repeated.status).toBe(201);expect((await repeated.json()).ref).toBe(uploaded.ref);
  const conflict=await post(Buffer.from('different'),'upload-operation-123');expect(conflict.status).toBe(409);
  const imageId=uploaded.ref.slice('dimg:'.length),read=(who:{credential:'session';userId:string;email:string;emailVerified:boolean})=>readImage(request(uploaded.url,{actor:who}),imageParams(document.id,dataset.id,imageId));
  const visible=await read(pageActor);expect(visible.status).toBe(200);expect(visible.headers.get('x-content-type-options')).toBe('nosniff');expect(visible.headers.get('cache-control')).toBe('private, no-store');
  const ownerSession={credential:'session' as const,userId:owner.id,email:owner.email!,emailVerified:true};
  expect((await read(ownerSession)).status).toBe(200);
  await setDatasetPolicy(ownerActor,dataset.id,{version:2,allow:[{actions:['read'],from:{user:owner.id}},{actions:['insert'],from:{artifact:document.id}}]},1);
  expect((await read(pageActor)).status).toBe(404);expect((await read(ownerSession)).status).toBe(200);
  const db=await getDb();await db.query('UPDATE artifacts SET deleted_at=now() WHERE id=$1',[dataset.id]);
  expect((await read(ownerSession)).status).toBe(404);
  expect((await db.query('SELECT count(*)::int AS count FROM dataset_images WHERE dataset_id=$1',[dataset.id])).rows[0]?.count).toBe(1);
});
