import {OPERATIONS} from '@/lib/operations/registry';
import {expect,it} from 'vitest';
import {request,useAppHarness} from './harness';
import {documentEditBody} from './prepared-document';
import {getArtifactById} from '@/lib/artifacts';
import {mintToken} from '@/lib/tokens';
import {POST as create} from '@/app/api/artifacts/route';
import {POST as edit} from '@/app/api/artifacts/[id]/edits/route';
import {PATCH as patch} from '@/app/api/artifacts/[id]/route';
useAppHarness();
it('document metadata uses guarded operations, preserves omission, clears null and records a version',async()=>{
 const token=await mintToken('metadata');const original=await(await create(request('/api/artifacts',{method:'POST',token:token.token,json:{title:'Before',theme:'organic',markup:'<p>hello</p>'}}))).json();
 const base=(await getArtifactById(original.id))!;
 const send=(body:Record<string,unknown>)=>edit(request(`/api/artifacts/${original.id}/edits`,{method:'POST',token:token.token,json:body}),{params:Promise.resolve({id:original.id})});
 const missing=await patch(request(`/api/artifacts/${original.id}`,{method:'PATCH',token:token.token,json:{title:'No'}}),{params:Promise.resolve({id:original.id})});
 expect(missing.status).toBe(400);expect((await missing.json()).error).toBe('jsonb_operations_required');
 const response=await send(documentEditBody(base,{metadata:{title:null}}));expect(response.status).toBe(200);const updated=await response.json();
 expect(updated).toMatchObject({title:null,theme:'organic',version:original.version+1});expect(updated.edit_id).not.toBe(original.edit_id);expect(updated.state).not.toBe(original.state);
 const stale=await send(documentEditBody(base,{metadata:{title:'Stale'}}));expect(stale.status).toBe(409);
 const invalid=documentEditBody(base,{metadata:{theme:'pop'}});
 Object.assign(invalid.document_update,{settings:{visibility:null}});
 expect((await send(invalid)).status).toBe(400);
});
it('the advanced registry exposes the same operation-based metadata write',async()=>{
 const operation=OPERATIONS.find(x=>x.name==='edit_artifact');expect(operation).toBeDefined();expect(operation?.http.method).toBe('POST');
 const token=await mintToken('metadata-registry');const req=request('/api/artifacts',{method:'POST',token:token.token,json:{markup:'<p>hello</p>'}});
 const original=await(await create(req)).json(),base=(await getArtifactById(original.id))!;
 const result=await operation!.run({actor:{tokenId:token.id,userId:null},base:'http://localhost',request:req,author:{kind:'agent',label:null,transport:'http'}},{id:original.id,...documentEditBody(base,{metadata:{title:'After'}})});
 expect(result.status).toBe(200);expect(result.body).toMatchObject({title:'After',version:original.version+1});expect(result.body.state).not.toBe(original.state);
});
