import {expect,it,afterEach} from 'vitest';
import {useAppHarness} from './harness';
import {RemoteRegistry} from '@/lib/remote/registry';
import {RemoteAgents} from '@/lib/remote/agents';
import {getDb} from '@/lib/db';
useAppHarness();
const registries:RemoteRegistry[]=[];
const fresh=()=>{const r=new RemoteRegistry();registries.push(r);return new RemoteAgents(r);};
afterEach(()=>{for(const r of registries)r.clear();registries.length=0;});
const registration={name:'claude',harness:'claude',cwd:'/project',machine:'test',cols:80,rows:24,managed:true,recoveryKey:'a'.repeat(64)};
const exchange=(runnerKey:string)=>({runnerKey,cols:80,rows:24,ack:0,outputSeq:0,output:''});
it('reserves names across relays, keeps stable proof and color on reconnect, and persists stop',async()=>{
 const a=fresh(),b=fresh();const s=await a.create('owner',registration);
 await expect(b.create('owner',{...registration,recoveryKey:'b'.repeat(64)})).rejects.toThrow(/already running/);
 const offline=await b.view('owner',s.id,0);expect(offline.session).toMatchObject({id:s.id,name:'claude',online:false,color:s.color});expect(offline.frames).toEqual([]);
 await expect(b.view('another-owner',s.id,0)).rejects.toThrow(/not found/);
 const recovered=await b.create('owner',registration);expect(recovered.runnerKey).toBe(s.runnerKey);expect(recovered.color).toBe(s.color);
 await b.stop('owner',s.id);
 const c=fresh();await c.create('owner',registration);
 expect((await c.exchange('owner',s.id,exchange(s.runnerKey))).stop).toBe(true);
 await c.exchange('owner',s.id,{...exchange(s.runnerKey),exitCode:0});
 expect((await c.create('owner',{...registration,recoveryKey:'b'.repeat(64)})).name).toBe('claude');
});
it('queues only once, waits for ready, and marks interrupted delivery uncertain instead of replaying',async()=>{
 const token=await mintToken('queue');const user=await createUser({email:'mxmx_test_queue@example.com'});await claimToken(user.id,token.token);const owner=user.id;
 const made=await publish(request('/api/artifacts',{method:'POST',token:token.token,json:{markup:'<p>queue</p>'}}));const artifactId=(await made.json()).id;
 const a=fresh();const s=await a.create(owner,registration);
 const comment={id:'comment',body:`[@claude](/chat?session=${s.id}) fix it`,author:{kind:'human' as const,label:'Owner'}};
 const db=await getDb();await db.transaction(async tx=>{await a.enqueue(tx,owner,artifactId,'thread',comment);await a.enqueue(tx,owner,artifactId,'thread',comment);});
 expect((await a.exchange(owner,s.id,exchange(s.runnerKey))).inputs).toEqual([]);
 await expect(a.ready(owner,s.id,'wrong')).rejects.toThrow(/credential/);
 await a.ready(owner,s.id,s.runnerKey);
 const delivered=await a.exchange(owner,s.id,exchange(s.runnerKey));expect(delivered.inputs).toHaveLength(1);
 expect(delivered.inputs[0].requestId).toBeTruthy();
 const b=fresh();await b.create(owner,registration);
 expect((await b.exchange(owner,s.id,exchange(s.runnerKey))).inputs).toEqual([]);
 expect((await b.work(db,artifactId,'thread'))[0].phase).toBe('uncertain');
 await db.transaction(tx=>b.enqueue(tx,'other',artifactId,'thread',{...comment,id:'other'}));
 expect(await b.work(db,artifactId,'thread')).toHaveLength(1);
});
import {request,agentCookie} from './harness';
import {mintToken} from '@/lib/tokens';
import {createUser,claimToken} from '@/lib/users';
import {POST as publish} from '@/app/api/artifacts/route';
import {POST as comment} from '@/app/api/my/artifacts/[id]/annotations/route';
import {POST as reply} from '@/app/api/artifacts/[id]/annotations/[annId]/route';
import {remoteAgents} from '@/lib/remote/agents';
import {remoteSessions} from '@/lib/remote/registry';
afterEach(()=>remoteSessions.clear());
it('commits mention delivery with the comment, authenticates receipts, and refuses resolving over a later human comment',async()=>{
 const token=await mintToken('review');const user=await createUser({email:'mxmx_test_receipt@example.com'});await claimToken(user.id,token.token);
 const cookie=await agentCookie([token.id]);
 const made=await publish(request('/api/artifacts',{method:'POST',token:token.token,json:{markup:'<p>Review me</p>'}}));expect(made.status).toBe(201);const doc=await made.json();
 const s=await remoteAgents.create(user.id,registration);
 const root=await comment(request(`/api/my/artifacts/${doc.id}/annotations`,{method:'POST',cookie,json:{path:'0',edit_id:doc.edit_id,body:`[@claude](/chat?session=${s.id}) fix this`}}),{params:Promise.resolve({id:doc.id})});expect(root.status).toBe(201);const thread=await root.json();
 expect(thread.remote_work).toHaveLength(1);const work=thread.remote_work[0];
 await remoteAgents.ready(user.id,s.id,s.runnerKey);await remoteAgents.exchange(user.id,s.id,exchange(s.runnerKey));
 const answer=async(phase:string,proof:string,resolve=false)=>{const req=request(`/api/artifacts/${doc.id}/annotations/${thread.id}`,{method:'POST',token:token.token,json:{reply:'Review response',request_id:work.id,phase,resolve}});req.headers.set('X-Artifactbin-Remote-Session',s.id);req.headers.set('X-Artifactbin-Remote-Proof',proof);return reply(req,{params:Promise.resolve({id:doc.id,annId:thread.id})});};
 expect((await answer('acknowledged','wrong')).status).toBe(403);
 expect((await answer('completed',s.runnerKey)).status).toBe(409);
 const ack=await answer('acknowledged',s.runnerKey);expect(ack.status).toBe(200);expect((await ack.json()).thread.at(-1).author).toMatchObject({label:'claude',sessionId:s.id,color:s.color});
 const db=await getDb();await db.query("INSERT INTO annotations (id,artifact_id,root_id,body,author_kind,author_user_id) VALUES ('later',$1,$2,'another thing','human',$3)",[doc.id,thread.id,user.id]);
 expect((await answer('completed',s.runnerKey,true)).status).toBe(409);
 expect((await remoteAgents.work(db,doc.id,thread.id))[0].phase).toBe('acknowledged');
 expect((await answer('completed',s.runnerKey)).status).toBe(200);
 expect((await remoteAgents.work(db,doc.id,thread.id))[0].phase).toBe('completed');
});
