import {afterEach,expect,it} from 'vitest';
import {useAppHarness,request} from './harness';
import {createUser,mintToken,claimToken} from '@/lib/accounts';
import {POST as publish} from '@/app/api/artifacts/route';
import {PUT as replace} from '@/app/api/artifacts/[id]/route';
import {observedTextBody} from './prepared-document';
import {artifactSchedule,startLambdaSchedules,setLambdaProgramResolver} from '@/lib/runner';
import {setServices} from '@/lib/platform/services';
import type {RunnerService} from '@artifactbin/contracts';
const harness=useAppHarness();let stop:(()=>Promise<void>)|undefined;
afterEach(async()=>{await stop?.();stop=undefined;setLambdaProgramResolver(undefined);setServices({runner:undefined});});
it('stores a live artifact reference without copying execution source or pinning its version',async()=>{
 const db=await harness.db();const owner=await createUser({email:'mxmx_test_schedule_live@example.com'});
 const token=await mintToken('schedule');await claimToken(owner.id,token.token);
 const doc=await(await publish(request('/api/artifacts',{method:'POST',token:token.token,json:{markup:'<p>Live schedule</p>'}}))).json();
 const runner:RunnerService={start:async()=>({runId:'unused'}),getRun:async()=>{throw Error('unused')},events:async()=>({events:[],nextSequence:0,hasMore:false}),cancel:async()=>{}};
 setServices({runner});stop=await startLambdaSchedules(db);
 setLambdaProgramResolver(async()=>({version:'current-1',program:{source:'export default()=>1',language:'javascript'}}));
 const response=await artifactSchedule(request('/api/artifacts/'+doc.id+'/schedules',{method:'POST',actor:{userId:owner.id,credential:'session'},json:{cron:'* * * * *',timezone:'UTC'}}),doc.id);
 expect(response.status).toBe(201);
 const result=await response.json();
 expect(result).toMatchObject({artifactId:doc.id,cron:'* * * * *',timezone:'UTC',enabled:true});
 const stored=(await db.query<{spec:Record<string,unknown>}>('SELECT spec FROM runner_schedules WHERE id=$1',[result.id])).rows[0]!.spec;
 expect(stored).not.toHaveProperty('version');expect(stored).not.toHaveProperty('program');expect(stored).not.toHaveProperty('document');
});
it('uses the same owner-scoped API for CRUD, manual triggers and history, and resolves the latest source',async()=>{
 const db=await harness.db();const owner=await createUser({email:'mxmx_test_schedule_http@example.com'});
 const token=await mintToken('schedule');await claimToken(owner.id,token.token);
 const doc=await(await publish(request('/api/artifacts',{method:'POST',token:token.token,json:{markup:'<Helmet><script type="server">{`export default()=>({marker: "initial"})`}</script></Helmet><p>Live executable</p>'}}))).json();
 const started:import('@artifactbin/contracts').RunStart[]=[];
 const runner:RunnerService={start:async input=>{started.push(input);return {runId:'run-'+started.length};},getRun:async({runId})=>({runId,status:'running',output:null,receipt:null}),events:async()=>({events:[],nextSequence:0,hasMore:false}),cancel:async()=>{}};
 setServices({runner});stop=await startLambdaSchedules(db);

 const call=(method:string,json?:unknown,foreign=false)=>request('/api/schedules',{method,actor:{userId:foreign?'other':owner.id,credential:'session'},...(json===undefined?{}:{json})});
 const {schedulesRequest,scheduleRequest,tickSchedules}=await import('@/lib/runner');
 expect((await schedulesRequest(call('POST',{artifactId:doc.id,cron:'* * * * * *',timezone:'UTC'}))).status).toBe(400);
 expect((await schedulesRequest(call('POST',{artifactId:doc.id,cron:'* * * * *',timezone:'Not/A_Zone'}))).status).toBe(400);
 expect((await schedulesRequest(call('POST',{artifactId:doc.id,cron:'* * * * *',timezone:'UTC',version:'1'}))).status).toBe(400);
 const created=await schedulesRequest(call('POST',{artifactId:doc.id,cron:'* * * * *',timezone:'UTC',input:{value:1}}));expect(created.status).toBe(201);const schedule=await created.json();
 expect((await(await schedulesRequest(call('GET'))).json()).schedules).toHaveLength(1);
 expect((await scheduleRequest(call('GET',undefined,true),schedule.id)).status).toBe(404);
 expect((await scheduleRequest(call('PATCH',{enabled:false}),schedule.id)).status).toBe(200);
 expect((await(await scheduleRequest(call('GET'),schedule.id)).json()).enabled).toBe(false);
 expect((await scheduleRequest(call('PATCH',{enabled:true,cron:'*/2 * * * *'}),schedule.id)).status).toBe(200);
 const ctx={params:Promise.resolve({id:doc.id})};
 const updated=await replace(request('/api/artifacts/'+doc.id,{method:'PUT',token:token.token,json:await observedTextBody(doc.id,'initial','updated-before-dispatch')}),ctx);expect(updated.status,await updated.clone().text()).toBe(200);
 const trigger=await scheduleRequest(call('POST',{requestId:'manual-one'}),schedule.id,'run');expect(trigger.status).toBe(202);
 const repeated=await scheduleRequest(call('POST',{requestId:'manual-one'}),schedule.id,'run');expect(await repeated.json()).toEqual(await trigger.json());
 await tickSchedules();expect(started).toHaveLength(1);expect(started[0]!.program.source).toContain('updated-before-dispatch');expect(started[0]!.artifactVersion).toBe('2');expect(started[0]!.input).toEqual({value:1});
 const history=await(await scheduleRequest(call('GET'),schedule.id,'history')).json();expect(history.history).toHaveLength(1);expect(history.history[0].attempts[0].runId).toBe('run-1');
 expect((await scheduleRequest(call('DELETE',undefined,true),schedule.id)).status).toBe(404);
 expect((await scheduleRequest(call('DELETE'),schedule.id)).status).toBe(200);
 expect((await(await schedulesRequest(call('GET'))).json()).schedules).toHaveLength(0);
});
it('invokes and schedules owner-controlled native program artifacts without a V8 document',async()=>{
 const db=await harness.db();const owner=await createUser({email:'mxmx_test_schedule_native@example.com'});
 const token=await mintToken('program-schedule');await claimToken(owner.id,token.token);
 const definition={version:1,command:['node','-e','console.log(process.env.ARTIFACTBIN_INPUT)']};
 const created=await publish(request('/api/artifacts',{method:'POST',token:token.token,json:{program:definition,visibility:'unlisted'}}));expect(created.status).toBe(201);const doc=await created.json();
 const started:import('@artifactbin/contracts').RunStart[]=[];
 const runner:RunnerService={capabilities:async()=>({version:1,managedProcesses:true,persistence:true,ssh:true,defaults:{vcpu:1,memoryMiB:2048}}),start:async input=>{started.push(input);return {runId:'native-'+started.length};},getRun:async({runId})=>({runId,status:'running',output:null,receipt:null}),events:async()=>({events:[],nextSequence:0,hasMore:false}),cancel:async()=>{}};
 setServices({runner});stop=await startLambdaSchedules(db);
 const {schedulesRequest,scheduleRequest,tickSchedules,invokeArtifact}=await import('@/lib/runner');
 const call=(json:unknown,foreign=false)=>request('/api/schedules',{method:'POST',actor:{userId:foreign?'another-user':owner.id,credential:'session'},json});
 expect((await invokeArtifact(call({requestId:'foreign'},true),doc.id)).status).toBe(404);
 expect((await invokeArtifact(call({requestId:'direct',input:{direct:true}}),doc.id)).status).toBe(202);
 expect(started[0]).toMatchObject({command:definition.command,compute:{vcpu:1,memoryMiB:2048},env:{ARTIFACTBIN_INPUT:'{"direct":true}'},name:`program:${doc.id}`});expect(started[0]).not.toHaveProperty('document');
 expect((await schedulesRequest(call({artifactId:doc.id,cron:'* * * * *',timezone:'UTC'},true))).status).toBe(404);
 const saved=await schedulesRequest(call({artifactId:doc.id,cron:'* * * * *',timezone:'UTC',input:{scheduled:true}}));expect(saved.status).toBe(201);const schedule=await saved.json();
 expect((await scheduleRequest(call({requestId:'native-manual'}),schedule.id,'run')).status).toBe(202);
 await tickSchedules();expect(started).toHaveLength(2);expect(started[1]).toMatchObject({command:definition.command,env:{ARTIFACTBIN_INPUT:'{"scheduled":true}'},compute:{vcpu:1,memoryMiB:2048}});expect(started[1]).not.toHaveProperty('document');
});
